.ci/test_wrapper.sh
.travis.yml
docker/Dockerfile-tpm20

Previously ibmtpm974 was used. This change implements ibmtpm1119
inline with typical use and upstream (tpm-software/*)
This is achieved by updating the Dockerfile for TPM 2.0 and
uploading a new build with the tag `v301` to docker hub.
The travis.yml file is also repointed to the new tag.
test_wrapper.sh is updated to work with the new swtmp.

Docker changes required to replace tpm simulator

---

CONTRIBUTORS.md

This provides information for new contributors, including PR
workflow and code of conduct.
Some placeholders exist for futher pages on setting up a developers
environment and running CI tests locally.

Adds a contributors guide [ci skip]

---

README.md
docker/Dockerfile-tpm20
installer.sh

Recent version of tss doesn't need -I param to
be passed to bootstrap.

Don't pass -I option to bootstrap

---

keylime/cloud_verifier_tornado.py
keylime/tenant.py
test/test_restful.py

change to tenant client api interface
add to an existing node just prints an error
added new update command that will delete and then re-add the node with
new parameters
delete will now confirm that the node was deleted before returning
fixes #75

Tenant loop

---

demo/demo_setup.sh
keylime/create_whitelist.sh

Noticed that there are some issues grabbing the initrd files in modern Debian-based systems using the traditional `gzip`-`cpio` method.  Newer Debian-based systems now provide `unmkinitramfs` to unpack initramfs images, which we can leverage.  In the worst case, fall back to using `gzip`-`cpio`. 
This method also allows `create_whitelist.sh` to be more flexible with parsing init ram images (no need to pass in "initrd" or "initrams" on the command line.

Update demo_setup.sh and create_whitelist.sh for Debian systems

---

demo/node_monitor/tenant_node_monitor.py
keylime.conf
keylime/cloud_verifier_tornado.py
keylime/openstack.py
keylime/registrar_client.py
keylime/registrar_common.py
keylime/tenant.py
keylime/tenant_webapp.py
keylime/tpm1.py
keylime/tpm2.py
scripts/script_check_quote.py
scripts/script_check_quote_raw.py

Please see GH issue #87 for details
Fixes #87

Replace and remove `raise Exception` calls

---

keylime/tpm1.py
keylime/tpm2.py

This breaks functionality in loading payloads into a node, see [keylime/cloud_node.py#L231](https://github.com/keylime/python-keylime/blob/master/keylime/cloud_node.py#L231).  
This will cause an exit out of the provisioning process and prevent any payloads from being loaded in. 
Also, we handle reading from NVRAM failures in the same way.

Writing to NVRAM failures should not be an (uncaught) exception

---

CONTRIBUTORS.md

This change introduces guidance on how to correctly format
a commit message to the CONTRIBUTORS.md file.
Resolves: #116

Outline commit message guidelines in CONTRIBUTORS

---

.travis.yml

This change adds a conditional to check if a pull request
contains only markdown files or is placed into `docs/`.
If the conditional is true, the Travis CI build will be aborted.

If PR only contains .md files or in docs, abort CI

---

.github/stale.yml

This (free) bot marks issues / PRs as stale when there is no activity
for 60 days. It will initially make a comment giving 7 days notice.
Should someone comment or apply a change to a PR, the issue will
no longer be considered stale and the automated close tag will be
aborted / revoked.
This really helps keep the PR / issue queue clean of issues
considered unimportant or PR's that have become abandoned.
More details are available here [0]
[0] https://probot.github.io/apps/stale/

Implement stale bot in keylime/keylime

---

installer.sh
keylime/tpm2.py

Currently Keylime only supports master branch of tpm2-tools (v4+).  This PR adds support for the legacy (v3.X) version of the tpm2-tools (currently used on RHEL, etc.)
Tools have all been upstreamed to 3.X.  Need to update the CI infrastructure to support both current (tpm2-tools v4 fork) and upstream 3.X (https://github.com/tpm2-software/tpm2-tools/tree/3.X) TPM tool code bases. 
PR couples with issue to update CI for v4 tpm2-tools upstream: https://github.com/keylime/keylime/issues/123

Add support for legacy tpm2-tools v3

---

README.md
docker/Dockerfile-tpm20

Since all needed tpm2-tools changes are upstreamed now, we can now
rename instances of keylime/tpm2-tools to tpm2_software/tpm2_tools
Resolves #123

Repoint tpm2-tools to the tpm2_software github org repos

---

keylime/crypto.py

This is not used, and can in some cases cause an exception
when using revocation

Remove redundant str from rsa_import_privkey

---

keylime/cloud_agent.py

use this method to call coroutines so that we don't need python3.7 and 3.6 is sufficient.  this means that compatibility with ubuntu 18.04 is easier

change async calls to support python 3.6

---

installer.sh
keylime.conf
patches/cfsslconf-patch.txt

This change switches the default to openssl.
The idea is that openssl is a rudimentary implementation that
works out of the box with no additional installation steps
required.
This is not to suggest in anyway that cfssl is a second class
citizen, just more that openssl is a better default for testing
and base installations. Should someone want to use CFSSL they
can then perform the installation afterwards.
Another benefit to openssl, is that Keylime can then be deployed
on an air-gapped machine with no need to retrieve anything from
the internet (everything else is in packages now so can be served
by a mirror)
Last of all #145  is the future and CA's will be a pluggable
framework
Also cleaned up some white space.
Resolves: #173

Set openssl as the default

---

keylime/ca_util.py
keylime/cloud_agent.py
keylime/cloud_verifier_tornado.py
keylime/httpclient_requests.py
keylime/ima_emulator_adapter.py
keylime/provider_platform_init.py
keylime/provider_registrar.py
keylime/provider_vtpm_add.py
keylime/registrar.py
keylime/registrar_common.py
keylime/revocation_notifier.py
keylime/secure_mount.py
keylime/serve_uuid.py
keylime/tenant.py
keylime/tenant_webapp.py
keylime/tpm_obj.py
keylime/user_data_encrypt.py
keylime/vtpm_manager.py

This change seeks to set a common shebang for files that are
executable only (e.g. set as entry_points in setup.py)
It is needed to pass `rpmlint` and allow package acceptence
upstream
Resolves: #175

Set standard shebang and only for exec files

---

services/installer.sh
services/keylime_agent.service
services/keylime_agent.service.example
services/keylime_agent.service.template
services/keylime_registrar.service
services/keylime_registrar.service.template
services/keylime_verifier.service
services/keylime_verifier.service.template

This allows standard naming (required for packaging) and also
renames .examples to .templates (so the installer script can still
be used).
It also removes the Unit dependencies which should not be there.
Any of the three services should not need a reliance on others (as
they could be installed on entirely different hosts)

Systemd changes

---

setup.py

This change stops static files being moved into /usr/local/keylime
and instead uses the site-packages destination
It also removes the less than version 6 clause for tornado (as
Fedora 32 / rawhide now uses 6.0.2
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1759276

Changes required for Fedora Packaging acceptance

---

scripts/vtpm_testing_setup.sh

This script contains all the necessary steps for creation of a
KVM/QEMU virtual machine with emulated TPM inside. It can also be
used within other VM.
Mostly based on code by Luke Hinds. Only tested on Fedora 30.

Add script for creation of QEMU/KVM VM with emulated TPM

---

keylime/ca_impl_cfssl.py
keylime/ca_util.py

this improves logging for revocation server errors.  It does not yet fix the problem that the agent will fail silently if there's no connection to the revocation server.  this will require much more zmq development to implement a heartbeat.  i think that's outside the scope of this PR to just improve error handling

Improves logging for revocation server errors

---

keylime/cmd_exec.py
keylime/tpm2.py

Commands such as `tpm2_getcap -c properties-fixed` cause a YAML
formatting error when run against an SLB9665VQ2 TPM
This can be seen in issue #160
This fix provides a simple boolean that can be passed on commands
that break with STDOUT removed
Resolves: #160, #206

Introduce Bool for toggling STDOUT on commands

---

README.md

It has become evident the Keylime is also very popular and fitting
towards Edge and IoT. This change influences the readme to be
less specific to just cloud use only.

README changes to remove tech specific terminology

---

keylime/cloud_verifier_common.py
keylime/crypto.py
keylime/revocation_notifier.py

Revocation events are currently failing (silently) as they cannot
be parsed by `json.dumps`
This is an artefact from the Python 3 port.
Resolves: #220

Fixes revocation events signature format

---

keylime/tenant.py

Currently you can only set a port for the agent in keylime.conf
If you have agents running on different ports, you can only
provision one.
This change allows you to keep using the single port via
keylime.conf, however you can over ride this value by using a
`--tp 9003` arg (with tp being target port).

Adds ability to set the port using the tenant

---

installer.sh

This change either moves the `tpm_cert_store` into place, if none
is present. Or copies only newer certs if not present in the
existing destination (using `-c` no clobber).
Resolves: #231

Move tpm_cert_store into place

---

keylime/cloud_agent.py
keylime/revocation_notifier.py

Currently we do not provide any notification that a revocation event is being sent.
This line adds a simple logger entry to inform the user.

Log that a revocation event is being sent

---

keylime/cloud_agent.py
keylime/cloud_verifier_common.py
keylime/registrar_common.py
keylime/revocation_notifier.py
keylime/tenant.py
keylime/tpm1.py
keylime/tpm2.py
keylime/tpm_abstract.py
test/test_restful.py

Currently, when several agents are polled from the verifier the same
message is printed for each of them. This is ambiguous for the user,
as it provides no info to the user. This change will add agent UUID
in a log message to distinguish between more than one agent.
Resolves: #230

Added agent UUID in verifier IMA log message

---

keylime/crypto.py

Keylime was experiencing the following deprecation warning:
"CryptographyDeprecationWarning: signer and verifier have been
deprecated. Please use sign and verify instead."
This resolves the warning by updating to useing `verify` instead
of `verifier`
Resolves: #222

Changes required for Cryptography Deprecation

---

keylime/tenant.py

Currently, not providing agent port in keylime tenant instantiation
results in a crash. This code change adds fallback to configparser
set value if the port is not provided in the command line.
Resolves: #235

Added code to fallback agent port to configparser set value

---

CODE_OF_CONDUCT.md
CONTRIBUTORS.md

I believe the recommended practice is to have CODE_OF_CONDUCT as an individual document.
In this light, this PR creates this document and updates CONTRIBUTORS to reflect this change, linking to the standalone document.
Hope this helps!
axel

Create CODE_OF_CONDUCT.md + update CONTRIBUTORS

---

keylime/tpm1.py
keylime/tpm2.py
keylime/tpm_abstract.py

Binding of data was not working for TPM2
Must always validate PCR16
Need flexible way to compare expected hash b/t TPM1 and TPM2

Fix bind data (TPM_DATA_PCR) for TPM2 implementation

---

keylime/tenant.py

Currently, the delete command depends on the target host IP even though it
does not use it. This fix remove this dependency.
Resolves: #247

Remove unnecessary dependency of target host IP on the delete command.

---

.ci/test_wrapper.sh
.travis.yml
docker/Dockerfile-tpm20

Use the TPM Kernerl resource manager, instead of tpm2-abrmd
This allows us to test in a container without having to use systemd
for the dbus requirements of tpm2-abrmd
Resolves: #258

Implements Kernel TPM Resource Manager

---

.gitignore

The NVChip file is created also on the root repo dir when running
tests.

[trivial] Add NVChip to .gitignore

---

.ci/run_local.sh

This patch adds the possibility to specify the path of the local
keylime repository as argument of the run_local.sh script or
using the KEYLIME_REPO_PATH environment variable.

Make run_local.sh a bit smarter

---

.ci/run_local.sh
.ci/test_wrapper.sh
.travis.yml
docker/Dockerfile-tpm20
test/test_restful.py

For some reason the systemd-udev package is not installed by
default in the base container image.
Because of that, we see this error when starting the tpm2-abrmd
service:
Failed to start tpm2-abrmd.service: Unit systemd-udev-settle.service not found.
Also commenting out starting condition that requires /dev/tmp* to
be present and not needed in CI.
Fix #271

Fedora 31 based CI image

---

docker/Dockerfile-tpm20

Some improvements to reduce the final size of the image:
Using a list of packages for dependencies
Aggregating some RUN commands
Initializing dnf cache
Removing dnf cache
Also removed duplicate ENV container docker entry
The total size save is around 300MB

Reduce size of docker image for tpm20 tests

---

keylime/revocation_actions/print_metadata.py

The argument reference in print_metadata.execute was changed to
revocation, but the argument itself was not.

Fix arg reference in the print_metadata.py

---

.ci/run_local.sh
.ci/test_wrapper.sh
.travis.yml
docker/Dockerfile-tpm20

We don't actually need to run systemd-udev-settle in container, so
commenting the requirements out from the tpm2-abrmd unit test file.
This should make the new Fedora 31 with tag v101 image works as is
with also the latest size improvement change that removed the
systemd-udev package.

Remove the need for systemd-udev in container

---

.travis.yml

We don't really need ruby anyway and xenial is kind of old now.

Use bionic as base for travis ci

---

keylime/httpclient_requests.py

Make timeout configurable from argument, and we can make it
configurable in the configuration file in the future.
Remove retry count as it doesn't work as expected, we can add retry
mechanism after we sort out which kind of status should be retried.
Use the same code path whether there is body in the request because it's
only a difference in the argument.
Also renamed a few arguments to reflect their real meaning to be less
confusing.

Improve base http request

---

keylime/tpm2.py

Extract the issuer (CA) from the EK certificate, then search for the matching subject in the entire list of signing certs by TPM manufacturers. If found verify the EK certificate against this CA.
Resolves: #27

Improve tpm2.verify_ek to speed up cert matching

---

.gitignore
README.md
installer.sh
requirements.txt
setup.cfg
setup.py
test/run_tests.sh

Use a setup.cfg file to ease managing setup configuration and add
a requirements file to simplify tracking dependencies, leaving
setup.py to take care of the simple setup execution.
Also start using pbr to manage versions.

Separate setup config from setup code

---

keylime/tpm2.py

This commit implements a fix for the keylime_agent when used with a more
recent (03/2020) version of tpm2-tools. At this point, this commit makes
the minimal amount of changes required to have keylime operational, by
simply defining a new "version point" (4.2) and adding the appropriate
conditionals in the multiple if-elif-else statements. Moving forward, a
cleaner refactoring (e.g. using a "command vs tpm2-tools version"
dictionary) looks like a more robust solution in the long term.
Resolves: #272

Fixes incompatibility between keylime and tpm2-tools >= 4.2

---

setup.cfg

Python3.8 is starting to come as a standard version now (fed 32)
This change adds it to the supported OS in `setup.cfg`

Add Python3.8 as supported

---

setup.cfg
setup.py

Previous data_files syntax was failing to move keylime.conf
into /etc/

Reverts data_files to former format.

---

keylime/registrar_common.py

Actually it was not used thus can be removed.

Remove unused config loading in registrar

---

demo/agent_monitor/tenant_agent_monitor.py

This was just left over from a previous Python 2 to 3 port.

Remove git merge conflict markers

---

keylime/registrar_client.py
keylime/tenant.py

This commit fixes the inability of running `keylime_tenant` in a setup
where Keylime's Registrar and Verifier daemons run on separate hosts.
There is also an attempt at providing a clearer error message when the
registrar cannot be reached at the specified IP address, TCP port.
Resolves: #297

Fix for registrar and verifier running on different hosts

---

keylime/ima.py

This change checks that the regular expression provided in an exclude
list can be successfully compiled before attempting to match paths
against it. Prior to this change, if the exclude list contained an
invalid regular expression, an exception was raised when attempting to
match a path with the exclude list regular expression. This exception
was not successfully handled triggering the verifier to crash that could
result in a denial of service attack.
@lukehinds identified this as being a potential DOS attack after we witnessed the verifier crashed during a joint keylime session.

Catch regex exception for invalid exclude list

---

keylime/cloud_verifier_tornado.py

The agent passed to process_agent can be an orm obj (PUT)
or a dict obj (POST), convert the agent to dict if it's not.
Resolves #310

Fixes requests to reactivate agent causes verifier exception

---

demo/agent_monitor/tenant_agent_monitor.py
keylime/cloud_verifier_common.py
keylime/keylime_agent.py
keylime/tenant.py

Before, it produces warnings like:
SyntaxWarning: "is not" with a literal. Did you mean "!="?

Fix warning: "is" should not be used with literals

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/common.py
keylime/ima.py
keylime/tenant.py
test/test_restful.py

Fixes #314
Exclude list example:
```shell
[root@keylime keylime-dev]# cat ~/excludes.txt
/root/keylime-dev/.*
*
```
Error from the verifier:
```shell
2020-06-05 20:40:21.875 - keylime.cloudverifier - WARNING - Invalid regex: nothing to repeat. Exclude list regex is misformatted. Please correct the issue and try again.
```
Error from the tenant:
```shell
[root@keylime keylime-dev]# python keylime/cmd/tenant.py -v 127.0.0.1 -t 127.0.0.1 -tp 9002 -f /root/excludes.txt -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --whitelist /root/whitelist.txt --exclude /root/excludes.txt -c add
Using config file /root/keylime-dev/keylime.conf
2020-06-05 20:40:20.539 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-05 20:40:20.539 …
```

Update verifier REST API to return error for invalid exclude list

---

scripts/create_whitelist.sh

When /ostree is a directory switch to using the ostree initramfs image location based off what is available in `/proc/cmdline`.
On Fedora CoreOS:
```
[root@cosa-devsh ~]# ./create_whitelist.sh out
Writing whitelist to /var/roothome/out with sha1sum...
Creating whitelist for init ram disk
extracting /boot/ostree/fedora-coreos-08a921dd4b162a14798a5f8892dd0a41b99dbfafdabfcc40a9f95cd9fe9de506/initramfs-5.7.12-200.fc32.x86_64.img
[root@cosa-devsh ~]# wc -l out
61158 out
[root@cosa-devsh ~]#
```
Also tried the change on RHCOS and it succeeded as well.

create_whitelist: ostree system use /boot/ostree/*/initr*

---

keylime.conf
keylime/cloud_verifier_tornado.py
keylime/registrar_common.py
scripts/postgres_tables/registrarmain.sql
scripts/postgres_tables/verifiermain.sql

`check_same_thread` causes an error with postgres and should only
be used with sqlite
Also fixes an issue where the registrar still attempts to create
a sqlite file, even though postgres is configured.
Add missing documentation URL to keylime.conf
Add table creation files for postgres
Resolves: #344

Fixes postgres database configuration

---

keylime.conf
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/httpclient_requests.py

Before the limit was 100MB set by tornado, but now we're explicitly
setting and controlling it ourselves. If this proves to be too
restrictive, we can look at making it configurable in the future.
Fixes issue #337

Allow keylime to use larger whitelists

---

keylime/tenant.py

When using `ek_check_script` (defined under `[tenant]` section on
keylime.conf), make sure the script's output is decoded from byte-string
back to string, given the stopping criterion while parsing the output is
a comparison with an empty string.

Simple fix for ek_check_script support

---

keylime.conf
keylime/revocation_notifier.py

This change seeks to clear up potential confusion over what values
are being set and used for the revocation notifier and reciever
We introduce a `receive_revocation_ip` which can be used by either
the agent or keylime_ca
`cloud_verifier, revocation_notifier_ip` remains as it was and is
used by the verifier.
Also remove the hardcoded `*` wildcard for the config value for
`revocation_notifier_ip` which results in listen on all interfaces
Instead use the config value (as a user may wish to listen on
a specfic IP / interface)
Resolves: #378

Seperate out revocation receiver IP:PORT

---

keylime/cloud_verifier_tornado.py
keylime/cmd/provider_registrar.py
keylime/cmd/registrar.py
keylime/registrar_common.py

verifier and registrar is listening 0.0.0.0 address which could expose
services to unwanted networks. Since there are configurations for the
specific addresses to bind to, let's use it instead.
Resolves #389

Restrict verifier and registrar port listening

---

keylime/cloud_verifier_tornado.py

DELETE /agents is missing a return control and causes
unnecessary db query and improper log.

Missing return in CV API

---

keylime/registrar_common.py

Protected/Unprotected share the same server, just using different socket.

Remove redundant registrar server class

---

keylime/tenant.py

Enable the IMA PCR by adding it to the mask using a 'logical or'
rather than 'adding' it.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.xom>

Enable IMA PCR by adding it to the mask using 'logical or'

---

keylime.conf
keylime/keylime_agent.py

system-uuid from dmidecode can be considered unique and doesn't
change from machine to machine.

Support using system-uuid from dmidecode as agent uuid

---

.travis.yml
Makefile
scripts/check_codestyle.sh
setup.py

This PR adds a script for launching either pep8 or pycodestyle-3 to check the python code style. Also a Makefile is added with a check target for running the script either on a local machine or by Travis. We now also run it as part of the Travis build.

Run code style checks on python files

---

keylime/cloud_verifier_tornado.py

Querying agent returns a query object not the agent itself.

Fix an issue of finding agent in CV

---

keylime/migrations/env.py

Hasn't been hit unless there is an error in the migrations which is why
it didn't cause tests to fail

Fix typo in Exception type

---

keylime/ca_util.py

Basically, the problem stems from the fact that `openssl` produces an
**empty** `cacrl.der` (and `cacrl.pem`).
Resolves: ##261

Minimalistic changes to allow successful execution of `keylime_ca -c listen` with `openssl`

---

.travis.yml
scripts/check_codestyle.sh

Transition from pep8 to pylint. Suppress many pylint errors/warnings that
we have not cleaned up the code for, yet, since those were not supported
by pep8.

codestyle: Transition to pylint

---

auto-ipsec/libreswan/src/local_action_crashsa.py
auto-ipsec/racoon/src/local_action_deletesa.py
keylime/ca_util.py
keylime/cmd_exec.py
keylime/keylime_agent.py
keylime/secure_mount.py
keylime/tpm/tpm1.py
keylime/tpm/tpm2.py
keylime/vtpm_manager.py

Removed shell=True from exec_cmd, currently in a tradeoff
of converting string argument of tpm.__run to list by split.
Issue #131

Remove shell=True from exec_cmd

---

.github/workflows/keylime-bot.yml

Roughly equivalent to https://github.com/keylime/enhancements/pull/35.
Once merged, pull requests will:
- automatically have reviewers requested (currently pulls from Github's suggested reviewers and the `core` team)
- have their assignees updated based on who is most responsible at any given time
Since bot setup was already done for `enhancements`, this should be good to go as is.

Enable PR assignment automation from actions-automation

---

keylime/cloud_verifier_tornado.py

Fixes an error where `keylime_tenant -c reactivate` is called, 
and the`verifier` returns an error complaining about the lack of the key
`provide_V` on the "agent" object. With this small change, `reactivate`
can be properly issued, even after a `verifier` restart, and a new U/V
(and pubkey) exchange will be done.

Fixes an error with `keylime_tenant -c reactivate`

---

keylime/keylime_agent.py
keylime/tpm/tpm1.py
keylime/tpm/tpm2.py
keylime/tpm/tpm_abstract.py
test/test_restful.py

Move stub and metric handling out of tpm.__run, also
handles cmd as a string or iterable.

Move stub code out of tpm.__run

---

keylime/tenant.py

When this command is called, the agent uuid passed to `do_cvstatus` must
be made empty. If not, instead of correctly issuing `GET /agents/`,
returning a list of all agents on a verifier, the aforementioned command
will issue `GET /agents/<default UUID in case one is not specified>`,
resulting in error.

Fix `keylime_tenant -c list`.

---

keylime.conf
keylime/cloud_verifier_common.py

Currently it's not configurable, this PR adds two configuration
options named check_client_cert and defaults to true for verifier
and registrar, when set to false will not validate client certificate.

Optionally validate client certificate

---

keylime/cloud_verifier_common.py

Currently cert related configurations are assumed to be under the
same path, but it's not usually satisfied when certificate is supplied
externally.
This patch provides support to use a cert from configuration option when
the value is an absolute path.

Allow specify absolute path for certifcates

---

keylime.conf
keylime/keylime_agent.py

hostname is considered unique and can be used as agent id.
Other forms of identifiers need to be manually retrieved
thus hard to automate.

Support hostname as agent id

---

keylime/openstack.py

agent does not use tornado, so it's better to switch to
existing requests wrapper to do http requests. This drops
unecessary dependency from the agent.

Use requests to access openstack metadata

---

.ci/test_wrapper.sh
docker/Dockerfile

These changes should support running Keylime's TPM 2.0 tests within a container without needing any of the hacks that were present previously.
Tagging @lukehinds and @puiterwijk for review.

Overhaul container infra to support migrating testing to GH Actions

---

.ci/test_wrapper.sh

Remove KEYLIME_HOME in test_wrapper.sh

---

keylime/registrar_client.py

Allow using absolute path of cert files for the registrar client.
Relates-to: #430

Allow using absolute path of cert for registrar client

---

docker/Dockerfile

Necessary to allow Keylime to run on the container.

Add dbus-daemon to container package list

---

keylime/migrations/env.py
keylime/requests_client.py
scripts/check_codestyle.sh

This patch addresses the following issues detected by pylint:
************* Module keylime.migrations.env
keylime/migrations/env.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module keylime.requests_client
keylime/requests_client.py:1:0: C0114: Missing module docstring (missing-module-docstring)

codestyle: Address issues related to C0114

---

keylime/ca_impl_cfssl.py
keylime/ca_impl_openssl.py
keylime/ca_util.py
keylime/cloud_verifier_tornado.py
keylime/cmd/ima_emulator_adapter.py
keylime/cmd/provider_registrar.py
keylime/cmd/registrar.py
keylime/cryptodome.py
keylime/ima.py
keylime/keylime_agent.py
keylime/registrar_common.py
keylime/tenant_webapp.py
keylime/tpm/tpm2.py
keylime/vtpm_manager.py
scripts/check_codestyle.sh

This patch fixes the following issues detected by pylint:
************* Module keylime.tpm.tpm2
keylime/tpm/tpm2.py:593:27: W0613: Unused argument 'activate' (unused-argument)
************* Module keylime.registrar_common
keylime/registrar_common.py:481:23: W0613: Unused argument 'signum' (unused-argument)
keylime/registrar_common.py:481:31: W0613: Unused argument 'frame' (unused-argument)
************* Module keylime.keylime_agent
keylime/keylime_agent.py:402:33: W0613: Unused argument 'handler' (unused-argument)
keylime/keylime_agent.py:464:9: W0613: Unused argument 'argv' (unused-argument)
************* Module keylime.ca_util
keylime/ca_util.py:66:0: W0613: Unused argument 'args' (unused-argument)
************* Module keylime.vtpm_manager
keylime/vtpm_manager.py:394:31: W0613: Unused …

codestyle: Address issues related to W1505

---

keylime/ca_util.py
scripts/check_codestyle.sh

This patch addresses the following issue detected by pylint:
************* Module keylime.ca_util
keylime/ca_util.py:486:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

codestyle: Address issue related to W0707

---

keylime/tpm/tpm_abstract.py
scripts/check_codestyle.sh
test/test_restful.py

This patch addresses the following issues detected by pylint:
************* Module keylime.tpm.tpm_abstract
keylime/tpm/tpm_abstract.py:303:20: E1101: Instance of 'AbstractTPM' has no '_get_tpm_rand_block' member (no-member)
************* Module keylime.tpm.tpm1
keylime/tpm/tpm1.py:541:20: E1101: Module 'M2Crypto.m2' has no 'bn_to_mpi' member (no-member)
keylime/tpm/tpm1.py:541:33: E1101: Module 'M2Crypto.m2' has no 'hex_to_bn' member (no-member)
keylime/tpm/tpm1.py:542:20: E1101: Module 'M2Crypto.m2' has no 'bn_to_mpi' member (no-member)
keylime/tpm/tpm1.py:542:33: E1101: Module 'M2Crypto.m2' has no 'hex_to_bn' member (no-member)
************* Module keylime.migrations.versions.eeb702f77d7d_allowlist_rename
keylime/migrations/versions/eeb702f77d7d_allowlist_rename.py:41:4: E1101: Module …

codestyle: Address issues related to E1101

---

.travis.yml
scripts/check_codestyle.sh

This patch addresses the following issues detected by pylint:
************ Module keylime.tpm.tpm1
keylime/tpm/tpm1.py:759:12: E0401: Unable to import '_cLime' (import-error)
************* Module keylime.cryptodome
keylime/cryptodome.py:10:0: E0401: Unable to import 'Cryptodome.Random' (import-error)
keylime/cryptodome.py:11:0: E0401: Unable to import 'Cryptodome.Hash' (import-error)
keylime/cryptodome.py:12:0: E0401: Unable to import 'Cryptodome.Cipher' (import-error)
keylime/cryptodome.py:13:0: E0401: Unable to import 'Cryptodome.PublicKey' (import-error)
keylime/cryptodome.py:14:0: E0401: Unable to import 'Cryptodome.Cipher' (import-error)
keylime/cryptodome.py:15:0: E0401: Unable to import 'Cryptodome.Protocol' (import-error)
keylime/cryptodome.py:16:0: E0401: Unable to import …

codestyle: Resolve issues related to E0401

---

keylime/revocation_notifier.py

I doscovered this problem on an upgraded machine. For some reason this
problem was not found before with pylint 2.6.0.
This patch addresses the following issue detected by pylint
************ Module keylime.revocation_notifier
keylime/revocation_notifier.py:15:0: C0411: third party import "import simplejson as json" should be placed before "import zmq" (wrong-import-order)

codestyle: Address issue related to C0411

---

keylime/tpm/tpm2.py

Just ensures that ekcert_size parameter (the one after the -s in
tpm2_nvread) is passed to self.__run as a string.

Fixes #486

---

keylime/crypto.py
keylime/cryptodome.py
scripts/check_codestyle.sh

This patch addresses the following issued detected by pylint:
************* Module keylime.cryptodome
keylime/cryptodome.py:75:4: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
************* Module keylime.crypto
keylime/crypto.py:139:4: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
The conversion make use of the fact that the following are producing equivalent ouput:
a=bytearray([11,22,55])
for i in range(len(a)):
for i, _ in enumerate(a):
print(i)
and
a=bytearray([11,22,55])
for i, _ in enumerate(a):
print(i)

codestyle: Address issues relate to C0200

---

keylime/tenant.py

status command doesn't need agent address, exclude it
from the argument validation so we don't need to remember
agent addresses when doing status query.

Improve tenant cli for status query

---

keylime.conf
keylime/db/keylime_db.py
keylime/registrar_common.py

Currently database configuration is breaked into several options,
we could just pass a connection string to SQLAlchemy instead of
constructing the url.
E.g.:
sqlite:////var/lib/keylime/cv_data.sqlite
mysql+pymysql://keylime:keylime@db_host/verifier

Simplify database configuration

---

keylime/tpm/tpm1.py
keylime/tpm/tpm2.py

We don't log random owner password, so shouldn't log config value
either.

Avoid log owner password

---

keylime/cloud_verifier_tornado.py
keylime/db/registrar_db.py
keylime/db/verifier_db.py
keylime/tenant_webapp.py
scripts/check_codestyle.sh

This patch addresses the following issues detected by pylint:
************ Module keylime.cloud_verifier_tornado
keylime/cloud_verifier_tornado.py:66:0: W0223: Method 'data_received' is abstract in class 'RequestHandler' but is not overridden (abstract-method)
keylime/cloud_verifier_tornado.py:92:0: W0223: Method 'data_received' is abstract in class 'RequestHandler' but is not overridden (abstract-method)
keylime/cloud_verifier_tornado.py:115:0: W0223: Method 'data_received' is abstract in class 'RequestHandler' but is not overridden (abstract-method)
************* Module keylime.db.verifier_db
keylime/db/verifier_db.py:15:0: W0223: Method 'process_bind_param' is abstract in class 'TypeDecorator' but is not overridden (abstract-method)
keylime/db/verifier_db.py:15:0: W0223: Method …

codestyle: Address issues related to W0223

---

auto-ipsec/libreswan/src/local_action_crashsa.py
auto-ipsec/racoon/src/local_action_deletesa.py
keylime/ca_util.py
keylime/cmd_exec.py
keylime/secure_mount.py
keylime/tpm/tpm1.py
keylime/tpm/tpm2.py

A lock is aleady held when executing tpm commands, there is no
need to lock in the underlying command, and this is typically not
a good idea.

Remove lock in the command execution

---

keylime/migrations/versions/8a44a4364f5a_initial_database_migration.py

During migration there is a warning
2021-01-13 15:29:49.954 - alembic.runtime.migration - INFO - Running upgrade  -> 8a44a4364f5a, Initial database migration
/usr/lib/python3.6/site-packages/pymysql/cursors.py:165: Warning: (1246, "Converting column 'ima_whitelist' from VARCHAR to TEXT")
result = self._query(query)
The type of ima_whitelist is changed to text from varchar,
set to text initially to avoid this type change.

Fix ima_whitelist db field type

---

.releaserc.yml

A possible fix for the current failure.

Enable Github plugin for semantic-release

---

.ci/test_wrapper_gha.sh
.github/workflows/test.yml

This should run the same test suite currently running on Travis on Github Actions. It should pave the way for Keylime to drop Travis entirely.
Related: https://github.com/keylime/enhancements/issues/18

Run Keylime test suite on Github Actions

---

keylime/keylime_logging.py
keylime/registrar_common.py

When running verifier with keylime user, it complains running as root,
but the /var/log/keylime/cloudverifier.log has correct privilge set
during package installation. Since REQUIRE_ROOT is hardcoded in code,
there is no means to treat verifier/registrar and agent differently,
this patch removes root checking and rely on the proper configuration
at deployment.
Also fixes the issue that registrar never logs to file.
Relates-to: #436

Allow non-root logging

---

keylime/cloud_verifier_tornado.py

It's not necessarily tight with request handler, by moving
it to the outter scope, it is possible to re-trigger agent
processing during verifier startup.
Resolves: #393

Move agents handling out of tornado request handler

---

.github/workflows/test.yml

This replicates the lint step present in the Travis testing config by installing necessary Python dependencies and running `make check`.
Resolves #509

Add lint check to "test" workflow

---

keylime/migrations/versions/8da20383f6e1_extend_ip_field.py

Add migration script to extend the ip field capacity to hold up
to 255 characters.
Resolves: #498

Extend capacity of verifiermain.ip field

---

keylime/tenant.py

Response object from requests doesn't have status attribute,
some code path will hit this:
AttributeError: 'Response' object has no attribute 'status'
Response doesn't have read() method either, changed to use text
attribute.
Signed-off-by: Kaifeng Wang <kaifeng.w@gmail.com>

Fix response handling in tenant

---

keylime/revocation_notifier.py

I had initially planned to also close the socket, but it appears that's not necessary, if my understanding of the PyZMQ documentation is correct.
So this patch simply removes the lingering frontend socket file before the revocation notifier process is killed.
Signed-off-by: axelsimon <github@axelsimon.net>

Remove revocation notifier's ZMQ frontend socket file before killing the process

---

keylime/migrations/versions/a7a64155ab3a_add_ima_filesigning_keys_column.py

The DB migrations script for the IMA keys did not link in properly with
the existing scripts, failing the test cases. This patch fixes this and
the upgrade history is now correct:
$ PYTHONPATH=. alembic -c keylime/migrations/alembic.ini history
8da20383f6e1 -> a7a64155ab3a (head), Add ima_sign_verification_keys column
eeb702f77d7d -> 8da20383f6e1, extend_ip_field
8a44a4364f5a -> eeb702f77d7d, allowlist rename
<base> -> 8a44a4364f5a, Initial database migration

db: Fix DB migrations script revisions

---

keylime/ima_file_signatures.py

This patch fixes the following issue on the verifier side when no
string representation of an IMA keyring is found in the DB.
2021-01-20 15:58:55.083 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 5.0
2021-01-20 15:58:55.084 - keylime.cloudverifier - ERROR - list indices must be integers or slices, not str
File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/cloud_verifier_tornado.py", line 437, in invoke_get_quote
if cloud_verifier_common.process_quote_response(agent, json_response['results']):
File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/cloud_verifier_common.py", line 202, in process_quote_response
ima_keyring = ima_file_signatures.ImaKeyring.from_string(agent['ima_sign_verification_keys'])
File …

ima: Return None in case there was no keyring in the DB

---

keylime/registrar_common.py

isAlive removed in Python 3.9, change to is_alive

---

keylime/db/verifier_db.py

This commit, very similar to #376, fixes the SQLAlchemy problem that
appears when one attempts to create a column of type `String` with a
large value (`1048576`) against a MySQL database. This results in the
error `Column length too big for column 'ima_sign_verification_keys'
(max = 65535); use BLOB or TEXT instead")` and here we just change the
`ima_sign_verification_keys` column to `Text(429400000)`. Tested on both
MySQL 5.7.31 and SQLite.
Signed-off-by: Marcio Silva <marcios@us.ibm.com>

SQLAlchemy database schema fix for the new `ima_sign_verification_keys` column

---

keylime/tpm/tpm2.py

It appears that for tpm2-tools 3.2 the tpm2_evictcontrol accepts
handle from the -H argument instead of -c.
ERROR: Invalid arguments
ERROR: Unable to run tpm2_evictcontrol
Suddenly hits this issue in a working host.

Fix evictcontrol for tpm2 tools 3.2

---

keylime/ima.py
keylime/ima_file_signatures.py

This PR addresses some more IMA file signature verification 'teething' issues:
- It reduces the logging output on file signatures evaluation. Particularly a log entry indicating a good signature is only shown on logger.debug level
- We now account for bad file signatures in a separate error field and report it
- If an allow list entry is not available then an error is only reported if its signature has not already been evaluated; this allows us to only sign a file and not have an allow list entry on top of it

Address some more IMA file signature verification issues

---

keylime/cloud_verifier_common.py
keylime/config.py
keylime/keylime_agent.py
keylime/tenant.py
keylime/tpm/tpm1.py
keylime/tpm/tpm2.py
keylime/tpm/tpm_abstract.py

* The `agent` will now retrieve TPM 2.0 preboot event log and will ship
it to the `verifier`. The latter will do nothing with it (just receives
and ignores it)
* Adds a new `keylime_tenant` CLI option, `--mb_refstate` (that was a
request from @mpeters) to signal the need for the agent to collect the
the event log. At this point, `keylime_tenant` do not actually process
this option (it shall be processed in a manner similar to IMA in a
future PR), it is simply used to signal the agent that "tpm2 preboot
event log" should be read.
* Hard-coded PCRs [0-9], 14 and path
/sys/kernel/security/tpm0/binary_bios_measurements for the event log
* The `verifier` will output a debug logging message stating that it
received the "tpm2 event log", and will send it down to the `check_pcrs`
method, but …

First PR (of a total of 3) to address #491

---

keylime/tpm/tpm2.py

This PR is to address following exception:
File "/usr/bin/keylime_agent", line 11, in <module>
load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
File "/usr/lib/python3.6/site-packages/keylime/cmd/agent.py", line 15, in main
keylime_agent.main()
File "/usr/lib/python3.6/site-packages/keylime/keylime_agent.py", line 492, in main
'cloud_agent', 'tpm_ownerpassword'))  # this tells initialize not to self activate the AIK
File "/usr/lib/python3.6/site-packages/keylime/tpm/tpm2.py", line 935, in tpm_init
self.__create_ek()
File "/usr/lib/python3.6/site-packages/keylime/tpm/tpm2.py", line 416, in __create_ek
if outjson is not None and current_handle in outjson:
TypeError: 'in <string>' requires string as left operand, not int

Fix an issue that check persistent handles

---

.gitignore

This PR adds to `.gitignore`:
- `.venv`, a common name for a Python virtual environment;
- `.vscode`, the name for the directory that a popular IDE creates for itself; and
- `workspace.code-workspace`, the name suggested by that IDE when it says I should save my current workspace.

Added developer conveniences to .gitignore

---

keylime/config.py
keylime/keylime_logging.py

This allows running Keylime registrar and verifier without root and without manually changing code files.
An example executing of the verifier would be: `KEYLIME_CONFIG=`pwd`/keylime.conf KEYLIME_DIR=`pwd`/workdir/work KEYLIME_REQUIRE_ROOT=off KEYLIME_LOGDIR=`pwd`/workdir/logs/ keylime_verifier`

Allow specifying REQUIRE_ROOT, LOG_DIR and WORK_DIR via environment variables

---

.ci/test_wrapper_gha.sh

The tests currently run swtpm_setup with --allow-signing, which results
in an EK that does not match the EK Certificate.
This removes that, since we do not need signing on the EK.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

CI: Ensure created EK is valid

---

keylime/tpm/tpm_main.py

Right now, the activate_identity function is returning `False`, while
keylime_agent is checking for `None` to return failure.
This means that the `False` is tried to be encoded as a result if the
credential activation procedure failed, which causes very vague errors.
The resulting error:
TypeError: key: expected bytes or bytearray, but got 'bool'
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

tpm_main: make activate_identity return the correct thing on error

---

keylime/cmd/ima_emulator_adapter.py
keylime/keylime_agent.py
keylime/vtpm_manager.py

During the deprecation of tpm1 in 45cb879, the handling of
`need_hw_tpm=True` was removed, which in turn resulted in
no run of `tpm2_startup` and `tpm2_getcap`
Resolves: #556

Fix missing tpm2 commands

---

keylime/common/algorithms.py

This algorithm is seen in Nationz chips, and is in the TCG standard.
Adds sm3_256 to known algorithms, otherwise keylime refuses to run
when the tpm_hash_alg is set to sm3_256.

Adds sm3_256 to the known hash algorithms

---

docker/Dockerfile
installer.sh
keylime/cloud_verifier_common.py
keylime/common/algorithms.py
keylime/config.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
keylime/tpm_bootlog_enrich.py

* The most important change here is the fact that the TPM 2.0 preboot
event log , shipped to the verifier from the agent, will now be
authenticated, by replaying the aforementioned log and comparing it
against the values of PCRs [0-9],14.
* If these do not match, then the node will be considered as failed at
attestation.
* A small utility (tpm_bootlog_enrich.py) is added to perform the log replay.
In the future, it could be replaced by newer versions of tpm2-tools capable
of performing the same activity (several open PRs against the tool with
fixes and improvements)
Signed-off-by: Marcio Silva <marcios@us.ibm.com>

Second PR (of a total of 4) to address #491

---

docker/Dockerfile

We hit an error when quay was building a new version of our image:
Could not pull base image: API error (500): toomanyrequests:
You have reached your pull rate limit. You may increase the
limit by authenticating and upgrading:
https://www.docker.com/increase-rate-limit
So docker hub was throttling quay and killing our build. So switching to
the quay.io version of the same image will keep everything inside of quay
and avoid throttling.

Use the quay.io version of fedora for CI tests

---

docker/Dockerfile

The fedora images in quay dont use generic tags like "latest" or even
"33", so neither should we

More specific base docker image tag

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/measured_boot.py
keylime/migrations/versions/ae898986c6e9_add_mb_refstate_column.py
keylime/tenant.py
keylime/tpm/tpm_abstract.py
test/test_restful.py

* The "measured boot reference state" (mb_refstate), provided via
`tenant` CLI with the option `--mb_refstate` is now parsed (JSON) and
stored on the `verifier` database in a new column (as text)
* The supplied mb_refstate is not yet fully used (but the log is
replayed against and the values of PCRs [0-9][11-15] are checked)
Signed-off-by: Marcio Silva <marcios@us.ibm.com>

Third PR (of a total of 4) to address #491

---

scripts/check_codestyle.sh

This can help when tracking down differences between different runs,
say one in CI and the other in local dev

Add pylint version to check_codestyle output

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/keylime_db.py
keylime/keylime_agent.py
keylime/measured_boot.py
keylime/registrar_client.py
keylime/registrar_common.py
keylime/tenant.py
keylime/tenant_webapp.py
keylime/tpm/tpm_abstract.py
keylime/tpm_ek_ca.py

Use standard python logging format where args are passed to the logging
functions (info(), error(), etc). Not only is this more consistent,
but it's better performant as interpolation doesn't happen until/if the
logs are written.
Before we were all over the place with fstrings, string concat, format
strings (but interpolation done before the function call).

Consistent formatting for logging strings

---

keylime/config.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
keylime/tpm_bootlog_enrich.py

Do not import tpm_bootlog_enrich (which depends on libefivar.so),
on non-x86_64 architectures

Fixes #582

---

keylime/cmd_exec.py
keylime/tpm/tpm_main.py

cmd_exec.run returns a list of byte-like objects containing the error strings
that a command may have returned. The current check must have assumed that a
simple string was returned. Fix this by implementing array_contains_substring
that checks whether any byte-like object or string in an array contains a given
substring.
This fixes issue #585.

agent: Fix the checking for a specific error returned by tpm2_quote

---

keylime/tenant_webapp.py

03132e1d13d introduced a bug when renaming variables that were
overlapping with the outer scope and c775b24dbe removed the then
unused variables. This patch partially reverts those changes and
fixes the path for the private key and certificate.
This patch fixes issue #604.

webapp: Fix private key and certificate path (issue #604)

---

keylime/cmd/ima_emulator_adapter.py

Remove an unnecessary global statement for start_hash since this
variable is accessed read-only. After replaying the log we end up
with the same result in PCR 10 as before this patch.

ima_emulator_adapater: Remove unnecessary global statement

---

keylime/elchecking/tests.py
keylime/tpm/tpm_abstract.py

The agent code does not need to import "measured boot policies"

Very simple fix for the agent (re: measured boot)

---

keylime/config.py

config: Document the measured boot PCRs and what is using them

---

keylime/ca_util.py
keylime/ima.py
keylime/keylime_agent.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
test/oldtest.py

This patch fixes some nits:
- use '|' rather than '+' to build a mask of bits (assuming sanity that if bit n is set twice it is not supposed to lead to bit n+1 to be set as was the case with the '+') 
- explicitly test for tpm2_tools version 4.0 and 4.2 in else branches to be consistent with other cases where the same testing is done in many places in tpm_main.py already. This may be the pessimistic approach that future versions of the tpm2_tools may again be incompatible and need another else branch. The optimistic approach would be to adjust the other cases where we explicitly test for 4.0 and 4.2 and use a simple else instead.
- removes the unused read_measurement_list_bin function attempting to parse the binary measurement list. Is someone persuing parsing the binary measurement list …

WIP: Some cleanups

---

keylime/tpm/tpm_main.py

Currently the PCR16 is included in the quote unconditionally, but
it only makes sense when the data is not None.
Signed-off-by: Kaifeng Wang <kaifeng.w@gmail.com>

Include PCR16 in the quote only when needed

---

keylime/keylime_agent.py

The simplest fix is to just call instance_tpm.flush_keys() whenever the
agent fails during the initial setup

Flush tpm keys upon registration failure - Fixes #620

---

agent_non_root_condition.sh
keylime/keylime_agent.py

There is still a bit of extra setup work to be done in order to run the
`agent` as non-root, but imo, those should be done outside of the main
keylime code (it is a "packaging" issue, not code issue).
1) It is assumed that the non-root user which is running keylime has the
ability to read the TPM device.
2) We need to mount `/var/lib/keylime/secure/` as root, since the mount
command uses `--options`. The solution is to run it as root, and
chown it to correct non-root user.
3) We need to make sure that the non-root user which is running keylime
can read `/sys/kernel/security/ima/ascii_runtime_measurements` and
`/sys/kernel/security/tpm0/binary_bios_measurements`. This could be
done as simple `chown` or as an udev rule.
Signed-off-by: Marcio Silva <marcios@us.ibm.com>

Addresses #436

---

keylime/tenant.py

This is a one liner. Not much to comment.

Fixes #629: Allow reglist to run without a -t argument

---

scripts/check_codestyle.sh

pylint 2.8.0 and later implement R1732 which raises the following types
of linter issues:
keylime/ima.py:481:4: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
Ignore them for now.

codestyle: Ignore R1732 implemented by pylint >=2.8.0

---

keylime/tpm/tpm_abstract.py

Fix the ioctl being used to add entropy to /dev/random. Now the following
warning message disappeared on the agent side.
keylime.tpm - WARNING - TPM randomness not added to system entropy pool: [Errno 22] Invalid argument

tpm_abstract: Fix adding of entropy

---

installer.sh

Copy, rather than move, the certificates to
/var/lib/keylime/tpm_cert_store/.  This way, git status
does not show that all the certificates have been deleted.
Signed-off-by: Ken Goldman <kgold@linux.ibm.com>

installer.sh: Do not delete the local copy of the certificates.

---

keylime/measured_boot.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py

This PR moves measured boot related code into their own functions since check_pcrs is so long now. This makes the code easier to read.

Move measured boot related code into functions to make check_pcrs readable

---

keylime/tpm/tpm_main.py

This function cleans up encryptAIK and fixes the error case where we were not returning enough parameters to the caller. The latter would cause an unpack error on the caller's side in case encryptAIK failed.

Cleanup and fix error case in encryptAIK

---

keylime/keylime_agent.py
keylime/tpm/tpm_abstract.py
test/test_restful.py

Trust the Linux kernel that it gets entropy from various sources.
Recent Fedora kernels for example are compiled with CONFIG_HW_RANDOM_TPM
that add the TPM as an entropy provider:
https://elixir.bootlin.com/linux/v5.12/source/drivers/char/tpm/Kconfig#L30

Remove adding entropy to system rng

---

keylime.conf
keylime/db/keylime_db.py

- Implements all the changes and improvements discussed at length during
PR 514, making it obsolete.
- Add the option to specify, via `keylime.conf`, limits for database
connection pool size. Absolutely required for large-scale deployments.

Fixes and improvements for database configuration

---

keylime/db/keylime_db.py
test/test_restful.py

Fix the database creation while running local tests, ensuring that the
sqlite database directory is correctly created.

Addresses issue #660 (database path while running local tests)

---

keylime.conf

The keylime.conf file should have an ima_allowlist variable in the
tenant section, but it's currently called 'allowlist' therefore leading
to errors when trying to access it.
keylime/ima.py:348:        al_path = config.get('tenant', 'ima_allowlist')
This patch fixes this type of an error when using the tenant tool:
2021-05-11 19:46:27.895 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-05-11 19:46:27.902 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-05-11 19:46:27.903 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-05-11 19:46:27.903 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
File "/usr/lib64/python3.8/configparser.py", line 789, in get
value = d[option]
File …

agent: Rename allowlist to ima_allowlist in keylime.conf

---

keylime/keylime_agent.py

The field ret['retout'] returned from cmd_exec.run(cmd) is a list,
so we have to select the first entry of the list to get to the
value returned by dmidecode.
This patch fixes the following error as pointed out in issue #664:
File "/usr/bin/keylime_agent", line 11, in
load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
File "/usr/lib/python3/dist-packages/keylime/cmd/agent.py", line 15, in main
keylime_agent.main()
File "/usr/lib/python3/dist-packages/keylime/keylime_agent.py", line 507, in main
sys_uuid = ret['retout'].decode('utf-8')
AttributeError: 'list' object has no attribute 'decode'

agent: Fix the usage of dmidecode during the agent startup (issue #664)

---

keylime/config.py

Add an optional fallback parameter with the default value to the config's
get() function and related ones like getint(). If a fallback parameter is
given we will return that fallback parameter in case the section is missing
the given option. The variant without the fallback parameter will throw
an exception in case of a missing parameter.

config: Add optional fallback parameter to get()

---

installer.sh

This patch fixes the following issue described in issue #671:
```
Check for tpm_cert_store
==================================================================================
Creating new tpm_cert_store
cp: -r not specified; omitting directory '/home/stefanb/dev/keylime/tpm_cert_store'
==================================================================================
```

installer: Add '-r' option to cp to copy directory (issue #671)

---

keylime/ima_file_signatures.py
keylime/tenant.py
test/test_ima_verification.py

When an x509 certificate is given, attempt to extract the keyidv2 from the
certificate's subject key identifier digest's last 4 bytes. This is safer
than recalculating it with the sha1 hash since other methods may exist.
For public and public keys extracted from private keys we have to use the
sha1 method.
Also adjust how we store the state of the keys into the database. We now
also store an array of the keyidv2's of all keys.

ima_file_signatures: Extract keyidv2 from x509 certs

---

keylime/tenant_webapp.py

`get_tls_context` search for the TLS certificates and TLS private key.
To do that uses a simple "%s/%s" to build the full path.
The problem is that if the certificates contains already the full path,
the final path will be incorrect.
This patch replace it with `os.path.join`, that respect the full path to
generate the final path.

webapp: fix tls certs paths

---

keylime/ima.py
keylime/ima_ast.py
test/test_ima_ast.py
test/test_ima_verification.py

This PR introduces a flexible way for parsing and validating IMA entries. 
A entry is parsed into an AST with basic input validation and provides functions to reconstruct and validate the template hash. For an entry a validator can be specified which can be specialized based on the IMA template.
Making the parsing more flexible allows Keylime to support more use cases of IMA than files which is introduced with kernel [5.12](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e58bb688f2e44237990dfb6). Those use mostly `ima-buf` as their template format which is currently not supported in Keylime.
For https://github.com/keylime/enhancements/pull/47 this makes it easier to add granular error context because the validation is unified into a single interface to use. …

Increase flexibilty of IMA entry parsing and validation

---

.ci/run_local.sh

The old configuration would result in the following error:
Initializing machine ID from random generator.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Tested with docker version 20.10.7.
Signed-off-by: Thore Sommer <mail@thson.de>

ci: make run_local.sh work with newer docker versions

---

keylime/tpm/tpm_abstract.py

If the values for mb_refstate are empty, the PCRs that are present in
the tpm_policy and belong to the measured boot process are ignored.
This patch check that the PCRs form the policy matches the ones that
comes from the quote when there is no measured boot data.
Fix #694

check_pcrs: match PCR if no mb_refstate is provided

---

keylime/measured_boot.py
keylime/tenant.py

The funcion "process_refstate" check if the parameter is a dict, and if
so returns the same parameter, and if not returns the same parameter.
This function is a noop.  This patch drop the function and the only
place where it is called.

measured_boot: drop process_refstate

---

keylime/tenant.py

As discussed on slack the tenant now has the option for specifying the registrars ip and port.

tenant: add the option to specify the registrar ip and port

---

keylime/ima.py

The pcrval in process_measurement_list originates from the IMA log and is
a hex number in string form. Convert it to its bytes representation once
rather than converting the running_hash every time we do a comparison.

ima: Convert pcrval to bytes to increase efficiency

---

keylime/tenant.py

do_cvdelete sends a delete request, and if received a 202 response
(accepted), actively iterate until the next get receives a 200 or 404.
The issue is that a get of 200 imply that the object is still available,
that causes the "update" operation to fail a bit later (update is a
delete followed of an add, and this last action will fail if the object
is still present)
This patch change the active polling to consider the agent deleted only
when a 404 is received.
Fix #711

tenant: do_cvdelete wait until 404

---

README.md
demo/agent_monitor/autorun.sh
demo/agent_monitor/tenant_agent_monitor.py
doc/xen-vtpm-notes.md
keylime.conf
keylime/tenant.py
test/test_registrar_db.py
test/test_verifier_db.py

This change was a lot less disruptive then I thought
It turns out the python UUID lib generates lower case as default:
```
>>> import uuid
>>> uuid.uuid4()
UUID('fb00e830-7a99-4761-8523-63e494431d7f')
```
So all higher case instances were as a result of the UUID entry
in `keylime.conf`
I have now changed all these to lowercase.
With the code as it it, there will be no need to patch existing UUIDs
in a users database. Anything using `generate` will already be lower
case. Anything that already exists in the db using highercase can
remain that way.
Resolves: #691

Set default UUID as lowercase

---

installer.sh
keylime/ima.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py

This PR uses the tsseventextend tool (found on package tss2), which
reads the binary measured boot log (sent from the `agent` to the
`verifier`), and then uses it to calculate the boot_aggregate.
This is done by using the (also calculated) values for PCRs 0-7(9)
also from the measured boot log (the need for contemplate both
PCRs 0-7 and 0-9 comes from the combination of older kernels and
older versions of grub).

Automatically calculates the boot_aggregate from the measured boot log.

---

keylime/tenant.py
keylime/tenant_webapp.py

Set the verifier-check to True in do_cvreactivate and do_cvdelete,
according to the default value set for the corresponding arg set
in tenant.py.
This handles the issue in tenant_webapp.py where the do_cvreactivate
and the do_cvdelete functions are called without specifying the value
for verifier-check.
Also fix a typo and a reduntant parenthesis.

Add default verifier-check value

---

installer.sh
keylime/agentstates.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/ima.py
keylime/ima_test.py
keylime/keylime_agent.py
keylime/migrations/versions/7d5db1a6ffb0_add_agentstates_columns.py
keylime/tenant.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
requirements.txt
scripts/postgres_tables/verifiermain.sql
test/run_tests.sh
test/test-requirements.txt
test/test_ima_verification.py

This PR introduces incremental attestation for IMA by having the verifier maintain state about the last-requested measurement list entry and the state of the 'running hash' for PCR 10 at the last invocation for each agent separately.
We introduce a new parameter 'ima_ml_entry' in the agent's `quote/integrity` API so that the verifier can request the IMA measurement list at a certain entry number, starting with '0' (zero). An old agent will not look at this parameter and will just return the whole IMA measurement list and a new one may return it from that offset unless it was restarted or the request from the verifier is far beyond the number of measurement list entries (due to reboot maybe). A new agent will also return the indicator of the first measurement list entry it returns and and …

Incremental attestation for IMA

---

keylime/tpm/tpm_abstract.py

The "tpm_policy" dictionary (per-`agent` attribute) is converted
to a string by the code on `tenant.py` (used by `keylime_tenant`).
It is is then processed by the `verifier` even before it is stored
on the database, causing an error. This PR ensures that the the
contents of this attribute is selectively converted back to a
dictionary before processing.

Additional fix for the processing of "tpm_policy"

---

keylime/measured_boot.py

measuredboot.py : get_policy returns a tuple consisting of a policy check object and associated mb refstate data.
In some previous commit the order in the tuple was accidentally reversed. Fixing that.
Signed-off-by: George Almasi <gheorghe@us.ibm.com>

Typo fix in measured boot code

---

keylime/cloud_verifier_common.py

TLS v1 and v1.1 have vulnerabilities which will trigger
security scanners when a `verifier` in a corporate
network. This single-line PR just sets the minimum
TLS version for the `verifier` SSL context, avoiding
this problem.

One-liner to set the minimum version of TLS to v1.2

---

services/keylime_agent.service
services/keylime_agent.service.template

If systemd sends SIGTERM to the agent it terminates the agent immediately without the cleanup functions being called. This will result in the TPM NV being full after a couple of agent restarts.
Using SIGINT instead of SIGTERM fixes this issue.

systemd: Add KillSignal=SIGINT to keylime_agent.service

---

keylime/benchmark/utility_average_logged_deltas.py
keylime/benchmark/utility_make_1_second_interval_average_list.py
keylime/benchmark/utility_plot_time_series.py
keylime/benchmark/utility_smoothed_ts.py
keylime/ca_impl_cfssl.py
keylime/ca_util.py
keylime/cmd/ima_emulator_adapter.py
keylime/cmd/provider_platform_init.py
keylime/cmd/provider_vtpm_add.py
keylime/cmd/user_data_encrypt.py
keylime/elchecking/__main__.py
keylime/elchecking/policies.py
keylime/elchecking/tests.py
keylime/gpg.py
keylime/ima.py
keylime/keylime_agent.py
keylime/measured_boot.py
keylime/migrations/env.py
keylime/revocation_actions/update_crl.py
keylime/revocation_notifier.py
keylime/tenant.py
keylime/tenant_webapp.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
keylime/tpm_ek_ca.py
setup.py
test/test_restful.py

This fixes W1514, W0612 and R1735 pylint errors.
W1514 enforces that an encoding is specified when open is used. 
I defaulted to "utf-8" and  used "ascii" or byte encoding where I was relative sure that this is correct. 
Someone else should also look at those changes to make sure that I haven't made wrong assumptions.

Fixing pylint erros

---

keylime/cloud_verifier_common.py

Hi all,
keylime code is using SSL library version 3.7+ but we have 3.6 in Ubuntu Focal. So, the idea is to adapt the needed calls or use of functions and constants to 3.6 with the same functionality. Following this https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TLSv1 and https://docs.python.org/3/library/ssl.html#ssl.create_default_context,  here is a proposal.
We tested that services are up and running after the change.
Any suggestions or concerns are welcome... Thanks in advance.

Simulating use of SSLContext.minimum_version on ssl v3.6

---

keylime.conf
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/failure.py
keylime/ima.py
keylime/ima_ast.py
keylime/measured_boot.py
keylime/migrations/versions/257fe0f0c039_add_fields_for_revocation_context_to_.py
keylime/tenant.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
test/test_ima_ast.py
test/test_ima_verification.py
test/test_restful.py

I've implemented the general tagging infrastructure and converted the IMA checks to demonstrate it's usage.
Before I now convert the rest of the code base I would like to get some feedback for the current implementation.
Currently Keylime operates in a binary state when it comes failures that cause revocations and does not collect information where and why that revocation happened.
This commit introduces the tagging and collection infrastructure and configuration for revocation events and adding context to them.
SeverityLabel
* Has a name that can be set in the keylime.conf and a severity that is dynamically calculated based on the order in the configuration.
Components
* Is a enumeration that contains the main components of Keylime that can cause events. Must be specified when creating a …

add infrastructure to tag and collect revocation events in Keylime

---

keylime/ima.py

Sanitize the exclude list while it is ingested at `tenant` by removing comments (^#) and empty lines.

---

keylime/tpm/tpm_main.py

This code fix removes the dependency on `tsseventextend` and thereby implicitly on the tss2 package. Whereas previously `tsseventextend` was used to calculate boot aggregate candidates for IMA, now that is done by using Python's `hashlib` functions.
* The code dependency on `tss2_eventlog` is unchanged.
* Possible boot aggregates are computed by using the output of the *parsed* and *replayed* binary boot log. We consider this acceptable (not a security risk) because the boot log is authenticated against the actual tpm quote before the generated boot aggregates have a chance of being used.
* The recalculation of boot aggregates is done in every attestation cycle instead of just once. This is an optimization problem for later consideration.

code improvement: removal of extra dependencies in measured boot attestation

---

keylime/crypto.py

Recent changes to make opens more explicit now open
the revocation cert as binary, so no need to encode it as text.

Fix bug #757 where revoc cert was treated as text

---

keylime.conf
keylime/cloud_verifier_common.py
keylime/revocation_notifier.py

This introduces the option to also send revocation messages via webhook instead of 0mq. 
It is useful for systems that need to act on revocation messages but are not running the Keylime agent.

verifier: add option to send revocation messages via webhook

---

installer.sh
keylime/tpm/tpm_main.py

The linux kernel starting with 4.12 ships with its own resource manager  which makes tpm2-abrmd not needed anymore for most use cases. This changes the installer script to not install tpm2-adrmd and changes the default to `device:/dev/tpmrm0`.
We already dropped the tpm2-abrmd dependency for the Debian package by setting that value manually.

By default use the kernel resource manager instead of tpm2-abrmd

---

keylime/tenant_webapp.py

Fix the following error reported by pylint:
keylime/tenant_webapp.py:350:11: R1714: Consider merging these comparisons with "in" to 'response.status_code not in (200, 404)' (consider-using-in)

pylint: Fix errors related to R1714

---

keylime.conf
keylime/ima_ast.py

This adds the option to either treat ToMToU errors as a failure or not.
@mpeters can you test if this works for you?

ima: make ToMToU errors not a failure by default

---

README.md

Update the README to
- remove mentions of Gitter + replace with Slack
- remove Travis CI badge
- add mention of semver + link to RELEASE.md
- reword some section names and
- fix a few bits and bobs

Update README: remove Gitter, Travis CI, mention semver

---

keylime/ima_ast.py

This will fail in most cases because the file hash is always zero.
Fixes #783

ima: for ToMToU errors skip template content validation

---

keylime/config.py

When getboolean with a fallback was called, it was not converted to a boolean
instead the string was returned.
This now should fully fix #783 .

config: fix getboolean with fallback

---

docker/ci/Dockerfile

This adds a number of dependencies present in `rust-keylime`'s various Dockerfiles - the goal being to unify all of Keylime's testing containers into this one. This will allow for `rust-keylime` to build on the container and for `rust-keylime`'s developers to replace the several existing containers they have.
In essence, I just took all dependencies and missing steps from both [here](https://github.com/keylime/rust-keylime/blob/master/docker/fedora/keylime_rust.Dockerfile) and [here](https://github.com/keylime/rust-keylime/blob/master/tests/Dockerfile) and put them into `keylime/keylime`'s container. I'm not actually sure which steps/packages are necessary and which are not, and I figure we can cut this down if needed.
Tagging @mpeters @lkatalin @lukehinds for review
Signed-off-by: Mark …

Unify `rust-keylime` containers into `keylime`'s test container

---

docker/ci/Dockerfile

`cargo tarpaulin` was not being correctly installed.

Fix missing && in Dockerfile

---

keylime.conf

Those options are only used by the verifier and tenant connect via mTLS
to the registrar. The registrar does not use this API to talk to itself.
`init_client_tls(...)` in `registrar_client.py` uses these options, but this code is not used by the registrar.

config: drop registrar_* TLS options in [registrar] section

---

docker/ci/Dockerfile

The cargo tarpaulin installation doesn't seem to be working when chained with dnf install. The old rust-keylime dockerfile uses a separate RUN command; this commit will try that out.

Move cargo-tarpaulin install to separate command

---

.ci/run_local.sh

Previously, it was cloning `master`, which isn't helpful for local testing. This change makes the test script copy in the local repo instead.

Make run_local.sh use a local copy of the repo

---

.ci/run_local.sh

The volume mount was running into permissions issues due to SELinux. It appears this can be fixed with the `:Z` option: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

Fix permissions issue on volume mount in run_local.sh

---

keylime/ima_ast.py

This now explicitly validates the IMA PCR in the log against what is expected.

ima_ast: check if the PCR is the same as in the config

---

.gitignore

These are generated when using `run_local.sh`.

Update .gitignore with more Keylime-specific files

---

keylime/config.py
keylime/tpm/tpm_main.py

`yaml_to_dict(..)` now returns None if loading failed.
This might happen when non text characters are in the input string. (Which can be the case for `tpm2_eventlog`)
Related to #760

config, tpm_main: explicitly handle YAML load errors

---

keylime.conf
keylime/agentstates.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/cmd/ima_emulator_adapter.py
keylime/common/algorithms.py
keylime/ima.py
keylime/ima_ast.py
keylime/keylime_agent.py
keylime/tenant.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
test/test_ima_ast.py
test/test_ima_verification.py
test/test_restful.py

Modern kernel versions (>= 5.10) hash the IMA entries with all available PCR bank algorithms, but the entry in the IMA log is still the SHA1 entry in most distributions. 
This PR removes the special handling for PCR10 and IMA and just uses the default hash algorithm of the agent.
This also fixes an issue that the hash algorithm for the data PCR might not match between agent and verifier and introduces a new IMA emulator adapter that supports multiple hash algorithms.
Fixes #30, fixes #801

Remove the SHA1 requirement for IMA

---

keylime/cmd/ima_emulator_adapter.py

Fixes the following issue, which followed-up from b0dcaa8:
```
File "/usr/local/bin/keylime_ima_emulator", line 33, in <module>
sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_ima_emulator')())
TypeError: main() missing 1 required positional argument: 'argv'
```
Other utilities under `cmd/` also use this approach.
Signed-off-by: Sergio Correia <scorreia@redhat.com>

ima_emulator: specify sys.argv as the named parameter argv in main()

---

keylime/json.py

Components like the agent do not need it, for instance.
Signed-off-by: Sergio Correia <scorreia@redhat.com>

json: do not make sqlalchemy a hard requirement

---

keylime/elchecking/example.py
scripts/create_mb_refstate

This adds a script `create_mbrefstate` which converts a UEFI eventlog into a valid mb refstate for the example policy.
Also some changes to the example policy are done to make it work out of the box with my Fedora 34 installation.
@ljmcgann can you please verify if this works also for your setup?

Add generator for measured boot refence state for example policy

---

keylime/config.py
keylime/keylime_agent.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py

This fixes various validation issues with the agent and drops `/usr/local` as an included path by default because we do not use a custom patched version of tpm2-tools anymore.

Various code improvements for mostly the agent

---

keylime/ima_ast.py

The handling for ToMToU errors was not extended to handle different hash algorithms correctly.
Fixes #821

ima_ast: fix handling ToMToU errors

---

keylime/cloud_verifier_tornado.py
keylime/revocation_notifier.py

@kkaarreell noticed that the shutdown of the verifier results in an error. This should fix that.

Allow graceful shutdown of the verifier

---

keylime/failure.py
keylime/ima_ast.py

Dataclasses module is not present in Python 3.6, an interpreter still
used in some distributions.
Even there is a 3rd party compatibility module, the current usage seems
not properly justified.  For example, in one of the dataclasses there is
an user-provided __init__ constructor.

Drop dataclasses module usage

---

test/test_restful.py

This strips the line separator before printing, so that no blank lines are printed.

tests: fix stdout formatting for agent and verifier

---

.packit.yaml
keylime/elchecking/example.py
keylime/elchecking/tests.py

This provides the initial hardening of the example policy against event type manipulation. 
This not directly an issue with Keylime, because the UEFI eventlog does not include the metadata in the hash that is used to extend the PCR. The original issue can be found here: https://github.com/google/go-attestation/blob/master/docs/event-log-disclosure.md
The most effective way to mitigate against that is to reduce the usage of `acceptAll ` and limit how often they can be used.
As discussed with @mpeters we will first update our example policy and then provide documentation on how to write custom policies.

Mitigations against event type manipulation in UEFI eventlog

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/config.py
keylime/ima_ast.py
keylime/keylime_logging.py
keylime/revocation_notifier.py
test/data/config/keylime-1.conf
test/data/config/keylime-2.conf
test/data/config/keylime-3.conf
test/test_config.py

And other refactoring of the `config` module

Support multiple configuration files

---

packit-ci.fmf

Enable /functional/keylime_tenant-commands-on-localhost in Packit CI

Enable new test in Packit CI

---

tox.ini

Setting PYTHONWARNINGS to default::DeprecationWarning creates a lot of
noise from pylint itself and makes it harder to read the log.
We can re-enable the setting once pylint does not generate those warnings
anymore.
Signed-off-by: Thore Sommer <mail@thson.de>

ci: disable DeprecationWarning from pylint in tox

---

keylime/ca_impl_cfssl.py
keylime/ca_impl_openssl.py
keylime/ca_util.py

After [1] we moved from M2Crypto to cryptography, and we started to drop
the use of the, now optional, `backend` parameter.  This is OK as we are
explicit on the minimal version of cryptography, but we still use in
other modules (like crypto.py or tpm_main.py for example) the old API.
This patch use the optional `backend` parameter to unify the API usage,
and still be compatible with some older versions of cryptography.
[1] https://github.com/keylime/keylime/pull/747

ca: support back old cyptography API

---

demo/agent_monitor/tenant_agent_monitor.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/config.py
keylime/keylime_agent.py
keylime/registrar_common.py
keylime/tenant_webapp.py
keylime/tornado_requests.py
keylime/web_util.py
test/test_web_util.py

Initially the idea was to convert all the components to the Tornado framework with #835, but moving the current threaded code to async did cause more problems than it solved.
This PR takes the general improvements from #835 without changing the components to Tornado.

Various fixes and improvements to the web components

---

keylime/cloud_verifier_tornado.py

web_util.echo_json_response(..) already calls finish. Calling it twice results in an exception.

verifier: do not call finish() twice

---

keylime/cloud_verifier_common.py
keylime/ima.py
test/test_ima_verification.py

The data sent via the API is JSON not Python dicts.
This failed once I build more complex policies for IMA or measured boot.
@maugustosilva can you confirm that you also expect it to be JSON and not Python dicts?

verifier: use json.loads(..) instead of ast.literal_eval(..)

---

keylime/revocation_notifier.py

If the path was already there, we checked if the socket has the right permissions not the directory. This fails because the file does not exists at that point.

revocation_notifier: fix socket path permission check

---

keylime/tpm/tpm_main.py

The hash algorithm itself is there as a key in the output, but the value is None.
This happened on a Debian + swtpm system were the `tpm2_pcrread` output looks like the following:
```
sha1:
sha256:
0 : 0xE21B703EE69C77476BCCB43EC0336A9A1B2914B378944F7B00A10214CA8FEA93
1 : 0xCB0FD2FC0B87CD3676C1E370DE8446AB4967CF92356B6FCE001CC4F05932FCD6
2 : 0xE8D71943876AA0BE05CF35E32E451C0435388D3B44FA4586843E4B5227033C87
3 : 0xE21B703EE69C77476BCCB43EC0336A9A1B2914B378944F7B00A10214CA8FEA93
4 : 0x5A1C3A55A9E0A037F9FAB97B15C7A71F30DFE362C477957F26671C1165104766
5 : 0x4D7544A02B1EEB2D34DD93A453EF23385EB378F527B21AB094E78E7BD2F160DC
6 : 0xE21B703EE69C77476BCCB43EC0336A9A1B2914B378944F7B00A10214CA8FEA93
7 : 0xE21B703EE69C77476BCCB43EC0336A9A1B2914B378944F7B00A10214CA8FEA93
8 : …
```

Handle missing PCR banks dependent on the hash algorithm correctly

---

keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
test/test_tpm.py

This is an attempt to add a unit testing framework for tpm_main. Required in order to close PR #848 fixing Issue #840.
The gist of this change is to slightly modify the call of tpm.get_tpm_manufacturer() to allow the adding of challenge inputs. The default behavior of the function continues to be to query the TPM device. However, with the additional optional argument relevant portions of challenges representing other TPM devices can be fed to the function.
The initial set of challenges are Infineon Optiga and Nuvoton devices, in addition to swtpm. More to come.
Signed-off-by: George Almasi <gheorghe@us.ibm.com>

Adding unit test for tpm_main

---

keylime.conf
keylime/cloud_verifier_tornado.py
keylime/common/retry.py
keylime/revocation_notifier.py
keylime/tenant.py
keylime/tpm/tpm_main.py
test/test_retry_algo.py

This small patchset adds the option on `keylime.conf`, enabled by default, to use exponential backoff when communication fails (with tpm, tenant and verifier).
Formula is `wait time = base ^ ntries`. With default base value `2`, so that wait times are `1, 2, 4, 8, 16, [...]`, still stopping on max_ntries.

Add exponential backoff on failing for tpm, tenant and verifier.

---

.ci/test_wrapper.sh
keylime/common/retry.py
keylime/config.py
keylime/keylime.conf
keylime/keylime_logging.py
setup.py

The keylime.conf is copied into the package path instead of trying to install it globally into /etc which fails if the user is non root.
We will fallback on this configuration the other potential ones do not exist.
This makes it easier to install Keylime in virtual environments.
Also new Python versions are added and a version for the package is set. 
(I've used 6.4.0 because this will probably the next version.)
Fixes #548

setup.py and config improvements

---

keylime/tpm/tpm_main.py

This is a small fix to proactively fix Issue #840 by identifying non-escaped double quotes in the tpm2-tools output.
The fix is tricky because it is very difficult to test -- I have access to exactly 1 device that shows this error.
In addition, the tpm2-tools have already fixed the defect, so must make sure *escaped* double quotes don't get escaped again in error.
Signed-off-by: George Almasi <gheorghe@us.ibm.com>

Fix for Issue #840

---

docker/ci/Dockerfile

Necessary for the `ss` command, to be used in PR https://github.com/keylime/keylime/pull/812.

Add iproute tool to Dockerfile

---

.github/workflows/pypi-release.yml
pyproject.toml
setup.cfg
setup.py

This adds support for automatically pushing releases to PyPI. I've also moved the `setup.py` to `setup.cfg` because we don't require code running during package creation.
@mpeters you'll need to set the secret `PYPI_API_TOKEN` with a PyPI API token, once the name is transferred to us.
Resolves #790

Add support for automatic PyPI releases

---

keylime/cloud_verifier_tornado.py
keylime/crypto.py
keylime/keylime_agent.py

If the cloud_verifier/multiprocessing_pool_num_workers is different from
1, the call to the `.start()` process will fails, as previous call to
`.add_stockets()` is already initializing the internal ioloop.
The raised exception will be:
File "/usr/bin/keylime_verifier", line 11, in <module>
load_entry_point('keylime==6.3.0', 'console_scripts', 'keylime_verifier')()
File "/usr/lib/python3.6/site-packages/keylime/cmd/verifier.py", line 21, in main
cloud_verifier_tornado.main()
File "/usr/lib/python3.6/site-packages/keylime/cloud_verifier_tornado.py", line 1122, in main
server.start(config.getint('cloud_verifier', 'multiprocessing_pool_num_workers'))
File "/usr/lib64/python3.6/site-packages/tornado/tcpserver.py", line 220, in start …

cloud_verifier_tornado: use fork_processes

---

keylime.conf
keylime/keylime_agent.py

`rsa_keyname` and `mtls_cert` now allow also absolute paths.
The logging level for creation of the keys and mTLS certificate is moved to info.
Related #878

agent: allow absolute paths for NK and mTLS certificate and better logging

---

.ci/test_wrapper.sh
test/run_tests.sh
test/test_restful.py

The current `test_restful.py` test suite runs a number of tests against the Python agent. This pull request adds a number of helper functions and a new set of tests that:
- shut down the Python agent
- start up the Rust agent
- run agent-specific tests against the Rust agent
Currently, one of the tests (`agent_quotes_identity_get`) passes, while others fail (mostly due to missing APIs in `rust-keylime`). I've added skips to the broken tests with documentation on the relevant `rust-keylime` issues blocking them, so it should still pass without fail.

Run existing agent tests against the rust-keylime agent

---

packit-ci.fmf

To simplify manual test execution on CentOS Stream.
See
https://github.com/RedHat-SP-Security/keylime-tests/issues/38

Enable EPEL repo on CentOS Stream in packit.yaml

---

keylime/cloud_verifier_tornado.py
keylime/revocation_notifier.py
packit-ci.fmf

device.destroy() seems to block for infinity in some cases, so we kill the process when this happens.
We now first stop the server to not accept new incoming connections and
then wait for all existing connections to be closed.
Instead of forking with tornado.process.fork_processes() we now use
Python's multiprocessing. This allows us to easily attach signal handlers
to the server processes. Note that we now do not restart a process if it
existed unexpectedly.
Fixes #874, #841

Better shutdown of the verifier

---

keylime.conf

A small reference to TPM 1.2 was left in keylime.conf, this removes it.

[minor] Remove last trace of TPM 1.2 (hopefully)

---

keylime/revocation_notifier.py

This ensures that those threads do not block on shutdown.

revocation_notifier: mark webhook threads as daemon and add timeout

---

keylime/json.py
keylime/revocation_notifier.py

python-requests will internally use either simplejson (preferred)
or the built-in the json module; when it uses the latter, it may
encounter issues handling bytes instead of strings.
Let's convert the data to str beforand, to avoid this issue.
Resolves: #896

revocation_notifier: convert the data to str in the notifiers

---

installer.sh

This updates the compiled version of tpm2-tss to 3.1 and tpm2-tools to 5.1. 
Also for Ubuntu and Debian installations we now try to use system packages where possible.
Fixes: #688

installer.sh: updated tpm2-{tools, tss}, use system packages if possible

---

services/keylime_agent_secure.mount

Add Keylime secure mount for agent from Debian.
Co-authored-by: Utkarsh Gupta <utkarsh@debian.org>
Co-authored-by: Miriam España Acebal <miriam.espana@canonical.com>

services: add keylime_agent_secure.mount service

---

keylime/cloud_verifier_tornado.py

We already do this for agent entries coming from POST requests, but
not always when we restart and repopulate from the DB.
This should fix issue #603

Add defaults for ephemeral keys for agent records

---

keylime/config.py
test/test_config.py

The configuration search order for RawConfigParser is from left (less
priority) to right (high priority).
This patch set the correct search order and adjust the test.

config: fix config search order

---

packit-ci.fmf

This adds a new plan to Packit CI that runs all e2e tests and reports code coverage.

Enable code coverage measurement for e2e tests in Packit CI

---

.github/workflows/container.yml

Turns out this is already part of the branch selector UI

Remove tag input from container build workflow

---

keylime/measured_boot.py
keylime/tpm/tpm_abstract.py

This small improvement adds the actual name of the selected policy
used to evaluate the measured boot log, in case of a failure, to the "failure event" message.

Add the policy name to failure event

---

keylime.conf
keylime/ima.py
keylime/ima_test.py
keylime/keylime_agent.py
keylime/secure_mount.py
keylime/user_utils.py
keylime/user_utils_test.py

This PR modifies the keylime agent in such a way that root-owned files are opened near process start and then the agent process drops privileges by switching to another user specified by the run_as variable in keylime.conf. By default no privileges are dropped since the root user now needs to prepare the filesystem beforehand and give the run_as user access to the WORK_DIR, which is typically /var/lib/keylime.

Drop privileges of agent process after startup

---

packit-ci.fmf

Restructuring Packit CI test plan to make it more resource-saving. Also, test logs on F35 would be more readable with just one test run being present.

Make Packit CI plan more resource-saving

---

keylime/ca_impl_cfssl.py
keylime/ca_util.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/cmd/provider_platform_init.py
keylime/cmd/provider_vtpm_add.py
keylime/failure.py
keylime/ima.py
keylime/ima_ast.py
keylime/ima_file_signatures.py
keylime/migrations/env.py
keylime/registrar_client.py
keylime/registrar_common.py
keylime/revocation_actions/update_crl.py
keylime/revocation_notifier.py
keylime/secure_mount.py
keylime/tenant.py
keylime/tpm/tpm_main.py
pylintrc

Avoid using formatted message as the format string for logging and use
lazy string formatting instead.  This includes avoiding using f-strings
for logging and prefer the recommended %-string formatting.
The changes include enabling the logging check in pylint to detect
non-recommended strings formatting usage.
Fixes: #535

Use lazy string formatting when logging (#535)

---

keylime/db/keylime_db.py

After a very contentious PR review, it has been established that
`database_url`, normally set to empty, should always takes precedence
over the other `database_*` parameters. However, due to the use of the
`database_pool_sz_ovfl` by sqlalchemy (default `5,10`), one can end up
in a situation where setting
`database_url=sqlite:////var/lib/keylime/cv_data.sqlite` results in the
following failure:
``` TypeError: Invalid argument(s) 'pool_size','max_overflow' sent to
create_engine(), using configuration
SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword
arguments are appropriate for this combination of components.  ```
This happens because the paramaters `pool_size` and `max_overflow`,
automatically added to the sqlalchemy engine object prior to its
creation, are not …

Fix for database_url parameter with sqlite

---

setup.cfg

We now include the static assets folder in the Python package.
Fixes #519

setup: add static assets for webapp

---

keylime.conf
keylime/registrar_client.py
keylime/requests_client.py
keylime/tenant.py
keylime/tenant_webapp.py
test/test_restful.py

This removes all `verify=False` from requests calls outside of the tests and webapp.
Fixes #681

Registrar Client and Tenant validate CA certificates

---

keylime/tenant.py

SHA-2 is a set of cryptographic hash functions but specifically
SHA-256 is used for --allowlist-checksum.

State in --help that SHA-256 is used for --allowlist-checksum

---

keylime/tpm/tpm_abstract.py

The set of missing PCRs is converted to a list before adding it to the failure list.

tpm: fix that the set of missing PCRs is not serializable in failure

---

keylime/common/algorithms.py
keylime/config.py
keylime/failure.py
keylime/ima_ast.py
keylime/json.py
keylime/keylime_logging.py
mypy.ini

This PR adds full type hints to:
- `ima_ast.py`
- `failure.py`
- `algorithms.py`
- `keylime_loggin.py`
- `json.py`
I also added a Mypy configuration with `strict` set to true which should enable most of the Mypy checks.
Once more parts of Keylime have type hints I will add this to the tox configuration.
Part of #929

Add type hints and initial Mypy configuration

---

packit-ci.fmf

This should address an issue on CentOS Stream 8 and 9 where only one prepare
step was executed, symbolic link hasn't been created and as a results we were
testing upstream code instead of the PR one.

Fix prepare step adjustments in packit-ci.fmf plan

---

keylime/cmd/tenant.py
packit-ci.fmf

Now that we are catching errors and making them more user-friendly
we still need to exit with a non-zero exit code so that other
programs can tell when something went wrong

keylime_tenant non-zero exit code on error

---

README.md

tpm2-abrmd is no longer required for newer kernel versions (>=5.4) and running on OSX is not supported.

readme: remove tpm2-abrmd and OSX sections

---

keylime/registrar_client.py
keylime/registrar_common.py
keylime/tenant.py

When the tenant tries do add an agent which is not registered to the registrar or is registered but not active yet, it crashes and gives a traceback similar to:
```
2022-03-25 15:07:44.658 - keylime.registrar - WARNING - GET returning 404 response. agent_id d432fbb3-d2f1-4a97-9ef7-75bd81c00000 not found.
2022-03-25 15:07:44.659 - keylime.registrar_client - CRITICAL - Error: unexpected http response code from Registrar Server: 404
2022-03-25 15:07:44.659 - keylime.registrar_client - CRITICAL - Response code 404: agent_id not found
2022-03-25 15:07:44.659 - keylime.tenant - ERROR - 'NoneType' object has no attribute 'get'
File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/cmd/tenant.py", line 18, in main
tenant.main()
File …
```

tenant: Handle 404 error from registrar gracefully

---

keylime/tenant.py
keylime/tenant_webapp.py

This implements the enhancement proposed in https://github.com/keylime/enhancements/blob/master/66_quote_before_register.md
Swap the order of `do_cv()` and `do_quote()` calls in the tenant.
Fixes: #680

Verify identity quote before adding agent to the verifier

---

keylime/config.py
keylime/db/keylime_db.py
keylime/db/registrar_db.py
keylime/db/verifier_db.py

Add the cache_ok = True flag to the JSONPickleType classes to supress SQLAlchemy warnings and enable query caching for improved performance.
It should be safe to enable caching for the JSONPickleType as it does not include additional state attributes which affects how it renders SQL.
This also adds an option to enable debugging the SQL queries and caching via `DEBUG_DB` environment variable which is only effective when `INSECURE_DEBUG` is also enabled.
See:
- https://docs.sqlalchemy.org/en/14/faq/performance.html
- https://docs.sqlalchemy.org/en/14/core/custom_types.html

Enable SQL query cache for JSONPickleType

---

ima_stub_service/installer.sh
installer.sh

As noted by @kkaarreell we should do a daemon-reload before starting the service, also we should not try to copy files that no longer exist.

tpm_emulator: improve TPM emulator installation

---

test/run_tests.sh

Since openssl became the default ca_implementation in keylime.conf
it is cfssl that needs extra configuration.

Fix cfssl configuration in run_tests.sh

---

.github/workflows/keylime-bot.yml

This group is more geared towards trigage and review
so it's a better group for this automation.

Change GH reviewers to be from developer group

---

keylime/secure_mount.py

mount() call will mount secdir if not mounted.
As a result we end up removing content of an empty mount point.
At the same time this extra mount() call causes a failure
in test_check_umount_umount() from test_secure_mount.py

Avoid mounting secdir while unmounting it

---

installer.sh

The default in Keylime is OpenSSL and this should be reflected in the installer.

installer: use OpenSSL by default

---

keylime/tpm/tpm_main.py

When using tpm2-tools directly with a TPM without a resource manager transient objects were not flushed. This caused the agent to crash because the TPM ran out of storage.
This is the better fix than #952.

tpm_main: flush transient objects

---

setup.cfg

Before we make a new release we should increase the version number.

general: bump Keylime version to 6.3.2

---

keylime/secure_mount.py
packit-ci.fmf

In Python 3.6 mock_open does not support iteration around text
files. This is causing test failures in test_secure_mount.py
which is using mock_open. We workaround the issue by not using
iterator.
For more details see:
https://code-examples.net/en/q/17a1c75
https://bugs.python.org/issue21258

Workaround for mock_open not supporting iteration in Python 3.6

---

packit-ci.fmf
requirements.txt

We are already consuming attributes such as 'minor'
and 'major' introduced by this version in api_version.py.

Bump required packaging module version to 20.0

---

keylime/ca_util.py
keylime/config.py
keylime/keylime_logging.py
keylime/tenant.py
keylime/tenant_webapp.py
keylime/tpm/tpm_abstract.py
test/test_restful.py

Keylime no longer requires to be run as root (except the agent on startup).
The KEYLIME_TEST option is extended to disable tmpfs and change the WORK_DIR to CWD.

remove REQUIRE_ROOT environment option

---

.github/workflows/codeql-analysis.yml

This adds an initial configuration for static code analysis using CodeQL.
Note that it will generate some false positives initially (mainly caused be the tenant webapp), but after that it should be very useful.

ci: add CodeQL analysis

---

keylime.conf
keylime/tenant_webapp.py

This was only used in the tenant webapp code, but not used. No other part of Keylime uses it, so we remove the tls_check_hostnames from the general section of the keylime.conf

config, webapp: remove tls_check_hostnames option

---

keylime/api_version.py
keylime/cloud_verifier_tornado.py
keylime/registrar_common.py
keylime/web_util.py

Adding new capability to mark API versions as "deprecated" which will
be displayed when verifier and registrar start and a warning is issued
anytime a client (agent or tenant) uses a deprecated API.
This will allow us to mark APIs as deprecated before they are fully removed.

Deprecate API version 1.0

---

.github/codeql-config.yml
.github/workflows/codeql-analysis.yml

The webapp is responsible for most of the warning which are false positives.

ci: only run CodeQL on the keylime directory and disable it for the webapp

---

keylime/tenant.py

Unify log messages to make log parsing a bit easier.

Unify log messages about deleting agent from CV

---

keylime/revocation_notifier.py
packit-ci.fmf

Importing the Python module zmq brings in quite a few system
dependencies through libzmq, including cryptographic libraries, while
the revocation notification feature in Keylime is not always desired.
This patch changes the top-level import of zmq to local imports at the
actual usage.
Signed-off-by: Daiki Ueno <dueno@redhat.com>

Defer loading PyZMQ to avoid optional dependency

---

packit-ci.fmf

By using regular expressions we are pulling in tests that are not
intended to run in CI environment.
Also, rename a test plan to ease pattern matching.

List tests in Packit-CI plan explicitly

---

keylime/tornado_requests.py

Assume that "OS Error" will be related to lack of network connectivity
(" No route to host") catch it, and return it as a TornadoResponse

Fixes #996, by properly catching exceptions resulting from network   problems on the verifier.

---

keylime/ima/ima_dm.py

This event is currently not supported in upstream kernels, but we already have
experimental support for it. Adding it to the list of valid names enables full
support for this event.

ima_dm: enable support for dm_target_update events

---

.github/workflows/submit-HEAD-coverage.yaml
.github/workflows/submit-PR-coverage.yaml
scripts/download_packit_coverage.sh

Requires configured GitHub secrect TESTING_FARM_API_TOKEN
Run test job again for a merged pull-request directly through Testing Farm.
This would ensure that there is a baseline for all pull-requests and make
overall code coverage report creation more stable.
Additionally, due to this new approach dowload_packit_coverage.sh was
simplified significantly.

Simplify GitHub Actions used for code coverage processing

---

keylime/cloud_verifier_tornado.py
keylime/elchecking/policies.py
keylime/measured_boot.py

The old behavior was that if the policy name was not found in the registry
the "accept-all" policy was chosen. This might make the user believe that
their setup was correctly because measured boot still works.
The behavior is changed to error on startup if the policy was misconfigured
and now instead of "accept-all" "reject-all" is used to have a more secure
default.
Fixes: #1002

elchecking: error if policy name is invalid, change default to reject-all

---

keylime/tpm/tpm_abstract.py

Fixes https://github.com/keylime/keylime/issues/1007

Fix order of parameters in an error message

---

keylime/tpm/tpm_main.py

This caused the following error:
```
Exception: Command: ['tpm2_eventlog', '--eventlog-version=2', '/tmp/tmpdtbwirrz'] returned 1, expected 0, output [], stderr [b'ERROR: Unable to run tpm2_eventlog\n']
```
I only have seen this in our Docker containers. I have no idea why the e2e test never ran into this issue.

tpm_main: fix temp file handling in parse_binary_bootlog(..)

---

keylime/cloud_verifier_tornado.py
keylime/tpm/tpm_main.py
scripts/create_mb_refstate

- tpm_main: add failure tagging to measured boot parsing
- verifier: ensure that execptions caused by the agent result in a failure

Better failure tagging for measured boot and fail agent on exception

---

keylime/signing.py

This makes `verify_signature_from_file()` more consistent in that it will
always raise an exception informing the signature verification failed,
when this situation happens.
As it is, `verify_signature()` can raise a few different exceptions, and
those were not handled by `verify_signature_from_file()`.

Improve error handling when doing signature verification

---

.github/workflows/test.yml
keylime/revocation_notifier.py
keylime/web_util.py
test/test_fs_util.py
test/test_restful.py
tox.ini

As the minimal supported version of Python is 3.6, run the lint check
in the CI with that version to catch any usage of >= 3.7 features.
This utilizes the multiple Python interpreter support in Fedora:
https://developer.fedoraproject.org/tech/languages/python/multiple-pythons.html
Signed-off-by: Daiki Ueno <dueno@redhat.com>

ci: Run lint with Python 3.6 as well

---

packit-ci.fmf

Update fmf plans for enabling run test with simple
IMA policy. With simple IMA policy will be run one
test. Then update IMA policy to signing policy and
run all tests.

Update fmf plans to run test with IMA policy

---

keylime.conf
keylime/cloud_verifier_tornado.py
keylime/ima/ima.py
keylime/tenant.py
test/test_ima_verification.py
test/test_restful.py

This PR refactors how allowlists are read and processed by the tenant and verifier, enabling verifier-side signature checks.
Now, instead of all allowlist processing being done tenant-side, the tenant sends the raw allowlist artifact along with any provided validation artifacts (checksum, signature, signing key) as a bundle to the verifier. (Note that the existing tenant-side signature check is preserved.)
The verifier will then unbundle everything and perform its own signature validation step before performing the final processing step and storing the formatted allowlist in the database as before.
This enhances security by thwarting compromised tenant attacks - prior to this, Keylime's security model relied on a trusted tenant; however, if a malicious tenant sent a bad payload (ex. one …

Refactor allowlist reading/sending to enable verifier-side signature checks

---

keylime/user_utils.py

On some distributions the keylime user's primary group may not have
permission to access /dev/tpmrm0 devices. For example, on Fedora,
/dev/tpmrm0 is owned root:tss, but keylime runs keylime:keylime,
with 'tss' as a supplementary group.
We need to load supplementary groups when dropping privileges,
otherwise we'll be unable to access the TPM device.
Resolves: #1038
Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>

keylime: initialize supplementary groups when dropping privileges

---

keylime.conf

Since PR#795 keylime supports agent revocation mechanism.
Together with the rust-agent usage users can avoid using
zeromq completely. This change is a step towards using more
secure default setup.

Set revocation_notifiers = agent as default in keylime.conf

---

installer.sh
keylime/signing.py
pylintrc
requirements.txt

The former uses GPGME and is the recommended way of using GnuPG from
applications, by the GnuPG initiative, as it provides a better
documented API [1][2].
python-gpg is also already present in some distros, e.g. Fedora and
CentOS Stream, as it is a dependency of their package manager (dnf).
It is also available in other major distros such as Debian, Ubuntu,
OpenSUSE, so no disruptions are to be expected regarding packaging.
[1] https://gnupg.org/software/gpgme/index.html
[2] https://wiki.python.org/moin/GnuPrivacyGuard

RFC: Use python3-gpg instead of python3-gnupg

---

README.md

Docs are building correctly now, so add a badge

Add docs status badge to README

---

packit-ci.fmf

Update fmf plans for enabling run tests 
which checking ek_cert.
Signed-off-by: Patrik Koncity <pkoncity@redhat.com>

Update fmf plans to run tests which checking ek_certs

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/migrations/versions/bf48e0c4751d_add_attestation_count_column.py

This counter, "attestations" is now available via API calls (e.g.,
`keylime_tenant -c status`) and it is stored on the database to preserve
state in case the `verifier` is restarted. Given the availability of
this information, the old "first_verified" attribute is now removed.
This PR is the first one on a series of PRs to implement "Durable
Attestation", also known as "Offline Attestation" (enhancement #73).

Adds a per-agent counter for "successfull attestations" on Keylime.

---

keylime/cloud_verifier_tornado.py

The agent attribute "mtls_cert" can be boolean "None" (API 1.0) or
could be assigned the value "disabled" in case mTLS is purposefully
disabled in post-1.0 API. These changes covers both cases.

Fixes #1057 ensuring that the verifier can be restarted cleanly when mTLS for agents is disabled

---

installer.sh

Fixes #1056.
Separated RHEL and Centos due to differences with the PowerTools repository. Enabled the repository first, then installed the build tools.

Update installer.sh for RHEL8, PowerTools

---

keylime.conf
keylime/keylime_logging.py

This PR just removes the hard-coded log file destination, replacing it
with two attributes on `keylime.conf`. In the future, more work will be
needed in order to make the logging system more robust and configurable,
but this minimalistic set of changes fixes a clear and present
operational problem (in production deployments)

Fixes #1063 in a minimalistic way, by making log output configurable

---

scripts/create_allowlist.sh

Related to #1040 
Pass output file name and hash algorithm as flags:
`Usage:  create_allowlist.sh -o [filename] -h [hash-algo]`

Handle output file and algo validation errors

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/migrations/versions/4329e2d14944_associate_moved_allowlists_to_agents.py
keylime/migrations/versions/a72aec03d720_migrate_allowlists_to_separate_table.py
keylime/tenant.py
test/test_restful.py
test/test_verifier_db.py

This is a WIP, draft implementation of a completed Allowlists API. When complete, this will move allowlist storage to their own database, enable allowlist CRD operations through the Keylime tenant, and allow for agents to be provisioned using existing allowlists on the verifier.
This work is still WIP; some things may be rough around the edges. But it is functionally complete.

Complete implementation of the Allowlists API

---

keylime/agentstates.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/migrations/versions/4089e1c79be9_add_tpm_clockinfo.py
keylime/tpm/tpm_main.py
test/test_restful.py

With this chnage, the `verifier` will now use the `tpm2_print` command
to extract clock information from the quote. It will then uses this
information to make decisions about the attestation of the agent (i.e.,
the quote timestamp has to monotonically grow in a TPM which wasn't
restarted/reset). In order to make this comparison the clock information
from the previous quote is stored on the database and then both
timestamps are compared.
While this is not strictly needed for the current implementation of the
"online attestation", it will add yet another attestation check to it,
and is crucial to  "Durable Attestation", also known as "Offline
Attestation" (enhancement #73).

Extracts (and uses) TPM clock information from the quote

---

keylime/cloud_verifier_tornado.py
test/test_restful.py

This PR refactors how allowlists are handled on the verifier, with the goal of catching a few edge cases where database writes could have happened before the verifier realized that an incoming request was incorrect.
Concrete example: user attempts to add an agent and allowlist, but provides an agent UUID that is already in use. Prior to this PR, adding the agent would fail with an error, while adding the allowlist would silently succeed. This would cause additional problems later on. This is fixed by making sure that the verifier won't attempt any database writes of any kind until all sanity checks have succeeded.
This PR also fixes a broken test that used incorrect dummy data (specifically, `test_040_agent_quotes_integrity_get` in `test_restful.py`).
Most of this PR is just moving …

Refactor allowlist handling on verifier to prevent premature DB writes

---

keylime/cloud_verifier_tornado.py

This small issue was found as a side effect during scale testing the keylime rust agent.
Executive summary
--
When verifiers are running in a busy environment, tornado sometimes generates http 408 return codes ("connection timed out"). This can be caused by network traffic or load network buffer overruns -- any number of causes. The correct behavior of cloudverifier-tornado *should be* to retry 408 failures with the usual exponential backoff algorithm.
Test setup
--
The setup involves 5 verifiers and 680 agents (all rust agents) running attestation at the usual 2 second rate. Everything is running in small virtual machines, which means that the verifiers are overloaded. In our setup we clocked about 10 failures in 24 hours. With the unmodified code this means the same amount of …

Fix for cloudverifier_tornado: retry 408 errors instead of failing attestation immediately

---

keylime/cert_utils.py
keylime/registrar_common.py
requirements.txt
test/test_cert_utils.py

python-cryptography won't parse malformed EK certs, such as some
Nuvoton ones we have encountered in the field. However, we still
have to deal with these certs anyway, so let's use pyasn1 to parse
the EK cert instead.

registrar: parse EK cert with pyasn1

---

keylime/config.py

It still has the CWD as the default in TEST_MODE
Fixes issue #1075

KEYLIME_DIR should not be clobbered in TEST_MODE

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/tenant.py
keylime/tpm/tpm_main.py

While testing KeyLime at scale (hundreds to low thousands of rust
agents), the fact that several error/warn/debug log messages did NOT
include the agent UUID turned post-failure analysis significantly more
complex. This PR makes sure that all relevant messages are kept in a
single line, and all contain the agent's UUID as part of it.

Verifier log message improvements for large-scale testing.

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/migrations/versions/a09cc94177f0_add_last_received_quote.py

A new DB column, containing an epoch timestamp (from the verifier)
records when a quote was received. This new column is then exposed as an
additional parameter on the API (whenever agent status is requested).
In case a verifier thread dealing with an  agent dies (while the
verifier process remains responsive) or in case of a multi-verifier
configuration (where a whole verifier could die, while one keeps
requesting status from a different verifier), there is a way for an user
to make a decision about the "age" of the last successful attestation.

This commit solves #1091 by adding a per-agent verifier-issued epoch timestamp

---

keylime/crypto.py
keylime/web_util.py

After discussing with @mepeters and @ansasaki, I have decided to hold
off on the "main" PRs for "Offline Attestation" (a.k.a. "Durable
Attestation" or DA) until after #1068 is merged. Meanwhile this small PR
introduces changes used by DA: a small utility to locate (registrar or
verifier) mTLS certs from the config file and another to sign artifacts
using such certs in a format which is acceptable by Rekor (Transparency
Log)

Adds two small utilities which are used by "Offline Attestation" (enhancement #73)

---

keylime/cloud_verifier_tornado.py
keylime/ima/file_signatures.py
keylime/tenant.py
test/test_restful.py

Previously, it was possible to delete an allowlist from the verifier while that allowlist was still in use by an agent. Doing so would break the agent on the verifier, and make it impossible to delete (and generally put the verifier in an unrecoverable state). This PR adds a safeguard against that scenario.
It also improves error messaging for `409` errors returned by the verifier; prior to the Allowlists API, that error was assumed to be an agent conflict, but now it can also be due to an allowlist conflict. Error messages should better reflect that now.

Prevent deletion of in-use allowlists + better error handling

---

keylime/cloud_verifier_tornado.py
keylime/db/keylime_db.py
test/test_verifier_db.py

This will make sure it's consistent across verifier, registrar and tenant

Move SQLite ref integrity pragma to keylime_db

---

keylime/cloud_verifier_common.py
keylime/db/verifier_db.py
keylime/migrations/versions/a09cc94177f0_add_last_received_quote.py

In some database backends, such as MySQL, the use of a float as column lead to representation and rounding errors. In order to preserve the information in the most backend-agnostic way possible, we will simply use string (varchar)

A fix for "per-agent verifier-issued epoch timestamp"

---

test/run_tests.sh
test/test_restful.py

Fix testing with the rust agent (triggered by setting the `RUST_TEST` environment variable)
This depends on:
- https://github.com/keylime/rust-keylime/pull/448
- Uses the `tpm_ownerpassword` when generating the EK
- https://github.com/keylime/rust-keylime/pull/432
- Add the `tpm_ownerpassword` to the `keylime-agent.conf`
One test is still skipped due to https://github.com/keylime/rust-keylime/issues/447
Add a test case for the `/keys/verify` endpoint for the rust agent

Fix testing with the rust agent

---

keylime/cli/options.py
keylime/cli/policies.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/common/cli_opts.py
keylime/tenant.py

First of all, several IMA and MB options on `tenant` are now processed on a separate "common" module. Second, a small change is introduced on the `verifier` method `process_quote_response`, where we pass an actual IMA policy (defined as a JSON) instead of a sqlalchemy object.

Small changes required by enhancement #73 "Durable (Offline) Attestation"

---

keylime/ima/file_signatures.py

```
$ pip show cryptography | head -2
Name: cryptography
Version: 38.0.1
$ ./bin/keylime_tenant --help
...
AttributeError: module 'cryptography.utils' has no attribute
'register_interface'. Did you mean: 'verify_interface'?
```
Latest `cryptography` lib dropped register_interface: https://github.com/pyca/cryptography/pull/7234
Recommendation is to just subclass directly, as was done in similar case here:
https://github.com/secdev/scapy/pull/3732/commits/488641868f8f5e54e6fe2dc7ba8fc4b30231d629
pylint exclusions aren't needed after this I think.
Proving `keylime_tenant --help` worked was the extent of my testing.

Replace use of cryptography.utils.register_interface

---

.github/workflows/greetings.yml
.github/workflows/submit-PR-coverage.yaml

This works around a busted actions/first-interaction@v1 until it's fixed https://github.com/actions/first-interaction/issues/101
Even after it's fixed it's probably good to keep around just so it won't block merges in the future.

GH first-interaction action is busted, workaround

---

README.md
docs/installation.rst
keylime.conf
keylime/keylime_agent.py
scripts/templates/2.0/agent.j2

This adds the deprecation warnings for the Python agent and makes the Rust agent the official one.
I also updated the installation instructions to be more up to date.
Closes #1111

Make Rust agent offical, improve docs

---

README.md
docs/user_guide/secure_payload.rst

This demo was removed because it was unmaintained.

README, docs: remove reference to ipsec demo

---

keylime/elchecking/example.py

Newer Shims measure if the kernel should trust the keys stored in MokList.
Currently requires a tpm2-tools version with this patch applied: https://github.com/tpm2-software/tpm2-tools/pull/3144

elchecking/example: add support for MokListTrusted variable

---

keylime/elchecking/tests.py

The values can also be an int in the case of the PCRs.

elchecking/tests: fix type hints for Dispatcher

---

demo/ima-policies/ima-policy-keylime
demo/ima-policies/ima-policy-keylime-etc
docs/user_guide/runtime_ima.rst

Since this is almost always the right default if there are containers

Update sample ima-policy to exclude overlayfs

---

keylime/tenant.py

This reverts commit a86588956cfedb64733c841152df17dbca4a3298.
By restricting files to be sent to be utf-8 encoded, this commit made impossible to send zipped payloads using the tenant '-f' sub-option of the 'add' command.
Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

Revert "tenant: open file to send utf-8 encoded"

---

keylime/ca_util.py
keylime/cmd/user_data_encrypt.py
keylime/crypto.py
keylime/tenant.py
test/test_restful.py

Do not require the input data to be utf-8 encoded and read as raw bytes instead. 
This allows binary files to be sent using the tenant `-f` sub-option of the `add` command, including zipped payloads.
This reverts #1141

Allow encrypting arbitraty binary input

---

keylime/ima/ima.py

In case the attested-to host quickly executes files measured by IMA we may run into the case that the keylime agent retrieved the state of the PCR at 'state n' but then IMA appended the log with several entries leading to a log representing 'state n + x' (with x>=1), which may not just be the previously anticipated single additional entry (state n+1). Therefore, remove the check for the number of entries in the log and always compare the running_hash that iterative attestation was resumed with against the provided PCR value from 'state n'.

ima: Fix log evaluation on quick-succession execution of scripts

---

keylime/cloud_verifier_tornado.py

Thanks to @THS-on for reporting the bug - when a request to add an agent is made to the Keylime verifier with no `ima_policy_bundle` parameter, an error occurs. This fixes that error.

Fix improper handling of IMA policy bundle when none is provided

---

keylime/cloud_verifier_tornado.py

Addresses Issue #1146 -- failing tenant add with IMA in unusual circumstances (i.e. unreliable mysql connections, or when attempting to run the same `tenant -c add` command simultaneously from two different tenants).
Signed-off-by: George Almasi <gheorghe@us.ibm.com>

Fix for writing the same allow list twice during agent activation

---

packit-ci.fmf

This service running on background can consume a lot of memory, resulting in OOM killer interrupting tests.

Disable dnf-makecache.service to save RAM

---

services/installer.sh

Currently, file permissions set by services/installer.sh are 666 which makes systemd to complain:
systemd[1]: Configuration file
/etc/systemd/system/keylime_agent_secure.mount
is marked world-writable. Please remove world writability permission bits. Proceeding anyway.

Set permissions of keylime_agent_secure.mount to 664

---

keylime/cmd/ima_emulator_adapter.py
keylime/tpm/tpm_main.py

This PR fixes issue #1106 by handling the failure when trying to read a PCR from an unsupported PCR bank

Fix issue #1106 by handling reading a PCR from an unsupported PCR bank

---

keylime/api_version.py
keylime/ca_impl_openssl.py
keylime/ca_util.py
keylime/cli/options.py
keylime/config.py
keylime/db/keylime_db.py
keylime/migrations/env.py
keylime/requests_client.py
keylime/signing.py
keylime/tpm/tpm2_objects_test.py
keylime/tpm_bootlog_enrich.py
keylime/user_utils.py
pyproject.toml

Following @stefanberger's suggestion, I am splitting #1139 into smaller PRs. This one provides "shallow" fixes, in the sense they should not change the behavior of the code at all:
- uninitialized variables
- variables initialized with wrong types
- missing/incomplete imports
- unspecified exceptions
- missing asserts (e.g., not None, instanceof, callable)
- missing type annotations

chore: shallow type fixes

---

keylime/cmd/convert_ima_policy.py
keylime/ima/ima.py
setup.cfg
test/test_policy_conversion.py

This script should serve as an upgrade path for the eventual IMA policy format overhaul, as laid out in Keylime enhancement https://github.com/keylime/enhancements/pull/71.
Note that this is NOT a complete implementation of the IMA policy format overhaul; it merely produces valid-formatted IMA policies according to the enhancement.

Implement IMA policy conversion script

---

keylime.conf
keylime/cert_utils.py
keylime/registrar_common.py
keylime/tenant.py
keylime/tpm/tpm_main.py
keylime/tpm_ek_ca.py
scripts/ek-openssl-verify
test/run_tests.sh
test/test_cert_utils.py

We had partially addressed the issue we encountered when parsing some
certificates with python-cryptography by writing cert_utils module that
provided a single helper to parse the pubkey from a certificate.
However, we still were doing the EK validation in tpm_main using
python-cryptography, which means we would fall into the same parsing
problem again, since during the validation it would read all the certs
in the tpm cert store to check if it is signing the presented EK.
We address this issue by moving the EK cert verification to cert_utils:
we use the same approach as before, i.e. we parse the cert with pyasn1
when python-cryptography fails, and then use python-cryptography to do
the actual signature verification, as before.
By moving the method to cert_utils, it also becomes simpler …

Move EK cert verification to cert_utils

---

installer.sh

RHEL-9 has the tpm2-tools package available and therefore does not need to build it.

installer: Enable installation on RHEL-9

---

scripts/create_mb_refstate
test/test_tpm.py

Check if the tpm2-tools version is recent enough to have the tpm_eventlog tool available before trying to run the create_mb_refstate script.
Also skip the test for measured boot log parsing test in test_tpm.py if the tpm2-tools version is too old.

Check tpm2-tools before running create_mb_refstate

---

.github/workflows/submit-HEAD-coverage.yaml
scripts/download_packit_coverage.sh

There are occasional failures when submitting code coverage. It is likely that a connections fails and adding --retry could help.

Add --retry 5 parameter to curl

---

docs/rest_apis.rst
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py

While requesting `agent` status, either individually or in bulk (`bulkinfo`), there is simply no need for loading anything from the `allowlists` table on the database, especialmente if the leght of the allowlist for a given agent is non-trivial (e.g., tens of megabytes).
In addition to that, two attributes for the `agent` - `allowlist_len` and `mb_refstate_len` - in addition of being of dubious utility, were being calculated in an incorrect manner. These were dutifully removed.
A meaningful attribute for mesured boot reference states - `has_mb_refstate` is already implemented on this PR.
In a subsquent PR we will find a way to introduce meaningful attribute for IMA allowlists (i.e., `has_ima_allowlist`, or something to that effect), **without** requiring a full load from the database …

cloud_verifier: This is the first PR to address the scalability problems uncovered in #1167, starting with `agent` status.

---

keylime/tpm/tpm_main.py

I missed that statement when I added the check for tpm2-tools version 5.4.

tpm_main: fix ek creation for tpm2-tools versions > 4.2

---

keylime/cloud_verifier_common.py

Only access agent["tpm_clockinfo"] if the filed tpm_clockinfo is
available and its value is not 'None'.
Resolves: https://github.com/keylime/keylime/issues/1178

verifier: Do not access agent["tpm_clockinfo"] if value is 'None' 

---

keylime/cert_utils.py
keylime/tenant.py
keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py
keylime/tpm_ek_ca.py

Following up from the recent refactoring that moved the EK validation to cert_utils, in a few places were added default method values that were reading the configuration files directly.
It was not such a great idea becasue it then made those config files as required to even import the modules.
Example `"from keylime import cert_utils"` now also requires that the tenant configuration be available for getting the path for the TPM cert store.
Let's stop doing that.
Signed-off-by: Sergio Correia <scorreia@redhat.com>

Do not use default values that need reading the config in methods

---

keylime/cloud_verifier_common.py
keylime/common/validators.py
keylime/ima/ima.py
test/test_validators.py

Remove a redundant 'valid' return parameter from functions that also return an error message when the result is not valid and return None otherwise.

Remove redundant return parameters from functions

---

keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py

Remove the redundant 'valid' return parameter from validate_ima_policy_data() and let the error message, that may either be None or an error string, be the deciding factor whether the IMA policy is valid. It's valid if the error message is 'None', invalid otherwise.

common: Remove redundant return parameter from validate_ima_policy_data

---

keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/ima/ima.py
keylime/migrations/versions/2fbc0fb8fa4d_add_checksum_to_allowlist.py
test/test_ima_verification.py

When an user provides an allowlist, a checksum is already automatically calculated (used for comparison when a checksum is also provided, ignored if not). 

ima: this PR adds checksums for allowlists as a separate column on the DB

---

keylime/common/algorithms.py
keylime/common/algorithms_test.py

When trying to instantiate the Hash class using a call like Hash("sha1") one would get a Hash object back. If one was to instantiate Hash("bad"), it would raise a ValueError. With this change the constructor will also raise a ValueError if the hash is not supported by the underlying crypto library, such as may be the case for sm3_256. Therefore, no object would exist for sm3_256 and we wouldn't be able to call the get_size() method that previously also could return None (in case sm3_256 wasn't supported by the crypto library).

Have the Hash class raise a ValueError also on unsupported algorithms

---

keylime/cloud_verifier_common.py

This PR fixes a recently introduced bug (by me) where the return parameters of the function were adjusted to only return an error message instead of the redundant is_valid parameter.

Some fixes to validate_ima_policy_data

---

pyproject.toml

Just removing unnecessary entry from `pyright` ignore list, this should be quite uncontroversial.

chore: clean up pyproject

---

keylime/ima/ima.py
pyproject.toml

Fix the following issues detected by pyright and enable pyright checking on this file.
/home/stefanb/keylime/keylime/ima/ima.py
/home/stefanb/keylime/keylime/ima/ima.py:629:22 - error: Argument of type "Literal['allowlist']" cannot be assigned to parameter "__i" of type "SupportsIndex | slice" in function "__getitem__"
  Type "Literal['allowlist']" cannot be assigned to type "SupportsIndex | slice"
    "Literal['allowlist']" is incompatible with protocol "SupportsIndex"
      "__index__" is not present
    "Literal['allowlist']" is incompatible with "slice" (reportGeneralTypeIssues)
[...]

pyright: Fix an issue in ima/ima.py

---

Makefile
pyproject.toml
tox.ini

This PR extends tox to run 'pyright' and 'black --diff' when running 'make check'

Run 'pyright' and 'black --diff' as part of make check

---

keylime/cli/policies.py
keylime/cmd/convert_ima_policy.py
keylime/ima/file_signatures.py
keylime/ima/ima.py
pyproject.toml

This PR fixes a 2nd batch of issues reported by pyright:
- Raise a ValueError on unsupported key types so that applications using a non-RSA or non-ECDSA don't use the key; this helps to subsequently add restrictive type annotations to ima/file_signatures.py
- Add type annotations to ima/file_signatures.py
- Add type annotations to cmd/convert_ima_policy.py
- Enable pyright checking on files that are clean

pyright: Fix a 2nd batch of issues reported by pyright

---

docs/rest_apis.rst
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/ima/ima.py
keylime/migrations/versions/039322ea079b_add_generator_column.py
test/test_ima_verification.py

With this PR, the `verifier` can load only a few colmuns from the `allowlist` table, giving it the ability to selectively decide if the full row needs to be loaded (very useful for implementing a proxy or cache).
In addition to that, a new column, `generator` is introduced to reflect the fact that an IMA policy was supplied by an user, versus automatically generated as "empty" from within the verifier.

The verifier can selectively load only a subset of columns from the `allowlist` table.

---

keylime/revocation_actions/update_crl.py
pyproject.toml

fixing type issue
[{
"resource": "/home/mdrocco/git/keylime/keylime/revocation_actions/update_crl.py",
"message": "Cannot access member \"encode\" for type \"bytes\"\n  Member \"encode\" is unknown",
"startLineNumber": 52,
"startColumn": 35,
"endLineNumber": 52,
"endColumn": 41
}]
Signed-off-by: Maurizio Drocco <maurizio.drocco@ibm.com>

chore: fix typing in revocation_actions/update_crl.py

---

pyproject.toml

cleaning up pyproject.toml
Removing leftover entry from pyright exclude list: keylime/ca_impl_openssl.py
Signed-off-by: Maurizio Drocco <maurizio.drocco@ibm.com>

chore: cleaning up pyproject

---

keylime/ca_impl_openssl.py
pyproject.toml

Filter-out unsupported private key types and raise a ValueError before trying to sign with the private key. Apply a filter of all those keys that could have possibly been used for signing. Any other type of key would have already thrown an exception since it was not possible to sign an x509 certificate with it.

pyright: Fix a pyright issue in ca_impl_openssl

---

keylime/config.py
keylime/keylime.conf
setup.cfg

The fallback config used the old format which no longer works.

config: remove fallback config

---

keylime/tpm/tpm_abstract.py
keylime/tpm/tpm_main.py

This PR addresses some related to switching the type of variables inside of function or overwriting the value of a function parameter inside a function. In all cases the changes help pyright later on to reason about the type of a variable.

Avoid switching types of variable or overwriting the value of a function parameter

---

keylime/ima/ima.py

A previous PR (#1181) introduced `checksum` as a separate column on the DB for the `allowlists` table. The initial implementation focused on the calculating the checksum for the allowlist, piggybacking already existing code on the `tenant`. However, this is not enough to detect full changes on the "IMA policy" (which will cover also the "exclude list"). This PR now ensures that a checksum is calculated for the whole policy, on the `verifier`.

Calculates the checksum for the whole IMA policy on the verifier

---

keylime/tpm/tpm_main.py

Type-annotate the tools_version field of the tpm class as a 'str'. Fix the code that temporarily assigns the tools_version member a List[str] by using a local variable instead.

tpm: Type-annotate tools_version and avoid switching data types

---

keylime/cmd/convert_ima_policy.py
test/test_ima_verification.py
test/test_policy_conversion.py

This could cause issues with the new integer generator format.

Fix incorrect generators in converted IMA policies

---

keylime/tpm/tpm_main.py

Replace the assert that checks that the version string following a regex search for the tpm2-tools version is not 'None' with an Exception that reports this back to the user. A similar Exception is already thrown before that if TPM2_Startup could not be run at all.

tpm: Replace assert with Exception

---

keylime/cmd/registrar.py
keylime/cmd/verifier.py
keylime/common/migrations.py
setup.cfg

Migrations are normally applied either manually or automatically during startup of
the verifier or registrar, so the option to run the migrations via a standalone
command is no longer required.

cmd: removal of keylime_migrations_apply

---

keylime.conf
keylime/keylime_logging.py
scripts/templates/2.0/registrar.j2
scripts/templates/2.0/verifier.j2

The implementation had the issue that only the main loggers were added and that
the permissions were not set strict enough. Users should use the logging
provided by systemd instead.
Fixes: #1207
Fixes: #1174

logging: remove option to log into separate file

---

keylime/cloud_verifier_tornado.py
keylime/registrar_common.py
keylime/web_util.py
mypy.ini
test/test_web_util.py

Type-annotate web_util.py. The following type annotation forces the casting of rest_params["api_version"] to a str. We can do this since we know that "api_version" has been set in get_restful_params.
def get_restful_params(urlstring: str) -> Dict[str, Union[str, None]]:

codestyle: Type-annotate web_util.py

---

keylime/tpm/tpm2_objects.py
keylime/tpm/tpm2_objects_test.py
mypy.ini

Fix type annotations and variables to avoid type-switching of variables in tpm2_objects.py and tpm2_object_test.py. Add the two files to mypy.

Add some files in keylime/tpm to mypy

---

keylime/api_version.py

Starting with the packaging package v22.0 the parse function does not accept the 'vader' malformed version string anymore that one of our test cases passes but the function now throws an InvaidVersion exception when this string is given. Therefore, catch the InvalidVersion exception on all version.parse() calls and return an appropriate value.
Note: Older versions create a <LegacyVersion('vader')> object.

api_version: Catch InvalidVersion for packaging v22.0

---

keylime/cli/policies.py

Remove policy_pcrs parameter from enforce_pcrs() function since the function introduces a variable with the same name that takes no input from the policy_pcrs parameter. Adjust all the existing callers of this function.

Remove redundant parameter from enforce_pcrs()

---

docker/release/base/Dockerfile.in
docker/release/build_locally.sh

We need the lastest version of tpm2_eventlog to parse logs with newer Shims correctly.

docker: use master of tpm2-tools

---

keylime/tpm/tpm_abstract.py

This is erquired because otherwise the registrar tries to load the verifier configuration.

tpm_abstract: move import of measured_boot into check_pcrs(..)

---

keylime/elchecking/example.py
scripts/create_mb_refstate

In some setups SecureBoot is disabled. MeasuredBoot should still work in that
case. Most GRUB implementations use the SHIM_LOCK protocol to verify
signatures when SecureBoot is enabled which adds an
EV_EFI_BOOT_SERVICES_APPLICATION event for the vmlinuz image. This does not
happen when SecureBoot is disabled.
This introduces the flag "has_secureboot" to the example policy, when this
option is set to false instead of "kernel_authcode_sha256"
"vmlinuz_plain_sha256" is used for verifying the kernel.
Note that those two options are mutually exclusive.
create_mb_refstate is updated to detect if SecureBoot is disabled and can
generate valid refstates for those new options.
Fixes #1197

elchecking: add support for measured boot when SecureBoot is disabled

---

keylime/cli/policies.py
keylime/ima/file_signatures.py
keylime/tenant.py

…ings
The variable ima_sign_verification_keys is a string, so initialize
it with an empty string rather than an empty list.

Fix the ima_sign_verification_keys initial datatype 

---

keylime/cmd_exec.py
keylime/tpm/tpm_main.py

Replace Dict[str, Any] with concrete RetDictType for the return type of cmd_exec.run() and propagate the type to all callers.

Introduce a RetDictType for return type of cmd_exec.run()

---

keylime/cmd/verifier.py
keylime/elchecking/__init__.py
keylime/elchecking/__main__.py
keylime/elchecking/policies.py
keylime/tpm/tpm_abstract.py

- Revert "tpm_abstract: move import of measured_boot into check_pcrs(..)"
- elchecking: load policy modules explicitly
Fixes: #1262

Fix that elchecking policy modules are loaded by agent or tenant

---

keylime/tenant.py

Remove the code that was trying to hash a public key and use the resulting hash as agent UUID. This most likely never worked since the uuid (which is supposed to be the content of a PEM public key file) is passed from the command line as string and hashlib.sha256() does not accept a string as an argument.

tenant: Remove code hashing a public key and using hash as UUID

---

keylime/tenant.py

We have found a scenario (database connection dropped) where a wrong answer from the `verifier` still results in a zero exit code for `keylime_tenant -c bulkinfo`. We fix it by checking the REST response code and then raising an `UserError` exception (which should be used in place of `sys.exit()` on several places inside `tenant.py` anyway)

tenant: fix the exit code for `bulkinfo` operation

---

keylime/cmd/attest.py
keylime/da/attest.py
keylime/da/examples/file.py
keylime/da/examples/redis.py
keylime/da/examples/sqldb.py
keylime/da/record.py
mypy.ini
setup.cfg

Originally, I intended this to be my last PR on the enhancement #73 "Durable (Offline) Attestion". However, I have decided to split it two parts, with an early, much simpler "durable attestation replay CLI", named `keylime_attest` for two reasons:
1) It became clear that the time has come to add at least a very simple
test for it on the CI. Thanks to @aplanas suggestion, we have a
"plain file" backend which would allow this, given this new `keylime_attest` CLI.
2) IMA (runtime) policy is (thankfully) seeing a lot of activity from
@mbestravos and @stefanberger. It is possible that some of the
changes proposed will "break" durable attestation, but it is not fair to demand "running compatibility without a test".
In addition to smal changes to add a (`verifier`-generated epoch timestamp to …

durable attestation: a simple "attestation replay" CLI utility

---

scripts/create_policy

This PR updates and extends the experimental create_policy tool that one can use to add keys or hashes to a Keylime runtime policy.

Update and extend experimental create_policy tool

---

keylime/cloud_verifier_tornado.py
keylime/tenant.py

This PR fixes the problem of having a `verifier` listening on 0.0.0.0 (a case we aim to support, as pointed out by @mpeters) and then adding and deleting (with specific CLI options) an `agent`.
The error stems from the fact that the "verifier_ip" column on the database was populated from the value (0.0.0.0) found on the configuration file (`/etc/keylime/verfier.conf`), which is wrong/useless as a network endpoint. Given the need for an IP address whenever the `tenant` wishes to contact the `verifier` (option -v/--cv on CLI) the contents of the aforementioned column should reflect the value supplied by the former, rather than what is read from the configuration file for the latter. This ensures we will not end up with 0.0.0.0 on the "verifier_ip" column.
Signed-off-by: Marcio Silva …

verifier: proper support for listening on 0.0.0.0 (fixes #705)

---

keylime/cloud_verifier_tornado.py
keylime/tenant.py

This PR extends the keylime tenant tool with the updateruntimepolicy command to enable a user to update an existing named runtime policy. IMA Attestation is NOT reset but simply continues with the new policy.

verifier: Implement updateruntimepolicy to update an existing runtime policy

---

docs/developers.rst
docs/index.rst
docs/installation.rst
docs/requirements.txt
docs/rest_apis.rst
docs/user_guide/runtime_ima.rst

Now from the correct branch
- docs: fix formatting of example IMA-policy
- docs: update theme to min 1.1.0
- docs: remove old development instructions, move dev conainter section
- docs: update REST APIs TLS documentation to match new default setup
- docs: add basic (m)TLS instructions to the installation guide
- docs: point newcomers to the design document
- docs: Update IMA instructions to new runtime policy format

Various documentation updates

---

.github/workflows/test.yml
.pre-commit-config.yaml
keylime/db/registrar_db.py
keylime/db/verifier_db.py
keylime/migrations/versions/4329e2d14944_associate_moved_allowlists_to_agents.py
keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py
keylime/migrations/versions/a72aec03d720_migrate_allowlists_to_separate_table.py
setup.py

This PR fixes some newly reported pylint issues:
```
pylint 2.15.10
astroid 2.13.3
Python 3.9.10 (main, Jan 17 2022, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
************* Module keylime.db.verifier_db
keylime/db/verifier_db.py:10:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
************* Module keylime.db.registrar_db
keylime/db/registrar_db.py:9:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
************* Module keylime.migrations.versions.8c0f8ded1f90_convert_allowlists_to_ima_policies
keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py:47:11: E1123: Unexpected keyword argument 'bind' in constructor call (unexpected-keyword-arg)
keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py:48:4: E1120: No value …
```

pylint: Fix some newly reported issues

---

keylime/revocation_notifier.py

The notify() and notify_webhook() functions are passed the return value of cloud_verifier_common.prepare_error() in cloud_verifier_tornado's notify_error(), which is a Dict[str, Any]. Fix the annotations of these two functions to reflect the input data types.

codesyle: Fix annotations of notify functions in revocation_notifier.py

---

keylime/cmd/convert_runtime_policy.py

Note that this also changes a command line option, since that was incorrect as well.

Fix stray references to "IMA policies" in conversion script

---

keylime/cloud_verifier_tornado.py
keylime/tenant.py

A bit of context: some runtime-policy tests were accidentally disabled (fixed by PR #1307) were accidentally disabled. Once re-enabled they show a couple of bugs on the `verifier` and `tenant` code.
This PR contains fixes for all these (basically need for checking for the presence of certain attributes/keys before referring to and use it)

verifier,tenant : fix IMA runtime policy bug (issue #1306)

---

keylime/da/attest.py
keylime/da/examples/file.py
keylime/da/examples/redis.py
keylime/da/examples/sqldb.py
keylime/da/record.py
keylime/tpm/tpm_abstract.py

The last couple of patches caused some breakages on Durable Attestation (DA), and given the absence of a proper CI test (will work on it after this PR is merged) it remained undetected. Here we have all the fixes needed to bring it back into operational state.
In addition to it, there are some small improvements on logging for the `check_pcrs` method, which benefits both DA and regular operations (basically, include agent ID on all messages, plus the actual name of measured boot policy used)

da: fixes for breakages on durable Attestation

---

keylime/db/keylime_db.py

If sessions are idle for a long time, the SQL server might no longer have that
connection open. This causes the Keylime to error when its tries to query the
database.
This enabled pool_pre_ping which checks if the connection is still active and
uses a new connection if not.
More details can be found here:
https://docs.sqlalchemy.org/en/20/core/pooling.html#disconnect-handling-pessimistic

db: switch to pessimistic disconnect handling

---

docs/rest_apis.rst
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/migrations/versions/f838d3cdeead_add_last_successful_attestation.py

This pull request fulfills https://github.com/keylime/enhancements/issues/74 by adding a new database column (`last_successful_quote`) and exposing it through the verifier's REST API. Many thanks to @maugustosilva for his help with this [in the Slack channel](https://cloud-native.slack.com/archives/C01ARE2QUTZ/p1676370102354909).
Additionally, I've adding some descriptions to the API documentation for the `last_successful_quote` field and a couple other fields that were missing documentation (namely, `attestation_count` and `last_received_quote`).
See commit messages for further details.

Add timestamp of last successful attestation to verifier API (enhancement #74) and address some missing documentation

---

README.md

In preparation of the agent removal, this simplifies the main readme.
I think in the feature, it is probably a good idea to move all technical instructions from the readme to the documentation.

readme: remove installation instructions, update outdated information

---

keylime/ima/ima.py
test/test_ima_verification.py

Old behavior: If the path is also in the allowlist, it needs to also match the digest in there if the signature is valid.
New behavior: Entry is valid if the signature is valid, only when verification fails we check the allowlist.

ima: do not validate against the allowlist if signature was already validated

---

scripts/create_policy

The future release of createrepo_c will, optionally, provide a new metadata, filelists-ext.xml, that will extend filelists.xml with the hashes of the files listed in the RPM package.
During the remote repo analysis, if this file is available it will be used as a shortcut instead of reading the RPM headers.

create_policy: read the hashes from filelists-ext

---

keylime/cloud_verifier_tornado.py
keylime/ima/ima.py
keylime/ima/ima_test.py
keylime/tenant.py
requirements.txt
test/run_tests.sh

This PR adds a JSON schema for the runtime policy along with its package dependency on jsonschema. It then uses the JSON schema to validate the user-provided runtime policies before they are written to the Db.

Add JSON schema for runtime policy and validate user-provided runtime policies against it

---

.packit.yaml
packit-ci.fmf

The COPR repo contains up-to-date RPMs of the upstream Rust agent and using these RPMs will speed up e2e tests.

tests: Use Rust agent from COPR for e2e tests

---

Makefile

Passing multiple -e options doesn't seem to be supported anymore by tox, so switch to a comma-separated list.

build-sys: Use comma-separated list for running multiple linters

---

.packit.yaml
packit-ci.fmf

- Enable CI on all Fedora releases as bug 2171376 has been already fixed
- Remove duplicate content in packit CI test plans utilizing fmf inheritance

Enable Packit CI again on all Fedora releases, simplify packit plans

---

keylime/agentstates.py
keylime/tpm/tpm2_objects.py
keylime/tpm/tpm_main.py

To simplify code and get rid of tpm2_print tool, implement a function that parses TPMS_ATTEST so far that it can extract TPMS_CLOCK_INFO.

Replace tpm2_print

---

docker/release/base/Dockerfile.in

This includes the fix to parse eventlogs with different startup localities.

docker: upate to newer tpm2-tools version

---

MAINTAINERS.md

Redefine the list of maintainers taking into account activity on the last 12 months, proposing a few new names to be added (please feel free to decline)
The main motivation for this commit is the upcoming architecture redesign, and the need for the definition of a core team of active maintainers which will have to agree (at least simple majority) on the implementation in PRs.
We fully expect members of the companies directly involved with Keylime (e.g., RedHat and IBM) and others who approached us demonstrating interesting in the framework (e.g., HP and TwoSigma) to actively participate on the discussion and high-level design, but we want to leave them free from the burden of code review and PR approval (they are welcome to do so, of course)
To the former maintainers who moved on to other …

Redefine the list of maintainers

---

installer.sh

This patch fix the following problem:
and the `/etc/os-release` of Alibaba Cloud Linux OS is like

installer.sh: support Alibaba Cloud Linux OS whose ID is alinux

---

README.md

IMA stubbing support is removed already and the URL in README.md is invalid. so we need to remove the invalid URL correspondingly.
Fixes: #1368 

README.md: remove the invalid URL about IMA stub service.

---

keylime/ima/file_signatures.py
keylime/tpm/tpm2_objects.py
keylime/tpm/tpm_util.py

Convert the hasher lookup tables to hold instances of hashers rather than references to classes that have to be instantiated to get an object. The driving for behind this conversion is to be able to apply proper type-checking for the hashers when they are passed around between functions.

tpm+ima: Convert tables to hold instances of hashers

---

scripts/download_packit_coverage.sh

By not having hardcoded domain name in the regexp pattern we make adding different file hosting services easier.

[tests] Simply coverage file URL parsing

---

scripts/download_packit_coverage.sh

Recent tmt update modified a way how test directories are stored on a disk, adding "-XX" suffix to test
directory name in order to avoid conflicts in repetitive test execution. This patch accommodates 
the download script to this change.

[tests] Update test coverage task name regexp

---

keylime/registrar_common.py
keylime/tpm/ec_crypto_helper.py
keylime/tpm/tpm2_objects.py
keylime/tpm/tpm2_objects_test.py
keylime/tpm/tpm_main.py
keylime/tpm/tpm_util.py
keylime/tpm/tpm_util_test.py

This PR implements the algorithms necessary for running TPM2_MakeCredential outside of a TPM 2 but follows the TPM 2 reference implementation. It then replaces the tpm2_makecredential command line tool invocation with a call to the python function that returns its result in the same format as tpm2_makecredential did.

Replace tpm2_makecredential with a python implementation

---

installer.sh

In tpm2-tools, https://github.com/tpm2-software/tpm2-tools/commit/b3dac7d32f9cdc6154720ecb01d0220cca6d2f79 fix the error `Cannot allocate memory when using --eventlog-version=2`. In keylime, https://github.com/keylime/keylime/blob/master/keylime/tpm/tpm_main.py#L711 also uses the tpm2_eventlog command to pasre MokListTrusted, which gets a similar error ` - root - ERROR - Parsing of binary boot measurements failed with: ['{"message": "running tpm2_eventlog failed"}']`
So we need to 5.4 to fix the bug of parsing for MokListTrusted using the tpm2_eventlog command.
Fixes: #1396 

installer.sh: update TPM2TOOLS_VER to 5.5 and cherry-pick patches to fix the bug of parsing for most newer logs with the tpm2_eventlog command.

---

packit-ci.fmf

Despite the runtime policy rewrite the basic functionality of allowlist and excludelist has been preserved. This test uses keylime_tenant's  --allowlist and --exludelist parameters to verify they are still functional.

[tests] Enable basic allowlist/excludelist test

---

keylime/ima/ima.py

If the runtime policy is large this causes a lot of noise in the logs otherwise.

ima: only log the accept list on validation failure

---

keylime/migrations/versions/4329e2d14944_associate_moved_allowlists_to_agents.py
keylime/migrations/versions/8c0f8ded1f90_convert_allowlists_to_ima_policies.py
keylime/migrations/versions/a72aec03d720_migrate_allowlists_to_separate_table.py

Since version 2.0 of SQLAlchemy we cannot pass strings into the execute method.  We need to use the `text` wrapper type.

migrations: use sa.text for raw SQL

---

templates/2.0/mapping.json

The default value for the TPM owner password should be the empty string to avoid authentication failure on machines with default TPM owner password configuration.
Resolves: #1404

templates: Set empty string as default value for tpm_ownerpassword

---

docker/release/tenant/Dockerfile.in

This installs kubectl into the tenant docker image. This is a requirement for the Kubernetes init jobs in the helm charts.
See the related PR for the helm charts here: https://github.com/keylime/attestation-operator/pull/13

Adding kubectl to tenant docker image for Kubernetes init jobs in helm charts

---

.packit.yaml

dnf5 used in Rawhide doesnt work well with the Testing Farm infrastructure and therefore we need to disable testing on Rawhide temporarily.

tests: Disable Packit CI on Rawhide due to infra issues

---

demo/demo_setup.sh
docs/user_guide/runtime_ima.rst
scripts/create_runtime_policy.sh

In addition to introducing parametrization for all paths, there is now the possibility for the user to supply an exclude list (-e/--exclude_list), which will be automatically incorporated into the policy
Usage: /KL/keylime/scripts/create_runtime_policy.sh -o/output_file FILENAME [-a/--algo ALGO] [-x/--ramdisk-location PATH] [-y/--boot_aggregate-location PATH] [-z/--rootfs-location PATH] [-e/--exclude_list FILENAME] [-s/--skip-path PATH]" optional arguments:
-a/--algo (default sha1sum)
-x/--ramdisk-location (default /boot/, set to "none" to skip)
-y/--boot_aggregate-location (default
/sys/kernel/security/ima/ascii_runtime_measurements, set to "none" to skip)
-z/--rootfs-location (default /, cannot be skipped)
-e/--exclude_list (default none)
-s/--skip-path (default none)
Not extensively …

Several improvements for the "create_runtime_policy.sh" script

---

keylime/cli/policies.py
keylime/cloud_verifier_common.py
keylime/cmd/verifier.py
keylime/da/attest.py
keylime/mba/elchecking/__main__.py
keylime/mba/elchecking/elchecker.py
keylime/mba/elchecking/policies.py
keylime/mba/elparsing/tpm2_tools_elparser.py
keylime/mba/mba.py
keylime/tenant.py
keylime/tpm/tpm_main.py
test/test_mba_parsing.py

The module `keylime/mba/mba` provides an interface for measured boot attestation verification that consists of four functions.
* `bootlog_parse()`
* converts a boot log from binary to JSON.
* authenticates the log by checking the consistency of its digests.
* provides a set of PCRs that can be verified against the TPM quote.
* provides a boot aggregate for use by Keylime IMA verification.
* `policy_load()`
* load a policy from a file into a Python string
* optionally validate that the policy is syntactically correct (this is TBD)
*  `policy_is_valid()`
*  test whether a string is valid policy
* `bootlog_evaluate()`
* check the parsed boot log against the loaded policy, and return a list of policy failures.
A default implementation for all four functions is predefined in Keylime, and is …

mba: making MBA policy parser and checker pluggable

---

scripts/create_runtime_policy.sh

In addition to that, automatically detects the algorithm used for boot aggregate (if one is specified) and exits with error if this differs from the one used with the -a/--algo option

Changes to script create_runtime_policy.sh, fixes #1426

---

keylime/registrar_common.py

Import the "select" module and use "self.request" on it for fix an issue introduced (wrong review) in:
https://github.com/keylime/keylime/pull/1421

registrar_common: fix missing select and sock

---

keylime/tpm/tpm_util.py

The functions to implement TPM2's MakeCredential were taken from the TPM 2 reference implementation that requires that the license and notices be kept but allows for distribution and creation of detrivative works.

tpm_util: Add the BSD license to the file due to functions from TPM 2 code

---

installer.sh

This patch fix the problem that anolis is not currently supported when using the ./installer.sh, so add the installer scripts about anolis.

installer.sh: support Anolis OS whose ID is anolis

---

keylime/cmd/create_policy.py

Initialize an rpm variable in case the rpm module could not be imported and replace HAS_RPM with it. This fixes the following newly detected issues reported by pyright (false positives):
/home/stefanb/keylime/keylime/cmd/create_policy.py
/home/stefanb/keylime/keylime/cmd/create_policy.py:221:10 - error: "rpm" is possibly unbound (reportUnboundVariable)
/home/stefanb/keylime/keylime/cmd/create_policy.py:222:19 - error: "rpm" is possibly unbound (reportUnboundVariable)
/home/stefanb/keylime/keylime/cmd/create_policy.py:222:50 - error: "rpm" is possibly unbound (reportUnboundVariable)
/home/stefanb/keylime/keylime/cmd/create_policy.py:243:5 - error: "rpm" is possibly unbound (reportUnboundVariable)
/home/stefanb/keylime/keylime/cmd/create_policy.py:259:18 - error: "rpm" is possibly unbound …

codestyle: Fix access to possibly not available package 'rpm' (pyright)

---

keylime.conf
keylime/cloud_verifier_common.py
keylime/tpm/tpm_main.py
templates/2.0/mapping.json
templates/2.0/verifier.j2

It allows to control the number of measured boot policy evaluation.

mba: Manage the number of measured boot attestation

---

tpm_cert_store/Alibaba_Cloud_vTPM_EK.pem

Adding the Alibaba Cloud vTPM EK Cert to the tpm_cert_store directory can reduce the need for users to manually import certificates when using keylime on Alibaba Cloud, making it more user-friendly.
Besides, the Alibaba Cloud vTPM EK x509 cert can be downloaded at https://aliyun-tpm-ca.oss-cn-beijing.aliyuncs.com/pki001/ekmf-ca.crt

tpm_cert_store: add the Alibaba Cloud vTPM EK x509 cert

---

keylime/mba/elchecking/example.py

These are generated by edk2 when used with QEMU, but we do not have a reference for them.
Fixes: #1393

elchecking/example: add ignores for EV_PLATFORM_CONFIG_FLAGS

---

keylime/revocation_notifier.py
packit-ci.fmf

Resolves https://github.com/keylime/keylime/issues/1455

Close session in worker_webhook function

---

keylime/ima/ast.py
test/test_ima_verification.py

CentOS currently has file signatures where the signature length indicator seems to be written in little endian. A failure to parse the length indicator causes Keylime to silently discard the signature and the result then is that the pcr template hash is not calculated correctly for the file and the running hash becomes wrong and one ends up with this error message in the log:
IMA measurement list does not match TPM PCR f5e0272e4....
Log the failure if a non zero-length signature was attempted to be parsed.
Resolves: https://github.com/keylime/keylime/issues/1462

ima: Emit a warning when a file signature could not be parsed

---

keylime/tpm/tpm2_objects.py
keylime/tpm/tpm2_objects_test.py

Currently if a tpm key uses a Null scheme `pubkey_parms_from_tpm2b_public()` from `tpm2_objects.py` returns `Error: Misparsed either modulus or keybits` when processing the key. This is because too much is being skipped  when the scheme algorithm is null.
This is fixed by checking for the scheme and only skipping if not null.
Resolves: [Issue 1471](https://github.com/keylime/keylime/issues/1471)

Fix for key parse error in tpm2_objects

---

keylime.conf
templates/2.0/mapping.json
templates/2.0/registrar.j2

The database was introduced as part of the original layered architecture (ref Fig.3
https://github.com/keylime/keylime/raw/master/docs/old/tci-acm.pdf) to record instances registered with the "Provider Registrar". However, with 605bba0e46e7db9fea0b2ad7d97e67604535fb14, both provider and vTPMs are no longer supported on Keylime.
The usage of 'prov_db_filename' from the config got dropped when the DB was ported to SQLAlchemy 4d8d8cd9acc8bc929af8bef0d4fca7b8a47b8d24 and the last remaining artifact was nuked as part of the style fixes be07edb59517dfd4e335ec356b0ca531e0e294af.
Fixes #1465

remove prov_db_filename from config

---

keylime/web_util.py

In file: web_util.py, the comparison of Collection length creates a logical short circuit. I suggested that the Collection length comparison should be done without creating a logical short circuit. 
Per feedback, I removed the test expression that was creating the logical short circuit.
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.
The bug is found by running the …

Fix an inappropriate test expression to remove a logical short circuit

---

test-requirements.txt

`types-atomicwrites` is archived and deprecated (refer https://github.com/python/mypy/pull/14265 and
https://github.com/python/typeshed/pull/8925)

test-requirements: remove types-atomicwrites

---

keylime/types.py

Fix the following deprecation warning by importing a more recent type if possible, otherwise fall back to the older type.
/usr/local/lib/python3.12/site-packages/keylime/types.py:7: \
CryptographyDeprecationWarning: Use CertificateIssuerPrivateKeyTypes instead
from cryptography.hazmat.primitives.asymmetric.types import CERTIFICATE_PRIVATE_KEY_TYPES as cpke

types: Fix a deprecation warning from recent cryptography

---

keylime/requests_client.py

Tox reports the following error message:
mypy: commands[0]> mypy keylime/
keylime/requests_client.py:6: error: Library stubs not installed for "requests.packages.urllib3.poolmanager"  [import-untyped]
keylime/requests_client.py:6: note: Hint: "python3 -m pip install types-requests"
keylime/requests_client.py:6: note: (or run "mypy --install-types" to install all missing stub packages)
keylime/requests_client.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Resolve the issue by having mypy ignore the import.
Otherwise, none of the following could resolve the issue:
- Adding types-requests to requirements.txt followed by 'make check-rebuild'
- Adding 'python3 -m pip install types-requests' to tox.ini before 'mypy keylime/'

codestyle: Have mypy ignore import of PoolManager

---

keylime/cert_utils.py
keylime/revocation_notifier.py

Catch the exception when a malformed certificate file is read. Ignore it and print out a warning:
2023-11-03 12:00:51.919 - keylime.cert_utils - WARNING - \
Ignoring certificate file /var/lib/keylime/tpm_cert_store/bundle.pem \
due to error: Invalid base64-encoded string: number of data characters \
(65) cannot be 1 more than a multiple of 4
Resolves: Issue #1081

cert_utils: Ignore malformed certificate files

---

packit-ci.fmf

The test is now merged.
The test recreates the IAK and IDevID keys out of band of the agent (using tpm2_tools), and sets up a CA to create certs for the keys. The agent attempts to register with the keys (checking the keys match the internal keys in the process) and fails when the CA has not been added as trusted, then succeeds when the CA is added.
[Testing repo PR](https://github.com/RedHat-SP-Security/keylime-tests/pull/514)

Enable test functional/iak-idevid-register-with-certificates

---

keylime/ca_impl_openssl.py
test/test_ca_impl_openssl.py

Only "http://localhost/crl.pem" was used although the configuration is defining a setting for this
Signed-off-by: Karsten Ohme <karsten.ohme@ohmesoftware.de>

ca_impl_openssl: support CRL distribution point from config

---

test/run_tests.sh

The test script supports a user mode, but fails when it is used.

support for user mode in run-test.sh

---

templates/2.1/agent.j2

The value in enable_iak_idevid in the agent template should not be surrounded by double quotes as it is a boolean value and not a string.

templates/2.1: Fix enable_iak_idevid in agent template

---

docs/user_guide/configuration.rst

Changed the documentation in the userguide regarding the configuration paths to reflect the actual correct paths under /etc/keylime/, not under /var/keylime/ as the current version states.
Resolves: #1509

Correcting paths in userguide documentation

---

docs/user_guide/idevid_and_iak.rst
templates/2.1/agent.j2
templates/2.1/mapping.json

These are documentation and template mapping changes that correspond to the changes in [rust-keylime PR 689](https://github.com/keylime/rust-keylime/pull/689). The rust PR adds the auto-detect for IDevID and IAK templates and changes the default value for idevid templates in the agent.conf.
Leaving this on draft until the rust-agent pr is looked at/approved, as that is a prerequisite.

Detect template changes for IDevID - docs and template mappings

---

keylime/common/migrations.py

Remove the 'type: ignore' comment from migration.py to allow mypy to pass without errors.

codestyle: Remove a 'type: ignore' comment (mypy)

---

keylime/mba/elchecking/__main__.py
keylime/mba/elchecking/example.py
keylime/mba/elchecking/tests.py

Bringing up some newer devices found some missing parts in the example policy.
This still misses EV_EFI_PLATFORM_FIRMWARE_BLOB2 handling, but that comes in a
seperate PR.
- mba/elchecking: load imports first
- mba/e/example: Allow db entries to be also hashes
- mba/e/example: ignore EV_CPU_MICROCODE, EV_EFI_HANDOFF_TABLES2 and MokListRT
- mba/e/elchecking: add workaround for non spec compliant firmware

Various fixes for example MB policy

---

keylime/migrations/versions/160f932fde5b_increase_length_of_verifier_ip_column.py

This change is very similar to what has been already implemented on PR https://github.com/keylime/keylime/pull/505, allowing the aforementioned field to hold ipv6 addresses (plus, it allow the holding FQDN too)

Extended the length of `verifier_ip` column to String(255)

---

requirements.txt

Version 0.2.1 does not include rfc4108.

requirements: bump pyasn1-modules to 0.2.5

---

templates/2.2/agent.j2

Fix typo on template comment about the default measured boot log location.
This is related with https://github.com/keylime/rust-keylime/pull/743

templates: Fix typo on default measured boot log location

---

keylime/dsse/dsse.py
keylime/ima/ima.py
templates/2.0/mapping.json
templates/2.1/mapping.json
templates/2.2/mapping.json
templates/2.2/verifier.j2

This PR adds the require_allow_list_signature config option to the verifier config file but sets it to 'False' on default. Also, when signatures are required, raise an error if a plain runtime policy is being used that doesn't have the 'payload' key in its map (The payload key in the signed policy contains the b64 encoded actual runtime policy).
Fixes: #1314
Resolves: #1464

Add require_allow_list_signature to the verfier config file

---

scripts/download_packit_coverage.sh

Services we had been using in the past stopped working, therefore switching to a new ones.

tests: Fix coverage download by supporting new webdrives

---

keylime/tpm/tpm_main.py

The salt length for PSS should be the byte length of the digest getting signed. This has only been working when it was the same size as the signature.
For example, if the item is hashed into 32 bytes (sha256) and signed with that amount, the verification would pass as the salt would receive the correct length (256/8 = 32). However if the digest is 48 bytes, and the signature is 512 then it will fail (512/8 = 64) as a salt length of 64 is longer than 48.

PSS padding fix - salt length set according to wrong length

---

keylime/cmd/convert_config.py
setup.py
templates/2.2/mapping.json
templates/2.3/agent.j2
templates/2.3/ca.j2
templates/2.3/logging.j2
templates/2.3/mapping.json
templates/2.3/registrar.j2
templates/2.3/tenant.j2
templates/2.3/verifier.j2
test/test_convert_config.py

This contains the changes made in #1482 to the templates and mappings for the version `2.2` which was already released on version `7.9.0`
This also fixes a bug with the default usage when generating the configuration files with the `--default` option where the first value set as default for an option is kept. This changes this logic and uses the default value set for the option in the latest template version.
EDIT: Some of the previously used default values came from template version 2.0 and needed adjustment using the `adjust.py` script. These were the default values used before the change in the `--default` option.
To not require an `adjust.py` script to be added to the template version 2.3, the default values were replaced to the adjusted format, keeping the same default values …

templates: Add version 2.3

---

templates/2.3/agent.j2
templates/2.3/mapping.json

Fixes #1549 
Adds config options to the templates for the IDevID and IAK handles if the keys have been persisted, and their passwords if they are password protected.
These are the template changes for the Rust agent changes here [PR 785](https://github.com/keylime/rust-keylime/pull/785).

add config options for the persisted idevid and iak handles, passwords

---

docs/rest_apis.rst
docs/user_guide/runtime_ima.rst
docs/user_guide/user_selected_pcr_monitoring.rst
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/db/verifier_db.py
keylime/tenant.py

This now allows an agent to be added without using the payload feature.
Note that then also no U/V key is sent to the agent on successful attestation.

verifier, tenant: make payload for agent completely optional

---

keylime/ca_impl_openssl.py

Follow RFC 5280 requirements when generating certificates, especially regarding required extensions and setting criticality.
Resolves #1556

Fix certificate generation to follow RFC 5280

---

keylime/tenant.py

In the case of TLSV1_ALERT_UNKNOWN_CA it is likely that the agent does not have the correct CA configured under trusted_client_ca.
Fixes #1553

tenant: add friendlier error message if mTLS CA is wrongly configured

---

docs/user_guide/use_measured_boot.rst
keylime/api_version.py
keylime/cli/policies.py
keylime/cloud_verifier_common.py
keylime/cloud_verifier_tornado.py
keylime/mba/mba.py
keylime/tenant.py
keylime/tpm/tpm_main.py
test/test_api_version.py

Similar to named runtime policies, it allows the operator to add, show, delete, update and use measured boot policies with names. It also allows to list the measured boot policies.

mba: Support named measured boot policies

---

keylime/revocation_notifier.py

This is a workaround for the regression added by `python-requests` version `2.32.3`, reported upstream as https://github.com/psf/requests/issues/6730
Resolves: #1569

revocation_notifier: Explicitly add CA certificate bundle

---

.github/workflows/codeql-analysis.yml
.github/workflows/container.yml
.github/workflows/greetings.yml
.github/workflows/pypi-release.yml
.github/workflows/submit-HEAD-coverage.yaml
.github/workflows/submit-PR-coverage.yaml
.github/workflows/test.yml
docker/ci/Dockerfile
docker/release/base/Dockerfile.in

Currently the Keylime's dockerfiles and action workflows are using tags over digests.
Tags are risky. Pinning to digests for Actions and Dockerfiles ensures you are using a specific, verified version of a dependency, otherwise its possible someone could replace the code for an existing tag, which could lead to certain attacks being triggered by the workflow runs.
Check out [GitHubs documentation](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) and [the following](https://candrews.integralblue.com/2023/09/always-use-docker-image-digests/) for Dockerfiles
I will make two follow up PR's. One to introduce Dependabot to keep the actions updated. The 2nd will be for Frizbee-action, an OSS tool that will automatically flip tags …

Change Docker and Action Tags to Digests

---

.github/frizbee.yml

This adds the Frizbee action that will automatically flip tags to digests on any Dockerfiles, workflows.
Note this action requires a token scoped with only (limited scopes), see
[here](https://github.com/stacklok/frizbee-action?tab=readme-ov-file#create-a-token) for details

Add Frizbee Action

---

docker/ci/Dockerfile
docker/release/base/Dockerfile.in
docker/release/build_locally.sh

The Fedora 37 is no longer supported. This updates the images to be based on Fedora 40.
Also add some small changes to fix the `build_locally.sh` script by disabling SELinux relabeling during the build.
EDIT: Added test dependencies needed for #1568

docker: Update images to use Fedora 40

---

docker/release/base/Dockerfile.in

The docker/build-push-action tries to download the base image from the docker registry instead of quay.io when the registry is omitted in the Dockerfile.
This leads the build to fail as the requested pinned image version is not available in the docker registry.
Add quay.io registry explicitly.
(Hopefully)
Resolves #1579

docker/release/base: Explicitly add the registry for base

---

.packit.yaml

Due to the various braking changes made recently in Rawhide we have decided to disable Rawhide in CI. We will continue testing on Rawhide on keylime-tests side so we can spot issues early.

ci: disable Packit testing for Rawhide

---

.github/workflows/base-image.yml
.github/workflows/container.yml
.github/workflows/update-base-image.yml
docker/release/base/Dockerfile.in
docker/release/build_locally.sh
docker/release/generate-files.sh
docker/release/registrar/Dockerfile.in
docker/release/tenant/Dockerfile.in
docker/release/verifier/Dockerfile.in

Add a workflow to automatically create pull requests updating the Fedora image used to build the base image.
The workflow should run monthly and can also be triggered manually on demand.
Build the base image separately when the Dockerfile template is updated.
Modify the other images build to use the master base image from the registry.
Fixes #1579

docker: Automate base image updates

---

keylime/cert_utils.py
keylime/cmd/keylime_policy.py
keylime/common/algorithms.py
keylime/ima/ima.py
keylime/models/registrar/registrar_agent.py
keylime/policy/create_runtime_policy.py
keylime/policy/initrd.py
keylime/policy/rpm_repo.py
keylime/policy/utils.py
setup.cfg
test-requirements.txt
test/data/create-runtime-policy/setup-initrd-tests
test/data/create-runtime-policy/setup-rpm-tests
test/run_tests.sh
test/test-requirements.txt
test/test_algorithms.py
test/test_cert_utils.py
test/test_create_runtime_policy.py
test/test_rpm_repo.py

Initial steps of enhancement #110, which is to provide a single
tool that provides the functionality of the existing tools we
have.
In this commit, we add the `keylime_policy` tool, that is currently
able to handle the creation of runtime policies.
To see the available options:
`keylime_policy --help`
To see the options available related to creating runtime policies:
`keylime_policy create runtime --help`
Some of the options available include e.g. using an IMA measurement
list, legacy allowlist/excludelist files, local/remote RPM repositories,
specifying a rootfs filesystem, initrds, a base policy, etc.

Enhancement 110: add tool to handle keylime policies 

---

.github/workflows/base-image.yml

The CI uses the 'latest' tag for the CI image

workflows/base-image: Add latest tag to the CI image build

---

keylime/mba/mba.py
keylime/tenant.py

Allowing the skipping of custom policies, known only to the verifier, will enable the tenant to call MBA without consulting the verifier config file.
Resolves: #1541

mba: Add a skip custom policies option when loading mba.

---

.github/workflows/test.yml
keylime/requests_client.py
keylime/revocation_notifier.py
packit-ci.fmf
tox.ini

Previously, the revocation notifier would use only the system installed CA certificates, ignoring those added via `trusted_ca_certificates` configuration. Also, if the webhook didn't offer a certificate, the revocation notifier would ignore the missing certificate and continue the communication in plaintext, even when TLS is enabled via configuration. This can be dangerous if sensitive data is sent to the webhook.
This change makes the revocation notification to use the configured TLS options.

revocation_notifier: Take into account CA certificates added via configuration

---

docker/release/base/Dockerfile.in
docker/release/registrar/Dockerfile.in
docker/release/tenant/Dockerfile.in
docker/release/verifier/Dockerfile.in

Previously, the image build would not install Keylime, but simply reuse the version installed during the base image build.
This fixes the issue, installing the latest Keylime version during image build.
Since the images were using outdated Keylime, the tests in https://github.com/RedHat-SP-Security/keylime-tests/pull/602 were failing.

docker: Install latest Keylime during image build

---

keylime/ca_impl_openssl.py
keylime/web/base/controller.py

Ignoring pyright reportArgumentType and reportInvalidTypeForm errors until a better solution can be found.

Lint: ignore reportArgumentType and reportInvalidTypeForm errors

---

keylime/policy/create_runtime_policy.py

Set the algorithm for the template-hash (`log_hash_alg`) to `sha1`; the kernel currently hardcodes it to sha1. Now, the specified algorithm is only used for hashing the ramdisk and rootfs. If one is not provided, it defaults to sha256.
This change fixes #1609 because the policy schema prevents the use of sm3 for `log_hash_alg`. It also fixes #1623 since it removes the lookup for the boot_aggregate algorithm by setting `log_hash_alg` to sha1 instead.

keylime_policy: setting `log_hash_alg` to `sha1` (template-hash algo)

---

docs/user_guide/runtime_ima.rst

Previously, the documented Runtime Policy JSON schema did not correspond to the actual implementation.
This change aligns the documented JSON Schema to the actual implementation.
Fixes #1564

docs: Fix Runtime Policy JSON schema to reflect the reality

---

pylintrc

The CI started failing due to the `too-many-positional-arguments` check from `pylint`.
This makes this check to be ignored.

pylintrc: Ignore too-many-positional-arguments check

---

keylime/policy/create_runtime_policy.py

The messages that are not relevant to the user should be logged using DEBUG level instead of INFO.
Fixes #1613

create_runtime_policy: Fix log level for debug messages

---

keylime/mba/elchecking/example.py
scripts/create_mb_refstate

- elchecking: add handling for EV_EFI_PLATFORM_FIRMWARE_BLOB2
- elchecking/example: workaround empty PK, KEK, db and dbx
Fixes the issue observed in https://github.com/keylime/keylime/issues/1617

Improvments to Measured Boot

---

keylime/cmd/keylime_policy.py
keylime/policy/create_runtime_policy.py
setup.cfg
test/test_create_runtime_policy.py

This PR has a few changes related to consistency within the policy tool, and has the following changes:
1) Let's keep option names consistent, i.e. use `--allowlist`/`--excludelist`, instead of `--allowlist`/`--exclude-list`
2) drop some confusing "short" shortcuts, like `-i` and `-A`, and keep long versions instead, for those
3) drop superfluous option `--use-ima-measurement-list`, as we already have `--ima-measurement-list`; the behavior is the following: if `--ima-measurement-list` is used without any argument, it will use the default IMA measurement list file, `/sys/kernel/security/ima/ascii_runtime_measurements`; if a parameter is given as argument, that parameter indicates the file to read as a source for the IMA measurement list
4) rename the tool itself from `keylime_policy` to …

keylime-policy: use consistent names for create runtime

---

demo/agent_monitor/tenant_agent_monitor.py
keylime/cmd/attest.py
keylime/cmd/keylime_policy.py
keylime/dsse/dsse.py
keylime/dsse/ecdsa.py
keylime/dsse/x509.py
keylime/policy/create_runtime_policy.py
keylime/policy/initrd.py
keylime/policy/utils.py
setup.py
test/test_api_version.py
test/test_ca_impl_openssl.py
test/test_ca_util.py
test/test_cert_utils.py
test/test_create_runtime_policy.py
test/test_crypto.py
test/test_ima_ast.py
test/test_ima_verification.py
test/test_json.py
test/test_policy_conversion.py
test/test_registrar_db.py
test/test_retry_algo.py
test/test_rpm_repo.py
test/test_signing.py
test/test_verifier_db.py

As clarified in #830, license headers should be removed from source code to ease homogeneity among them

Drop pending SPDX-License-Identifier headers

---

docker/release/base/Dockerfile.in

Adds `psycopg2` module to support PostgreSQL by adding it to the base docker image build as `python3-psycopg2`.
Also includes `nc` to support healthchecks in docker.
Fixes #1672

PostgreSQL support for docker using psycopg2

---

docs/installation.rst

Keylime Rust agent does not understand `TPM2TOOLS_` prefixed configuration. For example, `TPM2TOOLS_TCTI` is ignored when setting up swtpm.
`.ci/test_wrapper.sh` is already exporting both formats, but installation documentation is not mentioning the shorter format at all.

docs: update TCTI environment variable usage

---

.github/workflows/submit-HEAD-coverage.yaml
packit-ci.fmf
scripts/download_packit_coverage.sh

Replace the Fedora 39 usage to generate code coverage with Fedora 41.
This is necessary because Fedora 39 is now EOL and the tests are no longer triggered for it.

tests: Use Fedora 41 to generate code coverage

---

keylime/tenant.py

The change to a f-string format for the error raised when the deletion of an agent failed was not done correctly, resulting in the number of tries before giving up to not be printed.
A message similar to the following would be logged instead:
```
2024-12-02 12:54:11.424 - keylime.tenant - ERROR - ('Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1:9002)',) was not deleted from Verifier default (127.0.0.1:8881) after %d tries
```

tenant: Correctly log number of tries when deleting

---

keylime/cmd/keylime_policy.py
keylime/policy/create_runtime_policy.py
keylime/policy/sign_runtime_policy.py

- fix help for "keylime-policy sign" verb
- check for valid cert file when using x509 backend (sign)
- use Certificate() from models.base to validate certs
- exit with status 1 when the commands failed
-  improve error handling when provided a bad key (sign)

Misc fixes for keylime-policy

---

docker/ci/Dockerfile
docker/release/base/Dockerfile.in

Fedora 41 moved to `dnf5` which does not provide `groupinstall` anymore.
Also add `openssl` and `tpm2-openssl` to the list of packages to install.
Finally, copy the built `cargo-tarpaulin` to be available for all users and not only `root`

docker/ci: Fix CI image build for dnf5

---

docker/ci/Dockerfile

The `xxd` tool is used to generate IAK and IDevID certificates during tests

docker/ci: Add xxd to the CI image

---

packit-ci.fmf

Fix the typo replacing `keylime_policy-commands` with `keylime-policy-commands` on packit configuration.

packit: Fix typo to run keylime-policy-commands test

---

test-requirements.txt
test/data/create-runtime-policy/setup-rpm-tests
test/test_rpm_repo.py

- fix rpm tests to account for older createrepo_c versions
- remove typed-ast from test-requirements.txt

Misc test fixes

---

keylime/cmd/keylime_policy.py

Enable autocompletion using argcomplete by adding the comment with the string `PYTHON_ARGCOMPLETE_OK` on the first 1024 bytes of the script.

Enable autocompletion using argcomplete

---

templates/2.4/agent.j2
templates/2.4/mapping.json

The introduced configuraton option allows the user to select a subset of the supported API versions to enable.
This is part of the implementation of the enhancement proposal 114: https://github.com/keylime/enhancements/pull/115

templates: Add the new agent.conf option 'api_versions'

---

docs/user_guide.rst
docs/user_guide/keylime_policy.rst
docs/user_guide/runtime_ima.rst

In this commit we add some initial documentation for the keylime-policy tool.

docs: add documentation for keylime-policy

---

scripts/create_runtime_policy.sh

Let's use the full path of the exclude list when passing it to convert_runtime_policy.py, so that the script will be able to find and process it as expected, otherwise it will fail with the following trace:
./create_runtime_policy.sh -a sha256sum -e excludelist.txt -o runtime_policy.json
[...]
File "/root/keylime/./keylime/cmd/convert_runtime_policy.py", line 229, in <module>
main()
~~~~^^
File "/root/keylime/./keylime/cmd/convert_runtime_policy.py", line 214, in main
policy_out = update_runtime_policy(
policy, excludelist_path=args.excludelist, verification_keys=args.verification_keys
)
File "/root/keylime/./keylime/cmd/convert_runtime_policy.py", line 144, in update_runtime_policy
with open(excludelist_path, "r", encoding="utf8") as f: …

scripts/create_runtime_policy.sh: fix path for the exclude list

---

test/test_mba_parsing.py

This test needs the verifier configuration file available, and on systems that do not have keylime installed (hence, no config file), it would fail.
This commit changes the test so that it creates a verifier conf file in a temporary directory with default values, so that it can use it.

tests: change test_mba_parsing to not need keylime installed

---

demo/agent_monitor/tenant_agent_monitor.py
keylime/cloud_verifier_tornado.py
keylime/db/keylime_db.py
keylime/models/base/db.py
keylime/tpm/tpm_main.py

log.exception already contains exception info, there is no need to log twice with separate logging levels.

Remove excessive logging on exception

---

keylime/cmd/registrar.py

Log the current and supported versions during startup
Fixes: #1727

registrar: Log API versions during startup

---

packit-ci.fmf

The test tries all API versions supported by the agent against the latest server components.

packit: Add compatibility/api_version_compatibility test

---

.github/PULL_REQUEST_TEMPLATE.md

Adds standardized PR template to improve contribution process with:
- Explicit documentation update requirements
- Conventional commits guidance
- Structured change description format
- [√] Updated markdown docs (file path: .github/PULL_REQUEST_TEMPLATE.md)
- [√] Needs ReadTheDocs updates (repository documentation guidelines)
1. Check template renders correctly in GitHub PR interface
2. Verify template contains all required documentation checks
**Resolves:** #1035  PR Template

docs: add GitHub PR template with documentation reminders

---

keylime/db/verifier_db.py
keylime/migrations/versions/57b24ee21dfa_extend_meta_data_field.py

Added a database migration to allow the meta_data field in the verifierdb to contain more data. This field is used to store a json that Keylime uses to store cert details in some cases but can also be added to by the user to contain more metadata related to the agent (eg. by using the meta-data field in the API), so it should be extended to contain that data.
Generated a new db migration (`57b24ee21dfa_extend_meta_data_field`) that has an upgrade and downgrade strategy to change from the existing length 200 String type to the new Text type and vice-versa. This change is also reflected in the `VerifierMain` model in `verifier_db.py`.
The documentation does not mention a length limit so the docs are actually more accurate after this change.
1. Describe test environment
2. Step-by-step …

Extend meta_data field in verifierdb

---

keylime/policy/create_runtime_policy.py

*(If you use an issue tracker, please put references to them)*  
**Resolves:** #1764 
Python <3.12 does not support the "in" operator on Enums So we need to explicitly enumerate the potential values of an enum before using "in".
*(Optional: follow-up tasks, special considerations)*

Fix create_runtime_policy in python < 3.12

---

keylime/cmd/create_policy.py
keylime/policy/rpm_repo.py
keylime/revocation_notifier.py
templates/2.0/adjust.py
test/data/create-runtime-policy/setup-rpm-tests
test/test_create_mb_policy.py
test/test_mba_parsing.py

- Additional test fixes
*(If you use an issue tracker, please put references to them)*  
N/A
- templates: duplicate str_to_version() in the adjust script
- tests: skip measured-boot related tests for s390x and ppc64le
- tests: fix rpm repo tests from create-runtime-policy
- Fix (unrelated) mypy issues reported
Explain the problem being solved and why this change is necessary. Focus on:
- The change in the templates is necessary so that we can run the upgrade script without needing the keylime modules installed
- Additional test fixes, disabling the measured boot-related tests for s390x and ppc64le architectures and improving error handling for the create-runtime-policy test
*(Check all that apply)*
1. Describe test environment
2. Step-by-step validation procedure …

templates: duplicate str_to_version() in the adjust script

---

keylime/tenant.py

Add `--push-model` option to remove agent access
N/A
We introduce a new option, `--push-model`, disabled by default. If enabled, communication to agent from tenant will be disabled.
New option, `--push-model`, to avoid communication to agent from tenant.
Explain the problem being solved and why this change is necessary. Focus on:
- Change required to reuse `keylime_tenant` when using Push Mode
No documentation needs to be updated for tenant parameters
1. Describe test environment
Start registrar, verifier and agent (this last one in Push Mode)
2. Step-by-step validation procedure
Send registration to verifier through tenant:
```bash
keylime_tenant -c add --cert default -u <UUID> -t <AGENT_IP> -v <VERIFIER_IP>
```
3. Expected vs actual results
Actual:
A connection exception to the agent is …

tenant: Add --push-model option to avoid requests to agents

---

keylime/cloud_verifier_tornado.py
keylime/revocation_notifier.py

Fix webhook worker connection tracebacks during verifier shutdown by implementing graceful worker management and prioritizing critical revocation notification delivery.
**Problem:**
Stopping the verifier generated connection error tracebacks from webhook workers attempting to send revocation notifications during shutdown:
```
Exception in thread Thread-1:
File "/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
...
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
**Root Cause:**
Webhook worker threads continued attempting HTTP requests while the service was shutting down, causing connections to be aborted …

verifier: Gracefully shutdown webhook workers during signal handling

---

keylime/mba/elchecking/example.py
keylime/policy/create_mb_policy.py
scripts/create_mb_refstate
test/test_create_mb_policy.py

mb: support vendor_db as logged by newer shim versions #1791 
https://issues.redhat.com/browse/RHEL-80455
- Updated example policy to properly handle different event structures
for vendor_db validation:
- KeySubsetMulti for EV_EFI_VARIABLE_DRIVER_CONFIG (has SignatureType field)
- SignatureSetMember for EV_EFI_VARIABLE_AUTHORITY (direct signature format)
- Added method to extract vendor_db from EV_EFI_VARIABLE_AUTHORITY events
in reference state generation (keylime-policy create measured-boot and
the legacy create_mb_refstate script)
- Made vendor_db optional for backward compatibility
See: https://github.com/rhboot/shim/pull/728
Support vendor_db as logged by newer shim versions
This fixes attestation failures when vendor_db variables are present but
missing …

mb: support vendor_db as logged by newer shim versions

---

packit-ci.fmf

Enables test `/functional/add-agent-with-malformed-ek-cert` in Packit CI.

CI: Enable test add-agent-with-malformed-ek-cert
