keylime/keylime

- installer.sh
Was printing out the m2crypto version
> Fix typo in cryptodomex req check

- test/run_tests.sh
- test/test-requirements.txt
Start using pip standard for package versioning control as per [0]
The current versions in `test-requirements.yml` are the latest
available releases on pypi.
Closes #20
[0] https://pip.pypa.io/en/latest/user_guide/#requirements-files
> Implements pip requirements standard for test

- .travis.yml
> Add travis local directory is mount point into container.

- README.md
> Fixes incorrect folder path to doc

- test/run_tests.sh
- test/test_restful.py
This change introduces a slight change to the package manager
selection and in turn installs python-dbus
Further changes are made to `test_restful.py` whereby if the
system is running within systemd mode with an active dbus, restart
`tpm2-abrmd.service`. If not, do not try to restart the tpm2-abrmnd.
The logic being, a non systemd based service will be running a
tpm1.2 system.
The service restart is required as when using mssim, the resource
manager cannot reconnect.
This allows continued use of one set of test scripts for both
TPM versions.
> Allows tpm2-abrmd restart for test run

- README.md
[skip travis]
PartialFix of #53
> Added basic process for reporting security bugs

- RELEASE.md
A page describing the semver process
Resolves #54
> Release details page

- .gitignore
Add the following left after tests:
swtpm2_scripts/NVChip
test/.auditing-0
test/NVChip
test/testdata.sqlite
Fixes #46
> Add test objects to gitignore

- .ci/run_local.sh
Can be useful a local test environment for unstaged code testing
> Script to replicate CI build

- README.md
Quick mention of ansible and docker as ways for developers to quickly get a keylime instance(s) running.
Resolves #69
[skip travis]
> Mention Ansible and Docker install methods

- README.md
Quick summary text on when and where we meet and a reference to the
meetings repo used.
resolves #73
> Adds details on Keylime's community meetings

- README.md
- installer.sh
- keylime/common.py
- setup.py
first step towards fixing pyyaml dependency stuff.  we'll stick with the distro versions for now.
#81  and eventually will relate to #80
> handle pyyaml just like other dependencies

- keylime/tpm1.py
- keylime/tpm2.py
- keylime/tpm_abstract.py
adding a warning to cloud node if using a software tpm emulator #78
> Warn emulator

- keylime/ima_emulator_adapter.py
Patch by @jetwhiz to address issue in Fedora cloud image
where the ascii_runtime_measurements would not parse correctly.
Fixes #62
> Addresses cloud image seek issue failure

- test/run_tests.sh
> Update tests to run with require_ek_cert to False

- README.md
This change explains the role of keylimes main components and more on what the project plans to achieve, it also explains the current status of the rust-keylime agent code base.
> Text on rust-keylime and more body on what the project achieves.

- scripts/script_vtpm_register.sh
> script_vtpm_register.py wrong uses wrong extension

- installer.sh
change from Github org from mit-ll to keylime
> update the Keylime git repos to official ones

- README.md
> Updated 'Development only' status of Ansible section in README.md

- keylime/ca_impl_cfssl.py
> warn if cfssl binary is not found

- README.md
Outline dist support, plus a few minor fixes / changes to the installer text.
> Linux Distribution Installer Support Matrix.

- README.md
- installer.sh
Lets call it as it is, to make it easier for new users to understand.
Resolves: #182
> Make intention of Emulator arg more direct.

- README.md
> Added First Timers Support in README.md

- keylime/tpm2.py
- keylime/tpm_abstract.py
A sketch up WIP patch on how we could triage different tpm2-tools versions
Resolves: #187
> [WIP] new tools selection code

- keylime/tpm2.py
In tools commit hash:
https://github.com/tpm2-software/tpm2-tools/commit/45c4883dcdadc754b60832a4    2a5e9e82f847bc7d
`f` has been changed to `o`
`tpm2_pcrlist` is now `tpm2_pcrread`
Resolves: #204, #208
> Updates needed for 4.0.x tpm2-tools changes

- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/revocation_notifier.py
- keylime/tenant.py
- keylime/tornado_requests.py
`callback` has been depreciated from tornado 6.0
This code changes the `invoke_get_quote` from a callback to a
while loop
Resolves: #196
> Port verifer to tornado release 6.0.x

- keylime/tenant.py
cvstatus only supported 'listing=False' mode
> Fix bug in tenant's "list" functionality

- keylime.conf
- keylime/cloud_agent.py
@lukehinds Please review these changes.
> Cloudagent ip

- keylime/registrar_client.py
Added exception handling in doRegisterAgent
Currently, when the registrar is not running and we try to run agent
it exits without any graceful error message. With this change, an error
message is reported to user when the registrar is not running.
Resolves: #216
> Added exception handling in doRegisterAgent

- keylime/cloud_verifier_common.py
This would be a useful value to transmit, this commit adds it
Resolves: #238
> Add agent_id to revocation message

- keylime.conf
- keylime/ca_impl_cfssl.py
- keylime/cloud_agent.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/provider_platform_init.py
- keylime/provider_registrar.py
- keylime/provider_vtpm_add.py
- keylime/registrar.py
- keylime/registrar_common.py
- keylime/revocation_notifier.py
- keylime/tenant.py
- keylime/tenant_webapp.py
- test/test_restful.py
Currently, the layout of the configuration file is clumsy. This
change try to group logical items together, so that it make sense.
Resolves: #247
> Refactored IP address and Port in the configration file

- installer.sh
I hope this is what was needed for that issue. Sorry not sure how to link the PR to the issue. #256
> installer.sh package / pip changes

- keylime/ca_util.py
> Add trail slash only if needed

- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
Also fix a typo that was generating an error if the revocation_key
was not empty.
> Refactor notify error function

- .travis.yml
- keylime/ca_util.py
Reverts keylime/keylime#287
It should not have been merged, still as Work In Progress
> Revert "[WIP] Correct duplicate travis phase"

- keylime/tenant.py
Tried to fix this issue https://github.com/keylime/keylime/issues/304
Hope this is what you are looking for.
> Incorrect text of verifier, should be agent 

- keylime/cmd_exec.py
wait() can hang if there is too much to read (buffer fills before command
exits). communicate() will do all the reading for us.
Fixes issue #330
> Switch popen.wait() for popen.communicate()

- setup.py
PBR is causing constant headaches in packaging and adds no value
considering the amount of times its causing failures.
> Remove PBR

- setup.py
> Revert "Remove PBR"

- setup.py
> Fix a packaging issue

- README.md
Allow users to know how to request a feature change, by pointing
them towards our enhancements repository
> Add section on enhancements

- keylime/ima.py
- keylime/tpm/tpm_abstract.py
@mpeters @galmasi @maugustosilva
Please review and comment.
> first tentative fix #341

- keylime/db/keylime_db.py
- keylime/tpm/tpm1.py
- keylime/tpm/tpm2.py
- keylime/tpm/tpm_abstract.py
- keylime/tpm/tpm_obj.py
> Change missed license port files

- ROADMAP.md
While we work on an enhancements process, lets have our roadmap
here.
> Project Roadmap

- keylime/cloud_verifier_tornado.py
> Force max_upload_size to be an int

- keylime/cloud_verifier_tornado.py
- test/test_restful.py
Fixing 2 tests of broken tests at once to get CI working again:
* Fix separate reg cv tests
* Fix botched fix of max_upload_size int conversion
> Fix broken tests

- doc/freebsd.md
A while back i wrote up some docs on getting keylime running on freebsd.  I thought it would be good to have these docs in the docs folder in case anyone ever wants to pick this up again.
related to https://github.com/keylime/keylime/issues/254
> park the howto on freebsd in docs

- keylime/cloud_verifier_common.py
- keylime/cmd/ima_emulator_adapter.py
- keylime/tenant.py
- keylime/tpm/tpm1.py
- keylime/tpm/tpm2.py
- keylime/tpm/tpm_abstract.py
- keylime/utils/algorithms.py
This should be something in the common but there is already
a common file thus renamed to utils. Other common stuff can
be put to the utils as needed.
> Extract algorithm consts and helper into utilities

- keylime/ca_util.py
- keylime/cmd/provider_platform_init.py
- keylime/cmd/provider_vtpm_add.py
- keylime/common.py
- keylime/keylime_agent.py
- keylime/tenant.py
The support to develop in eclipse is no longer supported
and removed.
Resolves #383
> Remove the DEVELOP_IN_ECLIPSE support

- keylime/keylime_logging.py
Change logger format to use asctime, created is epoch time
which is not user friendly.
> Improve logging time

- keylime/tenant.py
As well as some minor code tuning.
> Remove unreachable code

- keylime/ca_impl_cfssl.py
- keylime/ca_impl_openssl.py
- keylime/ca_util.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/cmd_exec.py
- keylime/common.py
- keylime/crypto.py
- keylime/cryptodome.py
- keylime/ima.py
- keylime/keylime_agent.py
- keylime/keylime_logging.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/secure_mount.py
- keylime/tenant.py
- keylime/tenant_webapp.py
- keylime/vtpm_manager.py
- scripts/check_codestyle.sh
> codestyle: Address some code style issues in keylime directory

- keylime.conf
> Fixes failing wildcard for ZMQ

- keylime/tpm/tpm1.py
- keylime/tpm/tpm2.py
- keylime/tpm/tpm_abstract.py
- keylime/tpm/tpm_obj.py
- scripts/check_codestyle.sh
> codestyle: Address some code style issues in keylime/tpm directory

- keylime/benchmark/utility_average_logged_deltas.py
- keylime/benchmark/utility_plot_time_series.py
- keylime/benchmark/utility_smoothed_ts.py
- keylime/cmd/ima_emulator_adapter.py
- keylime/cmd/migrations_apply.py
- keylime/db/keylime_db.py
- keylime/migrations/env.py
- scripts/check_codestyle.sh
- test/oldtest.py
- test/test_restful.py
> codestyle: Address some code style issues in keylime sub directories

- keylime/ima.py
This PR does some cleanups on the process_measurement_list function in ima.py.
> Some cleanups on ima process_measurement_list

- keylime/ca_impl_cfssl.py
- keylime/ca_util.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/common.py
- keylime/keylime_agent.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/revocation_notifier.py
- keylime/serve_uuid.py
- keylime/tenant.py
- keylime/tenant_webapp.py
- keylime/vtpm_manager.py
requirements should be guaranteed by packaging, not code,
unless we also handle alternatives.
> Stop checking simplejson in code

- keylime/db/registrar_db.py
- keylime/db/verifier_db.py
- keylime/revocation_actions/print_metadata.py
- keylime/tpm/tpm2.py
- keylime/tpm/tpm_abstract.py
Somewhat missed in last patch, now it's removed.
> Remove simplejson checking again

- keylime/cloud_verifier_common.py
Capture ssl exception for EE_KEY_TOO_SMALL and provide hint
about how to resolve the issue.
Resolves: #395
> Improve ee_key_too_small handling

- .github/workflows/keylime-bot.yml
It seems LABEL is not a recognized argument.
> Github workflow bot fix

- MAINTAINERS
I would like to propose that Kaifeng Wang be promoted to maintainer.
Kaifeng has contributed some significant PR's to the project and
refactored large amounts of the code base to make the project layout
better organised. Kaifeng also helps out reviewing others code.
Any current MAINTAINERS are welcome to +1/-1. If a positive ratio
stands in one week from now (10/12/202) I will merge this PR.
> Promote Kaifeng Wang to MAINTAINER

- keylime.conf
This option was introduced but not actually used, should be a
left over of renames in the previous patch.
> Remove registrar_require_cert

- .github/workflows/test.yml
The workflow doesn't do anything just yet, but will be populated in a later PR.
> Add "test" workflow

- keylime/cmd/provider_platform_init.py
- keylime/cmd/provider_registrar.py
- keylime/cmd/provider_vtpm_add.py
- keylime/cmd/registrar.py
- keylime/cmd/verifier.py
- keylime/revocation_actions/print_metadata.py
- keylime/tpm/tpm_abstract.py
Clean up unnecessary config.get_config()
> More config cleanup

- .ci/test_wrapper.sh
This reverts commit ec42424f2244c963ec1fbea441ebe3c242593369.
> Revert "Remove KEYLIME_HOME in test_wrapper.sh (#445)"

- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/common/exception.py
- keylime/common/states.py
- keylime/tenant.py
- keylime/tenant_webapp.py
The change moves agent states from verifier to a common
module "states", it provides state definition and helpers.
> Simplify states declaration and reference

- keylime/tpm/tpm1.py
- keylime/tpm/tpm2.py
> Converting the execution of tpm tools to shell=False

- keylime/config.py
Delete redundant code in  config.py
> Resolve the issue: Some more dev env stubs to clean up

- auto-ipsec/libreswan/src/local_action_update_crl.py
- auto-ipsec/racoon/src/local_action_update_crl.py
- keylime/ca_util.py
- keylime/keylime_agent.py
- keylime/registrar_client.py
- keylime/revocation_actions/update_crl.py
- keylime/tenant.py
- keylime/tenant_webapp.py
- keylime/tpm/tpm1.py
- keylime/tpm/tpm2.py
- keylime/tpm/tpm_abstract.py
- scripts/check_codestyle.sh
This PR fixes another set of issues detected by pylint.
> Fix another set of issues detected by pylint

- .gitignore
- keylime/benchmark/utility_plot_time_series.py
- keylime/ca_impl_cfssl.py
- keylime/ca_util.py
- keylime/cmd/migrations_apply.py
- keylime/config.py
- keylime/migrations/versions/8a44a4364f5a_initial_database_migration.py
- keylime/tpm/tpm1.py
- scripts/check_codestyle.sh
- test/test_ca_impl_openssl.py
- test/test_registrar_db.py
- test/test_restful.py
- test/test_verifier_db.py
This PR addresses issues related to C0411 and extends the .gitignore with temporary editor files that and with '~'.
> Address issues related to C0411

- keylime/tenant.py
- test/test_restful.py
Create verifier_base_url on demand.
Resolves: #447
> Fix the issue that tenant can't override verifier address from comman line

- MAINTAINERS
This PR is for me to step down as PTL of the project and let
someone else have a chance to run as PTL for a term.
I will still 100% be active on the project.
I would also like to make a proposal of @mpeters taking over from
me. Michael has by all accounts been driving the project for a
while now, making lots of reviews and working to design and deliver
some key features.
The process is outlined here:
https://github.com/keylime/keylime/blob/master/GOVERNANCE.md#changes-in-project-lead
Typically the PR should be opened no earlier then 6 weeks before
the end of term, however I think we can use a caveat that I have
been in the role for well over a year now.
At the same time, anyone else is welcome to raise a PR with a
nomination of their own.
I will leave this PR open for 2 weeks (unless …
> End of PTL term for @lhinds and propose @mpeters

- keylime/cloud_verifier_common.py
- keylime/keylime_logging.py
- keylime/registrar_client.py
- keylime/revocation_notifier.py
- keylime/tenant.py
- keylime/tenant_webapp.py
A few small changes along the way to try and improve the language of (mostly) TLS warnings thrown by Keylime.
> Improve warning language

- keylime/tpm/tpm1.py
This change converts shell=False for tpm1 module.
Resolves: #131
> Convert shell=False for tpm1 tools

- keylime/registrar_common.py
> reraise on db exceptions in the registrar service

- .github/workflows/semantic-release.yml
- .releaserc.yml
This should be a starting point for an automated release process. Uses https://github.com/marketplace/actions/action-for-semantic-release.
> Implement a basic semantic release configuration

- .travis.yml
- keylime/registrar_common.py
Move pylint check to a job so it doesn't block
functional tests.
> Move lint check to a job

- keylime.conf
- keylime/cloud_verifier_common.py
- keylime/keylime_agent.py
- keylime/tenant.py
Adds service addresses that was reading from section of other service,
so that each service reads his own section to get the full picture.
Default value is populated as dev env.
Relates-to: #441
> Fill in service addresses for each section

- keylime/registrar_client.py
- keylime/tenant.py
Helpful command to list activated agents from registrar.
Would be more useful if ip address is returned as well, but not
available from the db yet.
Signed-off-by: Kaifeng Wang <kaifeng.w@gmail.com>
> List agents from registrar with tenant cli

- requirements.txt
This change relates to issue #521
Signed-off-by: Luke Hinds lhinds@redhat.com
> Add comments that changes first require an enhancement

- test/test_restful.py
retry_interval should be used instead of max_retries.
> Fix wrong option used in the restful test

- scripts/create_allowlist.sh
sha1sum was harcoded in scripts/create_allowlist.sh initramfs measurements
> Use $ALGO in initramfs measurements

- scripts/create_allowlist.sh
Fix #546 
Signed-off-by: Nicolas Oliver <nicolasoliver03@gmail.com>
> Write boot_aggregate in allowlist

- README.md
> Remove TPM1.2 specifics from README

- keylime/config.py
- keylime/elchecking/__init__.py
- keylime/elchecking/__main__.py
- keylime/elchecking/policies.py
- keylime/elchecking/tests.py
- keylime/tpm/tpm_abstract.py
- keylime/tpm/tpm_main.py
- keylime/tpm_bootlog_enrich.py
On this PR, we finally introduce the concept of "policy engine" in its complete form. Please refer to the item 3 of #491 for the details.
Signed-off-by: Mike Spreitzer <mspreitz@us.ibm.com>
> Fourth and final PR to address #491

- requirements.txt
> Update python cryptography lib to v3.3.2

- keylime.conf
- keylime/static/js/webapp.js
- keylime/tenant_webapp.py
This PR is an implementation for #599
> Add support for keylime_webapp service to read intervals from keylime.conf

- keylime/cloud_verifier_tornado.py
- keylime/db/verifier_db.py
- keylime/migrations/versions/eb869a77abd1_create_allowlist_table.py
- keylime/tenant.py
- test/test_restful.py
- test/test_verifier_db.py
This PR is part of #485 that will create an allowlist table and implement basic CRD API.
The next step will be drop tpm_policy/allowlist from the ``verifiermain`` table and reference the new allowlist table.
> Allowlist management

- installer.sh
> installer: Only install efi library on x86_64 systems

- keylime/ca_util.py
> Remove more commented code in ca_util.py

- keylime/cmd/ima_emulator_adapter.py
This PR cleans up cmd/ima_emulator_adapter a bit more.
> More ima_emulator_adapter cleanups

- keylime/tpm/tpm_main.py
This patch fixes a potential and an actual leaking file descriptor.
> Close leaking file descriptors

- keylime/cmd/user_data_encrypt.py
Patch from Ilhan Gurel (ilhan.gurel@ericsson.com)
> Fix user_data_encrypt to UTF8 decode before print

- agent_non_root_condition.sh
> scripts: Cleanup shell script formatting

- keylime/tpm/tpm_main.py
This PR makes the check_quote function a bit easier to read by moving tpm2_checkquote related code into is own function.
> Move code related to tpm2_checkquote into its own function

- keylime/tenant_webapp.py
In this PR, the unnecessary sorting logic is removed.
Issue:
#634 
Signed-off-by: MartinMa28 <1135485226@qq.com>
> Remove duplicated calls to verifier

- keylime/gpg.py
- keylime/ima.py
- keylime/tenant.py
This PR adds signature verification support for local and remote IMA signature verification keys.
> Add signature verification support for local and remote IMA signature verification keys

- keylime/cmd/user_data_encrypt.py
This bug was partially fixed in PR #638, but not completely. This fixes
the rest of it.
> Fix decoding error in user_data_encrypt

- README.md
Hi, 
while I was trying to configure keylime in my system, I was going through readme and found some minor rendering issues, have fixed in this commit. Please take a look at it, hope it helps somehow.
Thanks for working on keylime! :D
> corrects markdown to have proper rendering

- keylime/tpm/tpm_main.py
This commit is a quick (and admittedly ugly) hack to fix a problem that
has been affecting our production environment. While it partially
addresses #656, we have laid out a 3-phase plan to deal with the problem
in a more consistent and sustainable manner.
> Flush all sessions from TPM device

- keylime/cloud_verifier_tornado.py
- keylime/tenant.py
Patch to support issue #670. 
Signed-off-by: Apoorve Mohan
> Enable tenant to fetch all (or verifier-specific) agents info in a single call to a verifier

- keylime/cloud_verifier_tornado.py
- keylime/cmd/provider_platform_init.py
- keylime/registrar_common.py
- keylime/requests_client.py
- keylime/revocation_actions/print_metadata.py
- keylime/revocation_actions/update_crl.py
- keylime/tpm_bootlog_enrich.py
pylint was updated in the CI to 2.9.3 which resulted in some errors that are fixed with this PR.
> Fixing pylint errors

- keylime/ima.py
The 2 patches in this PR fix a runtime failure and a behavior change. Both are due to the move to 'ast'.
> Fix some issues introduced during the move to 'ast'

- keylime.conf
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/db/registrar_db.py
- keylime/keylime_agent.py
- keylime/migrations/versions/f82c4252bc4f_add_ip_and_port_to_registrar.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/tenant.py
- test/test_registrar_db.py
- test/test_restful.py
Implementation of enhancement proposal keylime/enhancements#50.
Currently tests are missing but I'll add them once I figure out how to run the restful test locally.
> Allow agents to specify a contact ip address and port for the tenant and CV 

- test/test_ima_verification.py
This adds the tests for the IMA behavior regression that were fixed in #706.
I've also added tests to check if the exclude lists actually work.
> tests: extend ima tests for signature validation and exclude lists

- keylime/tenant.py
> Ensures the output of `bulkinfo` command in `keylime_tenant` is JSON

- keylime/tpm/tpm_abstract.py
The old code walked through the PCR list and checked if the PCR belongs to some kind of verification. This is changed so that PCR list is parsed with basic validation to a dictionary and then each type of validation is checked.
I've also moved the `config.STUB_TPM`  check before the validation step because nearly all conditions checked for it manually.
This is in preparation for https://github.com/keylime/enhancements/issues/48 to make it easier to continue validation if one check failed.
> Refacator of check_pcrs to parse then validate

- keylime/api_version.py
- keylime/cloud_verifier_tornado.py
- keylime/config.py
- keylime/keylime_agent.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/tenant.py
- keylime/tenant_webapp.py
- requirements.txt
- test/test_api_version.py
- test/test_restful.py
> Versioned APIs

- keylime/config.py
- keylime/secure_mount.py
- keylime/tpm/tpm_main.py
Looking through the config module I found that there are two functions for converting bytes in a nested object structure to strings. I removed list_convert and the code now uses convert.
> config: merge convert and list_convert into the same function

- .github/workflows/test.yml
Restrict runnning ci jobs only when it's needed.
> Run ci jobs only when needed

- keylime/ima.py
read_allowlist() returns a plain empty list if al_path is None or ''.
However, we should return a dict following the new format since that is
what is returned when the list was converted from a JSON string or
converted from the old flat file format.
Create an empty_allowlist serving as a template to return in case an empty
list is to be returned and to extend when converting from the old flat
file.
Also, the code was reading the contents of the file into alist but this
alist was then never read from. Remove the unnecessary code and only
leave the 'test' for availability of the file.
> ima: Return an empty allowlist rather than a plain empty list

- keylime/keylime_agent.py
The keylime.conf states that when hash_ek is used the uuid is the EK public key in PEM format hashed with sha256. This was not the case instead the internal tss format base64 encoded was hashed.
Now if the TPM has an EK certificate the uuid can be easily derived with:
`tpm2_nvread 0x1c00002 | openssl x509 -inform DER -pubkey -noout | sha256sum`
> agent: ensure that EK is in PEM format when used as uuid

- keylime/tenant.py
Fixes #748.  
Note that this works only for a single agent and not for the bulk operations.
> tenant: status now shows if a agent was added to the registrar

- keylime/cloud_verifier_tornado.py
These were found during testing against the Rust agent.
Signed-off-by: Daiki Ueno <dueno@redhat.com>
> verifier: fix minor typos

- keylime/tenant.py
> Simple fix for tenant error message printout.

- auto-ipsec/libreswan/src/local_action_crashsa.py
- auto-ipsec/racoon/src/local_action_deletesa.py
- demo/agent_monitor/tenant_agent_monitor.py
- doc/freebsd.md
- installer.sh
- keylime/ca_impl_cfssl.py
- keylime/ca_util.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/config.py
- keylime/db/registrar_db.py
- keylime/db/verifier_db.py
- keylime/json.py
- keylime/keylime_agent.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/revocation_actions/print_metadata.py
- keylime/revocation_notifier.py
- keylime/serve_uuid.py
- keylime/tenant_webapp.py
- keylime/tpm/tpm_abstract.py
- keylime/tpm/tpm_main.py
- keylime/vtpm_manager.py
- requirements.txt
- scripts/make_agent_bundle_tarball.sh
- test/test-requirements.txt
- test/test_restful.py
Scipts and docs also updated to reflect that `simplejson` is no longer required.
> Replace simplejson with built-in json module

- GOVERNANCE.md
Also aligning it with the one in [keylime/.github](https://github.com/keylime/.github).
> Small updates to GOVERNANCE.md

- keylime/json.py
- test/test_json.py
- test/test_verifier_db.py
Also add some tests.
Resolves: #800
> json: add support for sqlalchemy.engine.row.Row in newer sqlalchemy

- .gitignore
> Another addition to gitignore

- keylime.conf
> config: private_key must set to -private.pem not -public.pem

- keylime/cmd/ima_emulator_adapter.py
ToMToU errors are handled by the IMA hash, so the correct hash algorithm
needs to be specified there (by default SHA1).
The option for measuring other files than config.IMA_ML was added.
> ima_emulator: fix IMA hash validation and add more options

- keylime/tenant.py
@kkaarreell can you check if it works now for you?
Fixes #832
> tenant: fix reactivate command

- keylime/tpm/tpm_main.py
The file descriptor was never closed.
> tpm_main: close file descriptor for aik handle

- test/test_restful.py
The test now manually generates a x509 certificate for testing instead of trying to initialize an agent for that.
I didn't catch this earlier because the local CI script leaves artifacts which already had the correct data in it.
> tests: fix mtls_cert generation in test_restful.py

- keylime/tenant.py
> Add missing subcommands to -c help message

- keylime.conf
- keylime/keylime_agent.py
> Fix typo for config param listen_notifications

- keylime/registrar_common.py
- keylime/tpm/tpm_main.py
bytes do not work well with postgres and bool is stored as int, so we convert them.
@kkaarreell can you check if that fixes your Postgres issue?
> registrar, tpm_main: ensure that correct types are commited to DB.

- keylime/migrations/versions/1ac1513ef2a1_fix_mb_and_ima_column_types.py
> Ensure columns "mb_refstate" and "allowlist" are of type LONGTEXT in table "verifiermain"

- test/test_restful.py
> Fix incorrect variable name in test_restful

- keylime/crypto.py
- keylime/keylime_agent.py
I've also added the ip where the agent binds to to the certificate.
Fixes #882
> agent, crypto: add localhost, server and contact ip to agent certificate

- packit-ci.fmf
> Fix Packit CI test plan Summary

- .github/workflows/greetings.yml
Fixes a problem noticed in another issue
> Update outdated greetings Github messages

- .github/workflows/container.yml
> Push container images to quay.io/keylime org

- packit-ci.fmf
> Enable test basic-attestation-with-unpriviledged-agent in Packit CI

- keylime/keylime_agent.py
> Fix some remaining log format strings

- README.md
- TESTING.md
> Add TESTING.md describing testing details

- keylime/failure.py
@kkaarreell this should fix the issue for Python 3.6 in #934.
> failure: fix Pattern type hint

- test/run_tests.sh
added opensuse / suse linux enterprise server to test matrix
> added suse / opensuse support with zypper

- doc/cloud-agent-tarball-notes.md
- doc/freebsd.md
- docker/ci/Dockerfile
- docker/ci/Dockerfile-tpm12
- installer.sh
- pylintrc
- requirements.txt
- scripts/make_agent_bundle_tarball.sh
> Remove last traces of M2Crypto

- .github/workflows/submit-PR-coverage.yaml
- .github/workflows/submit-merged-PR-coverage.yaml
- codecov.yml
- scripts/download_packit_coverage.sh
> Enable GitHub workflow integrating codecov.io

- TESTING.md
> Added codecov.io description to TESTING.md

- scripts/download_packit_coverage.sh
> Fix exit call in scripts/download_packit_coverage.sh

- packit-ci.fmf
> Enable test /functional/basic-attestation-without-mtls

- packit-ci.fmf
> Add test /functional/measured-boot-swtpm-sanity to Packit CI plan

- keylime/elchecking/example.py
Older tpm2-tools versions parse the GUID wrong. This extends the example policy to check for both GUIDs (wrongly and correctly parsed one).
Part of: https://github.com/keylime/keylime/issues/1003
> elchecking: add workaround for wrong GUID parsing

- packit-ci.fmf
> Adjust CI test name according to keylime-tests PR#125

- installer.sh
I verifed the same name is used for each dist
> Add python3-alembic to distros

- docs/requirements.txt
- docs/rest_apis.rst
- docs: update API documentation for 2.1, add missing fields for agent quote
- docs: make Python requirements less strict
> Updating API documentation

- keylime.conf
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/keylime_agent.py
- keylime/revocation_notifier.py
This adds support for the agent-local revocation mechanism as described in the [enhancements#53](https://github.com/keylime/enhancements/blob/master/53_agent_local_revocation.md). It's currently draft state, as it lacks tests and protocol version bump.
> Implement agent-local revocation mechanism

- keylime/signing.py
We had error handling in `verify_signature_from_file()`, which was the
only point where we called `verify_signature()`, however a recent allowlist
processing refactoring (#994) added new calls to `verify_signature()`, and these
calls do not properly handle the possible exception it might throw.
Instead of adding error handling to each call of `verify_signature()`, let
us instead catch/log the possible exceptions there, and then we can count
on it always returning a boolean to indicate whether it succeeded or not.
> signing: move exception handing to verify_signature()

- README.md
- docs/installation.rst
- keylime.conf
- test/run_tests.sh
As CFSSL support has been removed (#1012), let's remove some related leftovers.
> Remove CFSSL leftovers

- README.md
Fix URLs not found in project main README Additional Reading section.
> Fix broken URLs in README (Additional Reading)

- packit-ci.fmf
> Update Packit CI to test both agent and zeromq revocation notifiers

- packit-ci.fmf
Update fmf plans for enabling run test which
checking tenant verify options.
Signed-off-by: Patrik Koncity <pkoncity@redhat.com>
> Update fmf plans to run test which checking tenant verify options

- keylime/tenant.py
> Throw an error if --exclude is used without --allowlist

- keylime/tpm_ek_ca.py
> Treat tpm_cert_store as absolute path

- docs/conf.py
- setup.cfg
> Bump version to 6.4.3

- packit-ci.fmf
This new context will be used for proper filtering of relevant tests.
> Define context agent due to keylime-tests PR#193

- keylime/cloud_verifier_tornado.py
Whenever the `verifier` is unable to retrieve the stored_agent data from
the Database (for whatever reason), properly detect and log it. In this
case, instead of continously polluting the log with a ugly python
errors, the `verifier` stops polling the agent.
> Fixes #1046 by explicitly and carefully dealing with a corner case.

- keylime/tpm/tpm_main.py
Newer versions of tpm2-tools escape the strings in the UEFI eventlog [1]. We
remove the qoutes and convert the escaped special characters back to normal
ones.
[1]: https://github.com/tpm2-software/tpm2-tools/commit/c78d258b2588aee535fd17594ad2f5e808056373
> tpm_main: unescape UEFI eventlog strings

- keylime/ca_util.py
This is required when for example the verifier and registrar share the certificates, but run with different users.
Fixes https://github.com/keylime/keylime/issues/1112
> ca_util: allow users in the same group to read the created certificates and keys

- packit-ci.fmf
Signed-off-by: Patrik Koncity <pkoncity@redhat.com>
> Add new tests to packit CI

- keylime/tenant.py
This PR starts the cleanup and fixup of several small issues on `keylime_tenant` code. First of all, make sure all "jsonification" of resquest's responses happen at the static method `_jsonify_response` (renamed from `_print_json_response`) which can now optionally print the response. Second make sure this new function is invoked as often as possible throughout the CLI code, with obvious exceptions being documented. Third, the old `do_cv` method is renamed to `do_cvadd`, in order to improve the code's understandability and maintainability.
This by no means fixes all the problems and issues on `keylime_tenant`, but it is an incremental step in the right direction.
> Very limited code fixup/cleanup on keylime_tenant CLI

- keylime/ima/file_signatures.py
Also accept x509 certificates if they do not have a Subject Key Identifier (SKID). Previously only certificates with SKID were accepted because the SKID is required for the key to be used by the kernel keyrings and keylime would only accept a key that could possibly also have served for IMA signature verification in the kernel.
Return None in case no keyidv2 could be determined either due to missing extensions or missing SKID and warn the use about it.
Signed-off-by Stefan Berger <stefanb@linux.ibm.com>
> ima: Accept x509 certificates if no Subject Key Identifier is available

- docs/conf.py
- setup.cfg
> Bump version number

- packit-ci.fmf
> Enable e2e test functional/tpm-issuer-cert-using-ecc

- keylime/cert_utils.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/crypto.py
- keylime/registrar_common.py
- keylime/revocation_actions/update_crl.py
- keylime/tenant.py
- keylime/tpm/tpm_main.py
This PR provides a batch of type fixes that are:
- non-trivial from the perspective of code behavior
- not concerning IMA (I will create a separate PR for those)
In my local testing setup, they run clean all tests including regression.
> chore: non-obvious type fixes not concerning IMA

- scripts/check_codestyle.sh
- scripts/convert_config.py
- scripts/create_policy
- scripts/templates/2.0/adjust.py
Fix code style issues in python files in scripts directory and add the fixed files to codestyle checking.
> Fix code style issues in python files in scripts dir and add files to codestyle checking

- keylime/da/record.py
- keylime/ima/file_signatures.py
- keylime/json.py
- keylime/revocation_notifier.py
- pyproject.toml
This PR fixes a first batch of issues reported by pyright. @mdrocco
> pyright: Fix a first batch of issues reported by pyright

- keylime/agentstates.py
> codestyle: Add missing type annotations to agentstates.py

- keylime/cert_utils.py
- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/ima/file_signatures.py
> codestyle: Add type annotations to various files

- keylime/ima/ast.py
- keylime/ima/ima.py
Type-annotation all functions in ima/ima.py and fix some potential issues that pyright detected on the way.
> codestyle: Add missing type annotations to ima/ima.py and address issues

- keylime/ca_util.py
- keylime/crypto.py
Add type annotations to crypto.py and address issues detected by pyright.
> codestyle: Add type annotations to crypto.py and address issues

- keylime/cmd_exec.py
> codestyle: Add type annotations to cmd_exec.py

- keylime/common/validators.py
- keylime/ima/ima.py
- pyproject.toml
- test/test_crypto.py
- test/test_ima_verification.py
- test/test_validators.py
- tox.ini
This PR fixes some issues detected by pyright in test cases. Some type checks for other functions need to be relaxed to for example allow 'None' to be passed.
> codestyle: Type annotate and fix some issues in tests cases

- .github/workflows/test.yml
- Makefile
- keylime/config.py
- keylime/ima/ast.py
- keylime/json.py
- mypy.ini
- test-requirements.txt
- tox.ini
- tox: add mypy support
- json: allow ignore comment to be parsed by mypy
- ima/ast: add missing type hints
- config: add missing type hints
- ci: add mypy to CI
> Enable mypy in CI and add full type annotation for config and ima AST

- keylime/cert_utils.py
- pyproject.toml
- test/test_ca_util.py
This PR address some issues detected by pyright for 2 more test cases.
> codestyle: Address some issues detected by pyright for 2 test cases

- keylime/cloud_verifier_tornado.py
> codestyle: Fix typo in annotation

- keylime/ca_impl_openssl.py
- pyproject.toml
- test/test_ca_impl_openssl.py
Enable two more test to be type-checked
> codestyle: Enable two more test to be type-checked

- keylime/crypto.py
- mypy.ini
> codestyle: Add missing annotations to crypto.py and add to mypy

- keylime/secure_mount.py
- mypy.ini
> codestyle: Type-annotate secure_mount.py

- keylime/elchecking/__main__.py
- keylime/elchecking/example.py
- keylime/elchecking/policies.py
- keylime/elchecking/tests.py
- mypy.ini
- codestyle: add type hint to tpm class constructor
- codestyle: add type hints to elchecking module
> codestyle: add type hints to elchecking module

- keylime/cloud_verifier_tornado.py
This PR fixes some issue with type annotations in the verifier.
> codestyle: Fix some issues with type annotiations in the verifier

- keylime/measured_boot.py
- keylime/tpm/tpm_abstract.py
- mypy.ini
> codestyle: Type-annotate measured_boot.py and add to mypy

- keylime/ima/ima.py
The "allowlist" field on IMA policy (JSON) has, inside its "meta" subfield, a "timestamp" key,value pair (generated at the `verifier`). Due to this fact, whenever the `checksum` (over the whole policy) is calculated (also) at the `verifier`, the end result is different values for policies which are actually identical (minus the aforementioned `timestamp`).
While it could be possible to simply remove this timestamp, in order to prepare for future changes (such as PR #1147), this PR simply truncates the actual value of the timestamp, as it has no relation to the contents (e.g., "allowlist") of the IMA policy.
> verifier: fix for IMA policy checksum calculation

- keylime/common/algorithms.py
- keylime/common/exception.py
- keylime/common/migrations.py
- keylime/common/retry.py
- keylime/common/states.py
- keylime/common/validators.py
- mypy.ini
- test/test_retry_algo.py
> codestyle: Add missing type annotions to files in common & add to mypy

- keylime/revocation_actions/print_metadata.py
- keylime/revocation_actions/update_crl.py
- mypy.ini
> codestyle: Type-annotate files in revocation_actions & add to mypy

- packit-ci.fmf
> CI tests: Do not remove Fedora tag repository

- keylime/cmd/agent.py
- keylime/cmd/ca.py
- keylime/cmd/convert_ima_policy.py
- keylime/cmd/ima_emulator_adapter.py
- keylime/cmd/registrar.py
- keylime/cmd/tenant.py
- keylime/cmd/user_data_encrypt.py
- keylime/cmd/verifier.py
- keylime/keylime_agent.py
- keylime/registrar_common.py
- keylime/tenant.py
- mypy.ini
This PR type-annotates and adds all files in keylime/cmd to mypy.
> Type-annotate and add all files in keylime/cmd to mypy

- keylime/cloud_verifier_tornado.py
This is a minimalistic implementation, using a python dictionary named GLOBAL_POLICY_CACHE (name inspired by GLOBAL_TPM_INSTANCE in cloud_verifier_common.py), indexed by agent UUID, to hold the contents (string) of whole ima_policy column as read from the `allowlists` table on the database. While theoretically not memory efficient, indexing the dictionary by agent UUID ensures only a single worker will write a key simultaneously, thus making explicit locks unnecessary.
This implementation was experimentally checked for scalability (more than 100 `agents` per `verifier` with ~ 25MB unique allowlist per `agent`, stored on a database shared across 10 `verifiers`) and also for efficient memory usage (orders of magnitude below the theoretical O(N*M)).
Two simple cleanup routines are also …
> verifier: a (very simple) cache implementation for IMA policies (solves #1167)

- .github/workflows/submit-HEAD-coverage.yaml
- packit-ci.fmf
- scripts/download_packit_coverage.sh
> Switch code coverage measurement to Fedora 37

- docs/installation.rst
- keylime/ima/ima_dm.py
- mypy.ini
- requirements.txt
This adds type hints to all of the functions in ima_dm. I'm currently waiting for https://github.com/keylime/keylime/pull/1180 to finalize this PR.
> ima_dm: add type checks and hints

- keylime/cli/options.py
- keylime/cli/policies.py
- mypy.ini
This PR adds type-annotations to files in the cli directory and adds them to mypy
> Type-annotate files in the cli directory and add them to mypy

- packit-ci.fmf
> packit-ci: Add hotfix for tpm2-tss Fedora BZ#2158598

- TESTING.md
> Extend test execution instructions in TESTING.md

- keylime/tenant.py
As discussed in issue #1158, there are real-world scenarios where "add" and/or "delete" operations via `keylime_tenant` CLI causes it to return before the data was written by `verifier` on the database. This causes inconsistent "status" (also via `keylime_tenant`) for a given `agent`, in case the CLI invoked within a small time window after "add"/"delete".
Given the fact the code for `keylime_tenant` was somewhat messy (e.g., a fixed 12-step loop with 0.4 seconds between attempts on "delete"), this new code uses the already existing "retry_interval", "exponential_backoff", and "max_retries" attributes to implement an ordered "status" polling on the `verifier` right after an "add" or "delete" operation, only returning when the desired state and the actual state effectivelly match (or …
> tenant: reliable and consistent add/delete operations (fixes #1158)

- keylime/cmd_exec.py
- keylime/db/keylime_db.py
- keylime/requests_client.py
- keylime/revocation_actions/update_crl.py
- keylime/tornado_requests.py
- mypy.ini
This PR annotates files to be able to add them to mypy and also changes the list of files in mypy.ini to the list of unchecked files.
> Add various files to mypy and invert mypy list to unchecked files

- docs/conf.py
- setup.cfg
> Bump version number to 6.5.3

- pylintrc
> pylintc: Remove outdated modules from list of ignore modules

- scripts/create_policy
> script: Remove unused argument argv

- keylime/tpm/tpm_abstract.py
- keylime/tpm/tpm_main.py
- mypy.ini
Annotate tpm_abstract.py and tpm_main.py and add to mypy.
> Annotate tpm_abstract.py and tpm_main.py and add to mypy

- keylime/registrar_client.py
- keylime/tenant.py
- mypy.ini
- pyproject.toml
- requirements.txt
This PR annotates the keylime tenant tool and 2 dependencies.
> codestyle: Annotate the keylime tenant tool and 2 dependencies

- keylime/registrar_common.py
- mypy.ini
> codestyle: Annotate registrar_common.py and add to mypy

- keylime/cloud_verifier_tornado.py
This PR adds some more annotations to cloud_verifier_tornado.py that PR #1272 does not cover.
> Steps to annotate cloud_verifier_tornado.py

- keylime/cloud_verifier_common.py
- mypy.ini
> codestyle: Fully annotate cloud_verifier_common.py and add to mypy

- keylime/cloud_verifier_tornado.py
This PR addresses some issues related to pyright in cloud_verifier_tornado.py that PR https://github.com/keylime/keylime/pull/1272 does not cover.
> More steps to annotate cloud_verifier_tornado.py

- keylime/cloud_verifier_tornado.py
- pyproject.toml
> fix: type issues in verifier's code

- packit-ci.fmf
> e2e tests: Fix test name

- keylime/cloud_verifier_tornado.py
- keylime/db/keylime_db.py
- keylime/registrar_common.py
- mypy.ini
- test/test_registrar_db.py
- test/test_verifier_db.py
> codestyle: Fully annotate cloud_verifier_tornado and add to mypy

- ROADMAP.md
This updates the roadmap with the major changes planned for Keylime in 2023.
Please have a look and see, if the goals are defined well enough and if I forgot something to add.
> roadmap: update for 2023

- MAINTAINERS.md
This PR is for me to step down as PTL of the project and let someone else have a chance to run as PTL for a term.
I will still 100% be active on the project.
I would also like to make a proposal of @maugustosilva taking over from me. Marcio has been very active in the keylime community for several years in developing new features, reviewing code and working with others on their designs.
The process is outlined here:
https://github.com/keylime/keylime/blob/master/GOVERNANCE.md#changes-in-project-lead
Typically the PR should be opened no earlier then 6 weeks before the end of term, however I'm willing to move sooner if the community agrees.
At the same time, anyone else is welcome to raise a PR with a nomination of their own.
I will leave this PR open for 2 weeks (unless objections are made …
> End of term for @mpeters + propose @maugustosilva

- test/test_api_version.py
- test/test_validators.py
- test/test_version.py
* Introduce unittest subtests
* We can differentiate between test case definitions and testing code.
* All subtests will be executed, even when the previous one failed.
* When a test fails, we can see a message to identify the test case.
* Fix typo
> Refactor tests

- keylime/config.py
- keylime/keylime_logging.py
> log: add a barebones log config in case configuration files not present

- keylime/da/attest.py
`keylime_attest` CLI will build a list of nodes which failed at some point in the recorded history of attestation artifacts on the persistent store, and in case this list is non-empty, the exit code will be non-zero.
Fixes #1334
> da: non-zero exit code for attestation replay failures.

- packit-ci.fmf
Also set boolean faked_measured_boot_log to yes.
> Add missing test from keylime testsuite to e2e plan

- keylime/ip_util.py
- keylime/registrar_client.py
- keylime/registrar_common.py
- keylime/tenant.py
Set self.address_family to socket.AF_INET6 if the provided IP address to bind to is an IPv6 address.
Resolves: Issue #1315
> registrar: Detect IPv6 addresses to bind to and set address_family

- docs/installation.rst
> docs/installation.rst: add the missing popd command in the manual deployment.

- docker/release/base/Dockerfile.in
The git cherry-pick command requires a valid email address and name to function.
> docker: fix tpm2-tools build

- .github/workflows/test.yml
- keylime/cloud_verifier_tornado.py
- keylime/registrar_common.py
Also add a patch related to the import location of NoResultFound that pyright complains about.
> CI/CD: Run pyright as part of tox

- keylime/cloud_verifier_tornado.py
- keylime/registrar_common.py
pyright 1.1.306 now detects the following issue for which there doesn't seem to be a good solution:
/home/stefanb/keylime/keylime/cloud_verifier_tornado.py
/home/stefanb/keylime/keylime/cloud_verifier_tornado.py:1281:12 - error: Invalid conditional operand of type "ColumnElement[bool]"
  Method __bool__ for type "ColumnElement[bool]" returns type "NoReturn" rather than "bool" (reportGeneralTypeIssues)
/home/stefanb/keylime/keylime/cloud_verifier_tornado.py:1289:12 - error: Invalid conditional operand of type "ColumnElement[bool]"
  Method __bool__ for type "ColumnElement[bool]" returns type "NoReturn" rather than "bool" (reportGeneralTypeIssues)
/home/stefanb/keylime/keylime/cloud_verifier_tornado.py:1464:12 - error: Invalid conditional operand of type "ColumnElement[bool]"
  Method …
> codestyle: Add pyright ignore annotations due to pyright 1.1.306

- keylime/web_util.py
> web_util: handle tls_dir default with cacerts correctly

- docs/rest_apis.rst
> docs/rest_apis.rst: remove the comma at the end of the JSON string

- docs/installation.rst
This setup is no longer maintained.
> docs: remove Vagrant setup

- keylime/registrar_common.py
Consolidate the repetitive checking of input parameters into reusable functions.
> Registrar: Consolidate repetitive checking of input parameters

- keylime/cloud_verifier_tornado.py
Consolidate the check of input parameters in the various methods of the AgentsHandler. Ensure that all nuances of slightly different handling of agend_id are reflected in the common code.
> cloud_verifier: AgentsHandler: Consolidate checking of input parameters

- keylime/ima/ima.py
This PR does some cleanups and simplifications on IMA code.
> IMA: cleanups and simplifications

- keylime/agentstates.py
- keylime/common/algorithms.py
- keylime/elchecking/tests.py
- keylime/ima/ast.py
- keylime/tpm/tpm_main.py
- test/test_ima_verification.py
This PR replaces the usage of codec for writing and parting of hext strings with methods on bytes. It also does other simplifications and cleanups.
> Replace usage of codec for writing and parsing of hex string with methods on bytes and more cleanups

- keylime/cloud_verifier_tornado.py
- keylime/web_util.py
> Yet more cleanup

- keylime/tenant.py
This PR is one more which modifies the log messages (this time with the introduction of a "full ID string") in order to make easier to observe and debug Keylime with tools such as Elasticsearch/Kibana (e.g., by using the `agent`'s UUID as a search term to aggregate all events). This rewriting of log message resulted in the elimination of several poorly written messages.
This PR also ensures the output of commands `bulkinfo`, `status`, `cvstatus`, `regstatus`, `reglist`, `cvlist` is "consumable" by a tool such as `jq` (something like "<command> | grep ^{ | jq ." will work)
> tenant: log cleanup and output improvements

- keylime/registrar_common.py
This PR fixes an issue in the Keylime Registrar that allows performing a DoS by opening a single connection to its HTTPS interface. As long as the connection is open, the Register is blocked and cannot serve any further clients, which prevents the Register from working as expected.
The issue happens as Python SSL sockets block by default, unlike regular sockets. To fix this, a non-blocking SSL handshake is implemented. The fix is inspired by Python's documentation on non-blocking SSL sockets (https://docs.python.org/3/library/ssl.html#notes-on-non-blocking-sockets).
A cleaner solution would be using the tornado framework in the Registrar (like in the Verifier). However, this requires several changes to the Registrar code.
> Non-blocking Registrar SSL socket

- keylime/tenant.py
The tenant code is neither organized nor consistent when it comes to exit codes in case of error. This PR addresses this problem by removing all the `sys.exit()` calls and replacing it with the "standard", which seems to be the use of `raise UserError`.
Fixes #1413
> tenant: non-zero exit code in case of error

- templates/2.0/mapping.json
> templates/2.0/mapping.json: fix the default registrar_port error in the verifier config

- .github/workflows/container.yml
> Update container build workflow actions

- keylime/cloud_verifier_tornado.py
Automatically update the agent supported API version in the database if the agent is updated and its API version is bumped.
Previously, if an agent was added to a verifier while it used an old API version, and then it is updated with an API version bump, the attestation would fail as the verifier would try to reach the agent using the old API version.
Fixes #1457
> Implement automatic agent API version bump

- tpm_cert_store/Nationz_TPM_EK.pem
Besides, the Nationz TPM EK x509 cert can be downloaded at
http://pki.nationz.com.cn/EkMfrCA001/EkMfrCA001.crt
Signed-off-by: Jiannan.Yin <yinjn1@lenovo.com>
> tpm_cert_store: add the Nationz TPM EK x509 cert

- packit-ci.fmf
Recently in keylime test suite were prepared new
tests for covering new functionality. Update packit plan to use them in CI.
> Update packit plan with new tests

- docs/conf.py
- docs/index.rst
- docs/publications.bib
- docs/publications.rst
- docs/requirements.txt
This adds an initial additional reading section based on the list from @maugustosilva and @galmasi plus some additional papers and talks that I found.
> docs: add additional reading section

- keylime/cloud_verifier_tornado.py
- keylime/mba/elchecking/tests.py
- keylime/tpm/ec_crypto_helper.py
- test/test_ima_verification.py
Some issues previously detected by pyright (false-positives) have been resolved and therefore their ignore comments can be removed. In other cases add new ignore comments to fix the following issues:
.../cloud_verifier_tornado.py:374:22 - error: "filter_by" is not a known member of "None" (reportOptionalMemberAccess)
.../cloud_verifier_tornado.py:398:26 - error: "filter_by" is not a known member of "None" (reportOptionalMemberAccess)
.../cloud_verifier_tornado.py:409:26 - error: "all" is not a known member of "None" (reportOptionalMemberAccess)
.../cloud_verifier_tornado.py:682:37 - error: Expected no arguments to "VerfierMain" constructor (reportGeneralTypeIssues)
.../cloud_verifier_tornado.py:755:21 - error: Object of type "None" cannot be called (reportOptionalCall) …
> codestyle: Address some issues detected by pyright

- ROADMAP.md
This is the initial update for the roadmap. Do we want to include the current Kubernetes efforts?
> update roadmap for 2024

- .packit.yaml
- keylime/mba/elparsing/tpm2_tools_elparser.py
> elparser: add different escaping required for tpm2-tools >= 5.6

- docs/user_guide/user_selected_pcr_monitoring.rst
The old example did not work anymore with current Keylime versions.
Fixes: #1529
> docs: update PCR monitoring example

- docs/user_guide/user_selected_pcr_monitoring.rst
> docs: fix rendering in PCR example

- keylime/cloud_verifier_common.py
- keylime/cloud_verifier_tornado.py
- keylime/da/attest.py
- keylime/da/examples/file.py
- keylime/da/examples/redis.py
- keylime/da/examples/sqldb.py
- keylime/da/record.py
- keylime/db/verifier_db.py
- keylime/migrations/versions/32902c0a8d90_add_mbpolicies_table.py
- keylime/migrations/versions/9d2f6fab52b1_associate_moved_mb_refstates_to_agents.py
- keylime/migrations/versions/f4196d13fe45_migrate_mb_refstates_to_mbpolicies.py
- test/test_verifier_db.py
In the next PR, similar to named runtime policies, this table will be used to provide support for named measured boot policies and thier management.
> mba: Add a separate table for measured boot policies.

- keylime/da/attest.py
- packit-ci.fmf
> Fix durable attestation in absence of mb_policy

- keylime/cmd/sign_runtime_policy.py
Instead of showing an assert and traceback display a user-friendly
message when the user provides anything else than an EC private key.
> sign_runtime_policy: Display error message if non-EC key is provided

- .github/workflows/container.yml
- .github/workflows/update-base-image.yml
This typo is preventing the image building to succeed
EDIT: Also add a sign-off to the automatic base image update PR
> workflows: Fix typo and add a sign-off on the automatic PR

- .github/workflows/base-image.yml
- .github/workflows/update-base-image.yml
- docker/ci/Dockerfile
Previously, the image used for CI was not automatically built.
> docker: Build CI image together with the base image

- docker/ci/Dockerfile
Add python3-gpg to the CI container image.
> docker/ci: Add test dependency needed for PR#1568

- .github/workflows/base-image.yml
- .github/workflows/update-base-image.yml
Fix the build context for the CI image to have access to a file.
Include the CI image Dockerfile in the automatic pull request.
> workflows/base-image: Fix CI image build context

- packit-ci.fmf
Enable new test in Packit CI pipeline.
> tests: Enable test /sanity/opened-conf-files

- docs/rest_apis.rst
- keylime/cloud_verifier_tornado.py
- keylime/tenant.py
Add listruntimepolicy option with 'keylime_tenant -c' to list names of the runtime policies.
> ima: list names of the runtime policies

- packit-ci.fmf
This enables a test for IDevIDs and IAKs that are persisted in the TPM and are accessed via handle rather than regenerated. These keys may also be protected by password, this is also tested, as is the change to enable hex passwords for the TPM.
> Enable test functional/iak-idevid-persisted-and-protected

- keylime/cert_utils.py
> cert_utils: add description why loading using cryptography might fail

- packit-ci.fmf
This reverts commit 7671d60a4745b750986a0d4020b97a5ec2544195.
> Revert "DO NOT MERGE, TEMPORARY COMMIT"

- packit-ci.fmf
Before running tests apply workarounds to known
distribution bugs so we reduce the amount of
test failures.
> tests: apply workarounds to known bugs

- keylime/policy/create_runtime_policy.py
- test/test_create_runtime_policy.py
> policy/create_runtime_policy: fix handling of empty lines in exclude list

- keylime/cert_utils.py
Fixes [1612](https://github.com/keylime/keylime/issues/1612)
This changes the `check_tpm_origin` check in `cert_utils.py` to emit warnings if the SAN or hardware filed in the SAN are missing but still return true, and return false an incorrect HW identifier is provided.
The possibilities are:
* SAN missing: warn and pass
* SAN present but relevant hw field missing: warn and pass
* SAN present with HW info: pass or fail with error based on hw ID, no warning either way
> Change check_tpm_origin check to a warning that does not prevent registration

- docs/installation.rst
- docs/user_guide.rst
- docs/user_guide/idevid_and_iak.rst
- **docs: point to installation guide from RHEL and SLE Micro**
- **docs: include IDevID page also in the sidebar**
> docs: add distro installation instructions and include IDevID also in sidebar

- installer.sh
I've only tested this on Debian 12, but should be the same for Ubuntu
> installer.sh: update package list, add workaround for PEP 668

- MAINTAINERS.md
This PR is for me to step down as PTL of the project and let someone else have a chance to run as PTL for a term.
I will still be active on the project.
I would also like to make a proposal of @ansasaki taking over from me. Anderson has been very active in the keylime community for several years in developing new features (with emphasis on Keylime Rust agent), reviewing code and working with others on their designs.
The process is outlined here:
https://github.com/keylime/keylime/blob/master/GOVERNANCE.md#changes-in-project-lead
Typically the PR should be opened no earlier then 6 weeks before the end of term, however I'm willing to move sooner if the community agrees.
At the same time, anyone else is welcome to raise a PR with a nomination of their own.
I will leave this PR open for 3 …
> End of term for @maugustosilva + propose @ansasaki

- scripts/download_packit_coverage.sh
Instead of using an intermediary files storage service, download the file directly from the Testing Farm artifacts storage.
> scripts: Download coverage data directly from Testing Farm

- docs/conf.py
- setup.cfg
> Bump version to 7.12.0

- docs/conf.py
- setup.cfg
> Bump version to 7.12.1

- keylime/models/base/types/base64_bytes.py
Fix the warnings introduced by latest mypy
> lint: Fix mypy warnings

- keylime/tpm/tpm_util.py
This fixes the signature extraction for ECDSA signatures and unblocks: https://github.com/keylime/rust-keylime/pull/846
> tpm_util: fix quote signature extraction for ECDSA

- .ci/run_local.sh
- docker/release/build_locally.sh
Minimum change to allow CONTAINER_ENGINE
environment variable to be set with a
different container engine (i.e.podman)
`CI: Enable CONTAINER_ENGINE to allow alternative container engines`
N/A
Test run are normally executed locally before pushing changes to ensure regression tests are OK and nothing is broken. However, tests are run through docker, and can not be executed with other container engine (i.e.`podman`).
Allow using a different container engine rather than `docker` through `CONTAINER_ENGINE` environment variable. If nothing is provided, `docker` will be used by default (as it is now)
1 - Configure machine where docker is not installed (only podman is)
2 - Execute ci tests:
```bash
$ .ci/run_local.sh
Fetching Keylime CI container
.ci/run_local.sh: line …
```
> CI: Enable CONTAINER_ENGINE to allow alternative container engines

- keylime/cloud_verifier_tornado.py
**See also:** [#1772](https://github.com/keylime/keylime/issues/1772)
With Python 3.14 a default `multiprocessing` start method has changed from `fork` to `forkserver`. As a consequence, `keylime_verifier`\ cannot start due to various pickling issues.
This is a quick fix to make `keylime_verifier` work again as a proper fix would require a bigger rewrite.
Use `fork` as `multiprocessing` start method
Multiprocessing on Python 3.14 (using forkserver or spawn) must pickle the target function.
Only top-level module functions are pickleable—local functions are not. `server_process()`  is defined within `main()` and therefore pickling fails. Beside `server_process()` function itself `pickle` will fail also on `SSLContext` and possibly other objects.
1. Describe test …
> fix: Use `fork` as `multiprocessing` start method

- templates/2.5/agent.j2
- templates/2.5/ca.j2
- templates/2.5/logging.j2
- templates/2.5/mapping.json
- templates/2.5/registrar.j2
- templates/2.5/tenant.j2
- templates/2.5/verifier.j2
Add 2.5 templates to include Push Model agent changes
This commit introduces the necessary configuration template files for version 2.5. These new templates add the required configuration options to support the new agent operating in push mode.
The update follows the established configuration upgrade process by creating a new version directory and defining a non-breaking, minor version update.
Configuration changes motivated from Push Model implementation:
- Includes configuration to access Verifier.
- Includes configuration related to exponential back-off.
*(Check all that apply)*
New configuration values can be read from agent.
*(Optional: follow-up tasks, special considerations)*
> Add 2.5 templates including Push Model agent changes

- docs/conf.py
- docs/index.rst
- docs/man/keylime_tenant.1.rst
Manpage for keylime_tenant binary
- [ *] Documentation update (standalone)
**Resolves:** #1035 
I created manpage for keylime tenant and also included this binary in sphinx config so this manpage is also included in keylime documentation
Use bullet points where appropriate:
- Keep items concise
- Separate with blank lines
- Maintain consistency
*(Check all that apply)*
- [* ] Updated markdown docs (file path: ______)
- [* ] Code follows project style guidelines
- [* ] Documentation updated (per above section)
*(Optional: follow-up tasks, special considerations)*
> Manpage for keylime_tenant binary

- keylime/policy/sign_runtime_policy.py
policy/sign: use print() when writing to /dev/stdout
Do not open sys.stdout, as it is already open. Just use it, when it is the destination.
*(Check all that apply)*
1. Describe test environment
2. Step-by-step validation procedure
3. Expected vs actual results
*(Optional: follow-up tasks, special considerations)*
> policy/sign: use print() when writing to /dev/stdout

- packit-ci.fmf
Enable new tests for different TPM signing and encryption algorithms in CI.
Enable following e2e tests in CI:
agent-registration-with-non-default-tpm-algorithms/ecc256-ecschnorr
agent-registration-with-non-default-tpm-algorithms/ecc384-ecschnorr
agent-registration-with-non-default-tpm-algorithms/rsa2048-rsassa
agent-registration-with-non-default-tpm-algorithms/rsa3072-rsapss
Tests functionality enabled in the rust-agent through https://github.com/keylime/rust-keylime/pull/1132 
Will be tested by CI, tests are expected to pass.
> tests: Enable more TPM tests in CI
